apiVersion: v1
kind: Secret
metadata:
    name: labgrid-ts-auth-source
    namespace: lab
type: Opaque
stringData:
    authkey: ENC[AES256_GCM,data:SCa0Xi+RiTSOVN5cEPsr5PT5fdyLWgV+Wo7dwD3S8Z5sKRX9lR7eMWtQqgA/x5VFHfAMJ4HEGgyfvsunY5I9yQS0CffkL/H8cUSTKJ5jSZZpzfk/pKJNsg==,iv:Qx3bj/tmpar5MbPV8Fe2Ci+ePPG34ORg3EPaGxRlTTk=,tag:htSjuzk7uVVbN5tybcd6iw==,type:str]
sops:
    age:
        - recipient: age1r8tha72lm6j96pre8qrlxj2nyyzm9cq38umh9dcd2kf5hhjnqsfqe6saex
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMTXF0UjIwMG9la3MxTVEx
            bEkrTDBhUU5IcS9PMHo1S1FwcWxXSVpkMVdjCnpLRUhHYzM2OGU4UWE3QUthUVor
            b1Rja3lGM0NvY0pkd25TYTRFZGNVR2MKLS0tIHYzSDQ5Q3kwamFndm4wR3pkWFF4
            b3pmZTMrRkI1ZHAxTDRSbm5uK1JWRWMK0xlKOFySDqgehc+K9e2d+b1H0DBVH5NV
            +K3WQfoSLaysmIC9VVSop1suiLUv5O9N5MkwfhbsGVJB55hfgZfgcA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14taxy23wzym2r9jndzsq5h8dx2f5cj5vtusfet2ggjjepp8pkfdqf6mus0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJcmlTbmdkOEFKVFhqS3o2
            R0NPYlBpeEZJYXVoZnd2Rm9STG4xbTNoaWhjCkc1YkdrQmlVZmJRRTd1ODNQYWFk
            eHMwT0FNOWhLY3dQRzlEMmFvRDhRNzgKLS0tIDVkdjVVZ204dklPWUh4NTUvOUtY
            S1BhVmJJTVpMMGt3WDdvT0tsdW1jS3cKzJw0SQosbvmhJM1OOmw1Di9jb1s3lMwK
            3OfKKqmo+2GNj4fIHTi5fu1/sMNnzSt25T9bKUs964bvwDp7YzzZ0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-29T06:22:59Z"
    mac: ENC[AES256_GCM,data:gtfc0LDO5uOd4EfnO9uxpNF2adYfketKiXTs7X6jRH8OouJVT3CXtMLtuyvw1IvqKVykDcq55Hh/hI/TTSJ82HpyvQqJQo4WY469QtU+F9JkMjY4pixiqDpa9q281WmAfHSRpD5nWts8y38uOZBGG36Y48/7diUw9EDEl4BocRM=,iv:2GgxmDwSPHxknUQPa2OQ732lpp5OayWApD9aH9K17oo=,tag:UoXZaYtuVYSw4cOfFdF1zg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
