---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bl-controllers
  namespace: edge
spec:
  chart:
    spec:
      chart: charts/binarylane-controllers
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: binarylane-controllers
        namespace: flux-system
  dependsOn:
    - name: control-plane
    - name: bl-controllers-config
  interval: 1h
  postRenderers:
    - kustomize:
        patches:
          - target:
              group: apps
              version: v1
              kind: Deployment
            patch: |
              - op: add
                path: /spec/template/spec/volumes/-
                value:
                  name: kubeconfig
                  configMap:
                    name: kubeconfig
              - op: add
                path: /spec/template/spec/volumes/-
                value:
                  name: cert
                  secret:
                    secretName: admin
              - op: add
                path: /spec/template/spec/containers/0/volumeMounts/-
                value:
                  name: kubeconfig
                  mountPath: /kubeconfig
                  subPath: kubeconfig
              - op: add
                path: /spec/template/spec/containers/0/volumeMounts/-
                value:
                  name: cert
                  mountPath: /cert
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: KUBECONFIG
                  value: /kubeconfig
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: TMPL_TS_AUTH_KEY
                  valueFrom:
                    secretKeyRef:
                      name: node-ts-auth
                      key: key
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: TMPL_BOOTSTRAP_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: bl-controllers-config
                      key: token
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: TMPL_CA_HASH
                  valueFrom:
                    configMapKeyRef:
                      name: ca-hash
                      key: hash
          - target:
              group: rbac.authorization.k8s.io
              version: v1
              kind: ClusterRole
            patch: |
              $patch: delete
              apiVersion: rbac.authorization.k8s.io/v1
              kind: ClusterRole
              metadata:
                name: unused
          - target:
              group: rbac.authorization.k8s.io
              version: v1
              kind: ClusterRoleBinding
            patch: |
              $patch: delete
              apiVersion: rbac.authorization.k8s.io/v1
              kind: ClusterRoleBinding
              metadata:
                name: unused
  values:
    existingSecret: bl-token
    deployment:
      annotations:
        reloader.stakater.com/auto: "true"
    autoscaler:
      enabled: true
    mtls:
      enabled: true
      clientSecretName: binarylane-controller-mtls-client
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bl-controllers-config
  namespace: edge
spec:
  chart:
    spec:
      chart: hub/cluster/edge/bl-config
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: infra
        namespace: flux-system
  interval: 1h
  valuesFrom:
    - kind: Secret
      name: node-bootstrap-token
      valuesKey: id
      targetPath: token.id
    - kind: Secret
      name: node-bootstrap-token
      valuesKey: secret
      targetPath: token.secret
