---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bl-controllers-ca
  namespace: edge
spec:
  commonName: bl-controllers-ca
  duration: 87600h # 10 years
  isCA: true
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
  secretName: bl-controllers-ca
  privateKey:
    algorithm: ECDSA
    size: 256
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: bl-controllers-ca
  namespace: edge
spec:
  ca:
    secretName: bl-controllers-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bl-controllers-mtls-server
  namespace: edge
spec:
  secretName: bl-controllers-binarylane-controllers-mtls-server
  commonName: bl-controllers-binarylane-controllers
  dnsNames:
    - bl-controllers-binarylane-controllers.edge.svc
    - bl-controllers-binarylane-controllers.edge.svc.cluster.local
    - localhost
  duration: 8760h # 1 year
  issuerRef:
    name: bl-controllers-ca
    kind: Issuer
  usages:
    - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bl-controllers-mtls-client
  namespace: edge
spec:
  secretName: binarylane-controller-mtls-client
  commonName: cluster-autoscaler
  duration: 8760h # 1 year
  issuerRef:
    name: bl-controllers-ca
    kind: Issuer
  usages:
    - client auth
