apiVersion: v1
kind: Secret
metadata:
    name: bl-token
    namespace: edge
stringData:
    BL_API_TOKEN: ENC[AES256_GCM,data:eeb3/pGLaePYsUnMc9PRyl1XOz/rYremSmBjN/tz9HpXbH0cBKAC/+9TvJexE0JZ9jzy35D2gJ7NwFotLlCGNg==,iv:yppMOL0ux+H94pWkfcg9mli2TWgqcg6UnJLHGzeZ3o8=,tag:FpszjVrMXL/mEX0xb5ssew==,type:str]
sops:
    age:
        - recipient: age1tu8l2llfk32g0c4mvklqazjkj977h9xwvx3ntwt2ucdert8sufgq2g8mgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpMUNKUUVadEpaL2FQZXVk
            cFE3aUk0TnV3bUkzTW5Xd2cyQWlvUXNHUFRrCmdLcXZBakJBYmlDdHNHbWMwUUNG
            OGd0ZEhqT1dRbGVKTnUxTGlhcms5bG8KLS0tIDhpVytjZnV3S2xnenUrcE9aYndM
            RHp0cEhTUTRTZ1dFOC9jaWpqSldQQXcKIXarHzWmckanLexhzebFjUluET8+gbxY
            ejEHkcv3yW7XzX5VRKVpLPW/BZW3yEkwnVuxHvzwYxvLoZIlB56O3w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14taxy23wzym2r9jndzsq5h8dx2f5cj5vtusfet2ggjjepp8pkfdqf6mus0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBleUYxajltd2lJaVZSV0FN
            R1FHWjY5c2JZUlFBdyt5WlNybVlkWjc2ZGtjCkh1ZGYrUHJ4Q2liT2hKNC9jMk9L
            ZjJnOHNrWk5hbElQbWFGajY0cE9FMU0KLS0tIC90cWVQenIvajRCcnpIYVpsY05C
            ZnhpOGhCenNPQ2RieGZkamtqY2k5Z00KpOatEEd70PxKJ7wbFCvKhAo7zDUUfQXm
            PeJlEahqDg1xhdeAsaad/5qqnlF+vnxDan5jqO/yquD6Ft5IasM/sw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T09:33:00Z"
    mac: ENC[AES256_GCM,data:BxWeVV4ydxokNlrFe8fb0JkPAXlOIRu3jo82umOn0xmiOKU1YuRnGlasQYmCFCinLH+gEnz+jgB2QsKAWMiRS122o1ju8eMeKa5UczZyuXEqg4cWL/UUSfHKXtyyEMJU4YC2pMHOinfXIaOPW0n65JbJ2WhuVKDyTM6LxgnI0hI=,iv:ySBEzfuWUQHUXGEHCh+oYroGXQcSiPnjBKD2naKuTug=,tag:rz8yUH+ZVjSf3U2WoNjhxA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
