apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: control-plane-values
    files:
      - values.yaml=control-plane-values.yaml
namespace: edge
resources:
  - ../../../.kustomize-config
  - bl-controllers.yaml
  - bl-controllers-mtls.yaml
  - bl-crds.yaml
  - bl-token.yaml
  - cluster-autoscaler.yaml
  - control-plane.yaml
  - kustomizations.yaml
  - namespaces.yaml
  - node-bootstrap-token.yaml
  - node-joiner
  - ts-apiserver.yaml
  - wasmcloud.yaml
  - wasmcloud-demo.yaml
  - wasmcloud-monitoring.yaml
