apiVersion: v1
kind: Secret
metadata:
    name: hcloud
    namespace: fastboop
stringData:
    token: ENC[AES256_GCM,data:00m+nqFYx6fd0ziMNKKsbY1i+eXVfIYN/DQq2XLTa2WuQmCvSddUehI2VhFbZ7CnA97zjRzLXT9HTyq67lw7NQ==,iv:/t6F2j5fLwgXipVHfUxd76ingDoGEuBEdD27kdjW3ok=,tag:1GEqNZ8Tzid2tD5nAAAAqA==,type:str]
sops:
    age:
        - recipient: age1tu8l2llfk32g0c4mvklqazjkj977h9xwvx3ntwt2ucdert8sufgq2g8mgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRdys2UE9ucUVRR2ErOHJ0
            SWhndStpNXFXTkJpNUpYM2VIOEgwK0R6ZTF3Cm4rclg4OGIzR1ZvZGhTc0NFcnZu
            NWpGY3hCVzNBNEN1Y08zTDlBTXVibEUKLS0tIFR3aUtlMHpFdXRqSUJqRU5lY3k5
            NmRQaDdacmxZWjdWR3pTWlVMamtUcjQKRr0GnjCuQ6GhW676M0e1gvjQ1YUFhUEH
            yzIc+I2k2GddJE+QyK/jbE7CfQdq88Vn71C7R8M5Adk5M6QWAF0OkQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14taxy23wzym2r9jndzsq5h8dx2f5cj5vtusfet2ggjjepp8pkfdqf6mus0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5VDEydGZOZHdHRXNVaENK
            bW8rd0lMWHc5T0VwUlRFRklkeW0xdVdWRW0wCndDYlVtaE1DekUyWWNXblRkam9G
            QzQ3UmNGSHRqRnpUcEIrYTVsUm5raTQKLS0tIE96bi9NTW9jdTZRdmk2cFhzSHJJ
            NkJnVlN5bjN3V0V0RC92NGZiWEpSWmsK+HAMhQgSGaohuCYxWfLt+RDk9MTwx6iG
            CTzB41OB055GeY2niaHau6wywMOZuO+bygneA8hzs6uHwkvPFK36Mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T06:59:19Z"
    mac: ENC[AES256_GCM,data:7i7y4zO3Xx5JeKi65bR/Qsx1ZmHQPus15hQts70Zkr2j5D8S78QZ6NG0i7b4BX4rmqBkIvE2x5DKRmb/ug/1H0kX4vLYxNFgRXlYnlm1F3OtxPS08rHjxQHqJqXCnc8IbIaUFT8BXMVIBMpcNxD6ONjMrfO0ZwuaCraN42KmaGE=,iv:SFJpozAIN817n/HJOP9X80Bn8LWo38n6LyXB3dl2dRo=,tag:e/RaJQ5FEyYMqymDO0TNUA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
