apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: cert-manager
spec:
  podSelector: {}
  policyTypes:
    - Egress
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns-and-kubernetes-api
  namespace: cert-manager
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    - to:
        - ipBlock:
            cidr: 172.21.0.10/32
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    - to:
        - ipBlock:
            cidr: 172.21.0.1/32
      ports:
        - port: 443
          protocol: TCP
    - to:
        - ipBlock:
            cidr: 10.66.0.10/32
        - ipBlock:
            cidr: 10.66.0.11/32
        - ipBlock:
            cidr: 10.66.0.12/32
        - ipBlock:
            cidr: 10.66.0.254/32
      ports:
        - port: 6443
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-kubernetes-api-to-webhook
  namespace: cert-manager
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: webhook
      app.kubernetes.io/instance: cert-manager
      app.kubernetes.io/name: webhook
  policyTypes:
    - Ingress
  ingress:
    - from:
        - ipBlock:
            cidr: 10.66.0.10/32
        - ipBlock:
            cidr: 10.66.0.11/32
        - ipBlock:
            cidr: 10.66.0.12/32
        - ipBlock:
            cidr: 10.66.0.254/32
      ports:
        - port: 10250
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: etcdetcetc
spec:
  podSelector: {}
  policyTypes:
    - Egress
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-controller-egress
  namespace: etcdetcetc
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/name: etcdetcetc
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    - to:
        - ipBlock:
            cidr: 172.21.0.10/32
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    - to:
        - ipBlock:
            cidr: 172.21.0.1/32
      ports:
        - port: 443
          protocol: TCP
    - to:
        - ipBlock:
            cidr: 10.66.0.10/32
        - ipBlock:
            cidr: 10.66.0.11/32
        - ipBlock:
            cidr: 10.66.0.12/32
        - ipBlock:
            cidr: 10.66.0.254/32
      ports:
        - port: 6443
          protocol: TCP
    - to:
        - ipBlock:
            cidr: 10.66.0.10/32
        - ipBlock:
            cidr: 10.66.0.11/32
        - ipBlock:
            cidr: 10.66.0.12/32
      ports:
        - port: 2379
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: etcdetcetc-smoke
spec:
  podSelector: {}
  policyTypes:
    - Egress
    - Ingress
