apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: edge-au-east-control-plane-values
    files:
      - values.yaml=edge-au-east-control-plane-values.yaml
namespace: edge
resources:
  - ../../../../.kustomize-config
  - edge-au-east-control-plane.yaml
  - source.yaml
