#!/bin/sh
set -eu

ipaddr='10.0.4.1'
hostname='lab-router'

uci -q batch <<EOF
set dhcp.@dnsmasq[0].logdhcp='1'
set dhcp.@dnsmasq[0].enable_tftp='1'
set dhcp.@dnsmasq[0].tftp_root='/usr/share/tftp'

set dhcp.match_arch0=match
set dhcp.match_arch0.networkid='bios'
set dhcp.match_arch0.match='option:client-arch,0'

set dhcp.match_arch7=match
set dhcp.match_arch7.networkid='efi64'
set dhcp.match_arch7.match='option:client-arch,7'

set dhcp.match_arch9=match
set dhcp.match_arch9.networkid='efi64'
set dhcp.match_arch9.match='option:client-arch,9'

set dhcp.match_ipxe=match
set dhcp.match_ipxe.networkid='ipxe'
set dhcp.match_ipxe.match='77,"iPXE"'

set dhcp.boot_bios=boot
set dhcp.boot_bios.filename='undionly.kpxe'
set dhcp.boot_bios.serveraddress='$ipaddr'
set dhcp.boot_bios.servername='$hostname'
set dhcp.boot_bios.networkid='bios'

set dhcp.boot_efi=boot
set dhcp.boot_efi.filename='ipxe.efi'
set dhcp.boot_efi.serveraddress='$ipaddr'
set dhcp.boot_efi.servername='$hostname'
set dhcp.boot_efi.networkid='efi64'

set dhcp.boot_ipxe=boot
set dhcp.boot_ipxe.filename='http://lab-bootie.tailnet.hub.samcday.com/boot.ipxe?uuid=\${uuid}&mac=\${mac:hexhyp}&domain=\${domain}&hostname=\${hostname}&serial=\${serial}&arch=\${buildarch:uristring}'
set dhcp.boot_ipxe.serveraddress='$ipaddr'
set dhcp.boot_ipxe.servername='$hostname'
set dhcp.boot_ipxe.networkid='ipxe'
commit dhcp
EOF

service dnsmasq reload || true
