template:
  spec:
    containers:
      - name: admin-kubeconfig-generator
        image: {{ include "k8s-control-plane.kubectl-image" $ }}
        command:
          - bash
          - -uexo
          - pipefail
          - -c
          - |
            kubectl create secret generic admin-kubeconfig-external --from-file=value=<(KUBECONFIG=/kubeconfig-external kubectl config view --flatten --raw) --dry-run=client --output yaml \
              | kubectl apply -f-
            kubectl create secret generic admin-kubeconfig --from-file=value=<(KUBECONFIG=/kubeconfig kubectl config view --flatten --raw) --dry-run=client --output yaml \
              | kubectl apply -f-
            {{- range $user := $.Values.users }}
            {{- $userName := required "users[].name is required" $user.name }}
            {{- $certSecretName := printf "user-%s" $userName }}
            {{- range $export := $user.exportKubeconfigs }}
            kubectl create secret generic {{ required (printf "users[%s].exportKubeconfigs[].name is required" $userName) $export.name }} --namespace {{ required (printf "users[%s].exportKubeconfigs[].namespace is required" $userName) $export.namespace }} --from-file=value=<(KUBECONFIG={{ if $export.external }}/{{ $certSecretName }}-kubeconfig-external{{ else }}/{{ $certSecretName }}-kubeconfig{{ end }} kubectl config view --flatten --raw) --dry-run=client --output yaml \
              | kubectl apply -f-
            {{- end }}
            {{- end }}
        volumeMounts:
          - name: cert
            mountPath: /cert
          - name: kubeconfig
            mountPath: /kubeconfig
            subPath: kubeconfig
          - name: kubeconfig-external
            mountPath: /kubeconfig-external
            subPath: kubeconfig
          {{- range $user := $.Values.users }}
          {{- $userName := required "users[].name is required" $user.name }}
          {{- $certSecretName := printf "user-%s" $userName }}
          - name: {{ $certSecretName }}
            mountPath: /{{ $certSecretName }}
          - name: {{ $certSecretName }}-kubeconfig
            mountPath: /{{ $certSecretName }}-kubeconfig
            subPath: kubeconfig
          - name: {{ $certSecretName }}-kubeconfig-external
            mountPath: /{{ $certSecretName }}-kubeconfig-external
            subPath: kubeconfig
          {{- end }}
    serviceAccount: admin-kubeconfig-generator
    volumes:
      - name: cert
        secret:
          secretName: admin
      - name: kubeconfig
        configMap:
          name: kubeconfig
      - name: kubeconfig-external
        configMap:
          name: kubeconfig-external
      {{- range $user := $.Values.users }}
      {{- $userName := required "users[].name is required" $user.name }}
      {{- $certSecretName := printf "user-%s" $userName }}
      - name: {{ $certSecretName }}
        secret:
          secretName: {{ $certSecretName }}
      - name: {{ $certSecretName }}-kubeconfig
        configMap:
          name: {{ $certSecretName }}-kubeconfig
      - name: {{ $certSecretName }}-kubeconfig-external
        configMap:
          name: {{ $certSecretName }}-kubeconfig-external
      {{- end }}
    restartPolicy: OnFailure
ttlSecondsAfterFinished: 60
