---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: infra
  namespace: flux-system
spec:
  interval: 5m
  ref:
    branch: main
  secretRef:
    name: ssh-key
  timeout: 60s
  url: ssh://git@github.com:22/samcday/infra.git
