apiVersion: v1
kind: Secret
metadata:
    name: ignition-key
    namespace: bootie
stringData:
    age.agekey: ENC[AES256_GCM,data:2TQs2slCbloJ5CqhGWyrHWfWqd3KIl0EIW+0FIl5awq0lmnRdYvYB2nbk7YHBPXhOuPPdoWS+AjD5HZEMPgnMQgf3sMpRZ5fB4vCo3PdpIWkhISkMrFQEbWfIWuvEJ0UUCYuk0uwlTinHwLr2N0ucev2/KoFiTcMiBFjxWIeEx74TLgF/vUmagK8yV9WYcWtldyv8lzcFSMhv3CK0mer62WC4x0IxXr0qTx1tu0BkTdj5Mg3R8mIT/bSWxc=,iv:m/JmRUPcGrewgrrdBq3rbdq2KZH+MjpsFTryHdgHPCQ=,tag:wajp0l6f73NpGxsMJW0BiQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tu8l2llfk32g0c4mvklqazjkj977h9xwvx3ntwt2ucdert8sufgq2g8mgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZTV1TWpGRnNiVkJEelJa
            QklDNkNLdERabHhOSEl1Sm1hb0ZHeUdzQUM0CklUaDZwUEl3Q2w5c3d0SE95a29Y
            TTVEU01tK3pRa3ZqcWlHblZxSFNMaUkKLS0tIDJJRXNHdWVMVm1BREw1NTRUTnZ0
            Y2VxTHNMUWsyeTA3UWVaaWlmWTRQRUEKXgSOb06UoF6pBOrSdiyw7VUz7WnFZJgI
            em6FkRtA8n7ZQqgXCL1H22MSkqe5V6GItWT90Ar4/J+uUj5S6+bd6g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14taxy23wzym2r9jndzsq5h8dx2f5cj5vtusfet2ggjjepp8pkfdqf6mus0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0aW9BSys1MG1EZnVuYzho
            V05PS1RvbzArN28rby9zcWhlLzNZNzgxSHhVCmU2dzc2K3lvR2IxcHB0MFFNWWpW
            dGJ3UXFTWFlub0RBelZtYjdkdGE2MTQKLS0tIGdXYjlSUzQwMmdZYUhCSHhyVjU3
            WDhhbXJDOXMyc1Y4MVVGQ1pPbTZiKzAKzhj71bihn2txL4joKWdCH7/i6KidNoQj
            pK40qYqBxFwyUH2Clglc0ERNnQZeSULScC+gDvB4y5fi9n/9mNsHiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-28T04:26:57Z"
    mac: ENC[AES256_GCM,data:+TwuSpmkC8v48z97sfTFxtJsiaxw8l90IBCUqa7LZJ4aohlQL92RqQ4pnzxDiKqa60/4QfgbtQ/YIw1hxcvl+CDlwQDFfW8sCGHiv3G66e2LWIZR/SsOspCGAfs5ufiBizxQjNReQ8lZeinp4ExJ5LBegjxNkaz0JvlHwv7HWfM=,iv:rwd3pl7N82Mzzjm3Tio+odoHc+UOeJV7uXgQJ94PQAM=,tag:frLiqnt7ZxxhBMUt9qjQjQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
