apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bootie
rules:
- apiGroups: [""]
  resources: [nodes]
  verbs: [create, get, list, patch, update]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bootie
subjects:
  - kind: ServiceAccount
    name: bootie-generic
    namespace: bootie
roleRef:
  kind: ClusterRole
  name: bootie
  apiGroup: rbac.authorization.k8s.io
