apiVersion: v1
kind: Secret
metadata:
    name: rokkitpokkit-age-key
    namespace: cloud-cluster
stringData:
    age.agekey: ENC[AES256_GCM,data:qv0nZbEXH0LFb0vKjpSBkKcFi9vpC3xdADkWlg6MWKiJa2y/D60B8cDiS24LzkF1JX4fhZAobB8myg6lFFC1jJe3s6qJ/NivIoQ5kAJjGUwJ2vXIz/VY022Qg9Ms/nCx5M1clAmn2csqRu/AWf0Y+FR0A2x/nPjkqDnHh1Y21Q2XA6JeMpgdRGdPqPIMHWK/8bhoWirCVYyBj23HXg9xqpHFthKpd9B2UAMWM5PN2OasQwvSguOFvraSlPFu,iv:/ZaFoY0Q7XOAx51Zi7IKQ/Yxo/25osa+uJpI+QQtSJo=,tag:aaRM7RqOPKDQHKMqacGe2Q==,type:str]
sops:
    age:
        - recipient: age15v9ufl7p4vd2f67xsx5tstkmhzdrqgfj5408p9e3s7dyyc8mnacq44hkk9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjY0xSM1lQWmhnS3B0d04x
            WmpoZ0Mrc0Zrb2VHdmJaVllEbU5DUU1neGdvCmNNYVU2UDdkeS8rZStFM2M3SVQ4
            YmIxRFBlOUxCOFZNVTFwdjEyaHg5WjgKLS0tIFZXeFhUK0tsejFqdEN2U2VOU3li
            amhOOVZTdWY5aDhSOFFVRktLUVJJbEEKOyUUDCUSO1RLrR4+55gmDCYyJtOXLM0F
            Y00BxQ1YeqKuJOW5O4REpsNw+1o8tXQ7OaWxbJNQjxDAqqbHZXETDA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFwawprQXEkGl38Q7T0PNseL0vpoyr4TbATMkEaZJTWQ
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IEw2V0lpQSAyenhY
            VDJDQnh4UEYyaVRZNFR4M2ExZ2YwUWwxSExGSlFieFhkYkNUQ0FVClEzVDV3bmsr
            VURXNFN0c1h3TXozaktQR1pEbTFjK2kycUdtMDJpWFpsYm8KLS0tIDBTd2VTbEt0
            YURYM29vdGVMVHFvSGpZZHBjZ1dlaWEzZ0FFRmU3Y0hnSE0KBBAAWYkEKmO/E0NJ
            J0zYBSpOAKUCtb0E4rNF0OgXwhKxx2GRpdERZ5QKbYUrNwwXFVVoL5hgdAhidy8n
            IZtYbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-07T19:45:03Z"
    mac: ENC[AES256_GCM,data:k4XL2cO2l1yqDs7nnpFfqLNMfLT9DbW2rkzJzNyHDWmM9ZSq2vA7JxICfE27E/goP6C4y2JnJrmpgbaSWDz3YLV/154OxLkLXeAqqn5YNpc947HchPgQr63aLHTa+ronUQjVCyom8MtoZfF4plaVB7UILJaXhx47jizmJ68UUCo=,iv:i5+hZRbEJjHoalOH6g8RfH3DXwuzq6fjEicwhoP3GlA=,tag:INET4FHTaRwCbW94ZblYJQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
