apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: forgejo-runners
resources:
  - namespace.yaml
  - forgejo-runner-keda-auth.yaml
  - forgejo-runner-config.yaml
  - forgejo-runner-amd64.yaml
  - forgejo-runner-arm64.yaml
