apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  - name: butane
    files:
      - base.yaml=base.bu
      - install.yaml=install.bu
      - tpm.yaml=tpm.bu
      - var.yaml=var.bu
      - worker.yaml=worker.bu
    options:
      disableNameSuffixHash: true
