variant: fcos
version: 1.5.0
passwd:
    users:
        - name: sam
          groups:
            - adm
            - wheel
            - sudo
            - systemd-journal
          ssh_authorized_keys:
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFwawprQXEkGl38Q7T0PNseL0vpoyr4TbATMkEaZJTWQ
storage:
    files:
        - path: /etc/rancher/k3s/agent.token
          overwrite: true
          mode: 384
          contents:
            # cryptme
            inline: ENC[AES256_GCM,data:wrsMxxT/J8HoZiOPh+lVyeWZhjz3TEl8E3AJsIoEvgf7ZbjaG3w+g3XfKvFfV+XBr6xhHWP3MPdXd9foA9FuYPI=,iv:phS7C8FCBJ/9T6FO6JpohHdsAdNWVsWH4RQoYAGx+os=,tag:xQXH58nwjo6ezn0y1oZqWg==,type:str]
        - path: /etc/rancher/k3s/registries.yaml
          contents:
            inline: |
                mirrors:
                  "*":
          overwrite: true
        - path: /etc/zincati/config.d/90-disable.toml
          contents:
            inline: |
                [updates]
                enabled = false
          overwrite: true
        - path: /usr/local/bin/k3s
          overwrite: true
          contents:
            source: http://10.0.1.1/static/k3s
          mode: 493
        - path: /usr/local/bin/install-k3s
          overwrite: true
          contents:
            source: http://10.0.1.1/static/install-k3s
          mode: 493
        - path: /var/lib/rancher/k3s/server/manifests/traefik.yaml.skip
          contents:
            inline: ""
          overwrite: true
systemd:
    units:
        - name: install-k3s.service
          enabled: true
          contents: |
            [Unit]
            Description=Run k3s install script
            ConditionPathExists=!/etc/%N.stamp
            After=network-online.target
            Wants=network-online.target

            [Service]
            Type=oneshot
            RemainAfterExit=yes
            Environment=INSTALL_K3S_SKIP_DOWNLOAD=true
            ExecStart=/usr/local/bin/install-k3s
            ExecStart=/bin/touch /etc/%N.stamp

            [Install]
            WantedBy=multi-user.target
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tu8l2llfk32g0c4mvklqazjkj977h9xwvx3ntwt2ucdert8sufgq2g8mgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByb0oxUkZlR2g5M24vaDY3
            MFNJUEtYMnlqR1Z2cmtQYUNHMmlraUFLZ0N3CktwcjF0c1NQSkJIS2U5QXRZdFlS
            MGNyVU5jQUN5Z0R5R0RDdTcrcUpOTjQKLS0tIC9iTXZzaHB1RjNJRHFJb2dwNGFP
            Y2NkVHFQb1VGbG9Wdk1lZzQ3TXU3cXcKUc6GeE8mTFPjX7N+CPamqRVyVtirB/kq
            Lh2C9PQ0uMuT501G55LH6vkOx7gupWrMwqdoz/gMOWs95oZRm1Sezw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14taxy23wzym2r9jndzsq5h8dx2f5cj5vtusfet2ggjjepp8pkfdqf6mus0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxdzJzbWR2V0VBbExYYU0v
            TUNhTzdTaEtITDlFK3FlOThBeEcwYS9WRGdzCjFCRkNxTFhteHRaYUtpVUg5RWd1
            WWNVcmY0bmtuSlRyOTZWVlFlbUdwY0kKLS0tIEtUbzZYTTYzRlpXdzJzUjl6VGsr
            bzk3U2hOdVcyb0s0TkNmdjBaWlNTZFEKFHqxXjRa3EmZJCLAQxH4BQxVWW2q6SXV
            mo3DjP/VOoZVms/tw4bXdxHf0Jz9NJ3B+sOJ9Qzpccqr9j1NPaH7aA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-04T06:42:55Z"
    mac: ENC[AES256_GCM,data:3Wckf+VPQuSOvKxePa0UasKydDo04Vhs7/tcgIVeehcJB4nF7fTJyY+Xq6mBqtrPJVOVBM3Uks1hdKMneU7fwIvY5PIff8E/2BBwK9nIA1+O/LyrsmXaBl4gpW/A26OS8Lbc9VKqyqih9NAxsFQ6iFnO2/9okyiS2uDqynaCLMg=,iv:yihnGaHAgLfnl9OZoJEPK5PRhTha/Cnja7AMEW4lHjI=,tag:JWYAWmafWPz12yiAiaxlmQ==,type:str]
    pgp: []
    encrypted_comment_regex: cryptme
    version: 3.9.4
