variant: fcos
version: 1.5.0
passwd:
    users:
        - name: sam
          groups:
            - adm
            - wheel
            - sudo
            - systemd-journal
          ssh_authorized_keys:
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFwawprQXEkGl38Q7T0PNseL0vpoyr4TbATMkEaZJTWQ
storage:
    files:
        - path: /etc/rancher/k3s/agent.token
          overwrite: true
          mode: 384
          contents:
            # cryptme
            inline: ENC[AES256_GCM,data:ehcnvaWdDjwGnBlkOEp0JVO4AW2MmrBD/M/+qyLEFMhQbhL5L17Z0w2op9qaUUeb+M6IWqOGjp2I0mnktKrUpJk=,iv:8mdUAofyADJACawYFqrIPxSycUCkZPb3gR3h9fWKAoA=,tag:u31upwjCC9pve6Jg96krMA==,type:str]
        - path: /etc/rancher/k3s/registries.yaml
          contents:
            inline: |
                mirrors:
                  "*":
          overwrite: true
        - path: /etc/zincati/config.d/90-disable.toml
          contents:
            inline: |
                [updates]
                enabled = false
          overwrite: true
        - path: /usr/local/bin/k3s
          overwrite: true
          contents:
            source: http://10.0.1.1/static/k3s
          mode: 493
        - path: /usr/local/bin/install-k3s
          overwrite: true
          contents:
            source: http://10.0.1.1/static/install-k3s
          mode: 493
        - path: /var/lib/rancher/k3s/server/manifests/traefik.yaml.skip
          contents:
            inline: ""
          overwrite: true
systemd:
    units:
        - name: install-k3s.service
          enabled: true
          contents: |
            [Unit]
            Description=Run k3s install script
            ConditionPathExists=!/etc/%N.stamp

            [Service]
            Type=oneshot
            RemainAfterExit=yes
            Environment=INSTALL_K3S_SKIP_DOWNLOAD=true
            ExecStart=/usr/local/bin/install-k3s
            ExecStart=/bin/touch /etc/%N.stamp

            [Install]
            WantedBy=multi-user.target
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14taxy23wzym2r9jndzsq5h8dx2f5cj5vtusfet2ggjjepp8pkfdqf6mus0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJUzFJMDQwTkRvaFZNY255
            UGdXWXRZdjU1QmExQUFvSFhVcW5Dby84blNzCjZ1dWZGRVdlaTZpTlpmNUxYZGE2
            TGFEVWlFSXlKb2ZvbDFqUmNvZ05SNlUKLS0tIDdqbGp4a0NRYS9CMjdnNldtai8v
            WjA0WmFvL2hNZW94Nm53RjZ3RnhMbzgKhzbaplcswsxf8ZxulQ3+TE+evRF8lz0c
            gE8rv0g+pMZmPULxGYvCUK7hshx3GIea3Ir6WmScm6/zDnHVxqRaUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-30T07:27:11Z"
    mac: ENC[AES256_GCM,data:m+CLYFoha1pdzrOpxSVLnleI9MLbEaSEwiHS/UQ1ItAnzioaQWmaKSdGyT62qosChhh3uyPQqocSNs30yitfOaHMmpxdgOzZ2uDjtjxUi86+blZhgroiPjBIecI5dqYfIdzXSV5Wuo25X78iPedOJRNIFjuQyXWtdu5AaVhsGjM=,iv:vXIGFaP4jDlE1G61uhB5Ril/K3Pg+xr6ft5smDo0UJM=,tag:gBv3U/Ab65zV48H2T0pcCg==,type:str]
    pgp: []
    encrypted_comment_regex: cryptme
    version: 3.9.4
