apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  - name: butane
    files:
      - base.yaml
      - control-plane.yaml
      - etcd.yaml
      - install.yaml
      - kubevirt.yaml
      - worker.yaml
    options:
      disableNameSuffixHash: true
