apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: helm-repos
  namespace: flux-system
spec:
  chart:
    spec:
      chart: charts/resources
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: infra
        namespace: flux-system
  driftDetection:
    mode: enabled
  interval: 1h
  values:
    _:
      apiVersion: source.toolkit.fluxcd.io/v1
      kind: HelmRepository
      spec:
        interval: 1h
    autoscaler:
      spec:
        url: https://kubernetes.github.io/autoscaler
    cilium:
      spec:
        url: https://helm.cilium.io/
    cloudnative-pg:
      spec:
        url: https://cloudnative-pg.github.io/charts
    community-tooling-charts:
      spec:
        url: https://community-tooling.github.io/charts/
    coredns:
      spec:
        url: https://coredns.github.io/helm
    cowboysysop:
      spec:
        url: https://cowboysysop.github.io/charts/
    descheduler:
      spec:
        url: https://kubernetes-sigs.github.io/descheduler/
    dex:
      spec:
        url: https://charts.dexidp.io
    external-dns:
      spec:
        url: https://kubernetes-sigs.github.io/external-dns/
    fluxcd-community:
      spec:
        url: https://fluxcd-community.github.io/helm-charts
    grafana:
      spec:
        url: https://grafana.github.io/helm-charts
    hcloud:
      spec:
        url: https://charts.hetzner.cloud
    ingress-nginx:
      spec:
        url: https://kubernetes.github.io/ingress-nginx
    jetstack:
      spec:
        url: https://charts.jetstack.io
    keda:
      spec:
        url: https://kedacore.github.io/charts
    metrics-server:
      spec:
        url: https://kubernetes-sigs.github.io/metrics-server/
    openebs:
      spec:
        url: https://openebs.github.io/openebs
    piraeus:
      spec:
        url: https://piraeus.io/helm-charts/
    prometheus-community:
      spec:
        url: https://prometheus-community.github.io/helm-charts
    rook-release:
      spec:
        url: https://charts.rook.io/release
    samcday-tailscale-node-controller:
      spec:
        url: https://samcday.github.io/tailscale-node-controller
    stakater:
      spec:
        url: https://stakater.github.io/stakater-charts
    tailscale:
      spec:
        url: https://pkgs.tailscale.com/helmcharts
    tofu-controller:
      spec:
        url: https://flux-iac.github.io/tofu-controller
    wasmcloud:
      spec:
        type: oci
        url: oci://ghcr.io/wasmcloud/charts
