apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: helm-repos
  namespace: flux-system
spec:
  chart:
    spec:
      chart: charts/resources
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: infra
  driftDetection:
    mode: enabled
  interval: 1h
  values:
    _:
      apiVersion: source.toolkit.fluxcd.io/v1
      kind: HelmRepository
      spec:
        interval: 1h
    cloudnative-pg:
      spec:
        url: https://cloudnative-pg.github.io/charts
    community-tooling-charts:
      spec:
        url: https://community-tooling.github.io/charts/
    external-dns:
      spec:
        url: https://kubernetes-sigs.github.io/external-dns/
    ingress-nginx:
      spec:
        url: https://kubernetes.github.io/ingress-nginx
    jetstack:
      spec:
        url: https://charts.jetstack.io
    piraeus:
      spec:
        url: https://piraeus.io/helm-charts/
    prometheus-community:
      spec:
        url: https://prometheus-community.github.io/helm-charts
    rook-release:
      spec:
        url: https://charts.rook.io/release
    tailscale:
      spec:
        url: https://pkgs.tailscale.com/helmcharts
    tofu-controller:
      spec:
        url: https://flux-iac.github.io/tofu-controller
