apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - helm-repos.yaml
  - image-policies.yaml
  - image-repositories.yaml
  - image-update-automation.yaml
  - kustomizations.yaml
  - namespaces.yaml
  - tofu-controller.yaml
  - webhook.yaml
  - webhook-token.yaml
