apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kustomizations
  namespace: flux-system
spec:
  chart:
    spec:
      chart: charts/resources
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: infra
  driftDetection:
    mode: enabled
  interval: 1h
  values:
    _:
      apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      spec:
        decryption:
          provider: sops
          secretRef:
            name: age-key
        interval: 1h
        prune: true
        sourceRef:
          kind: GitRepository
          name: infra
          namespace: flux-system
        timeout: 5m
    bootie:
      spec:
        path: hub/cluster/bootie
    butane:
      spec:
        path: hub/butane
        targetNamespace: bootie
    butane-common:
      spec:
        path: common/butane
        targetNamespace: bootie
    cert-manager:
      spec:
        path: hub/cluster/cert-manager
    cloud-cluster:
      spec:
        path: hub/cluster/cloud-cluster
    cnpg-system:
      spec:
        path: hub/cluster/cnpg-system
    external-dns:
      spec:
        path: hub/cluster/external-dns
    global:
      spec:
        path: hub/cluster/global
    headscale:
      spec:
        path: hub/cluster/headscale
    ilumbaclusta:
      spec:
        path: hub/cluster/ilumbaclusta
    ilumbaclusta-butane:
      spec:
        path: ilumbaclusta/butane
        targetNamespace: ilumbaclusta
    ilumbaclusta-butane-common:
      spec:
        path: common/butane
        targetNamespace: ilumbaclusta
    ingress-nginx:
      spec:
        path: hub/cluster/ingress-nginx
    kube-system:
      spec:
        path: hub/cluster/kube-system
    monitoring:
      spec:
        dependsOn: [name: prometheus-operator]
        path: hub/cluster/monitoring
    openebs:
      spec:
        path: hub/cluster/openebs
    prometheus-operator:
      spec:
        path: hub/cluster/prometheus-operator
    rook-ceph:
      spec:
        path: hub/cluster/rook-ceph
    simonet:
      spec:
        path: hub/cluster/simonet
    tailscale:
      spec:
        path: hub/cluster/tailscale
