apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:dZ/jNnPzdZD0VmL9jbZmhJjPUp6/lUXk1YBst7xqkJEIr5JZLRRc20LW3QLtw8FJZdP+klYhv9PCZD51a6/zuA==,iv:UwMa1QPOksRUoN0SmqW484RhqF8bpsjB3Lv2ZFqh0AU=,tag:VcrsjzSLVwwqmApGe1xKdw==,type:str]
sops:
    age:
        - recipient: age15v9ufl7p4vd2f67xsx5tstkmhzdrqgfj5408p9e3s7dyyc8mnacq44hkk9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAraHFydlNRdTVTaHVoTnQ5
            QzZLb2x1aW5XaGtrV3Zac21UTE1qZWtYS3lrClN4UVAvc1pwZmtZNEErS21Jbkk2
            WEV0dkF2Q3piWVd4NW9tdnhDVUp6VTgKLS0tIE5nMFl3SFhMdGRzbUprcERHdXRk
            aGRXSlVITXlCVXpQVkNmRmVLQUd2SFUKFik0utXSPPOWfZrj9X4OezzTXSrrk1AQ
            V9++1L5pzl92qgLmX7sZK5CttcPeYMt/IAWgFdk3ZeyXS0oo0sV/dQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFwawprQXEkGl38Q7T0PNseL0vpoyr4TbATMkEaZJTWQ
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IEw2V0lpQSB2Uko4
            L1QyZHhlWnhaNlVLSUFWQkVGbCttRkw4MzcxNDAvSE5ScWlsUlI4CmV5ODR0VFZq
            TVpuamgwMEE3YkVkblFYeHl0L2xCc2FDLzExamk1UGIvaW8KLS0tIG9DT0kxbDJj
            M25JSWRyRTdQVkR1S2RxWlRzalIrRjdjV0JsaDQ3SG9OenMKgHd64iuYb6uOhaCu
            aP0an5axVm0J3eqZWxPwHmE6BFgZfpV/QLDKYagI3+vz6VxSyuyUvvLEpKIbd2JK
            LV3B9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-07T19:27:04Z"
    mac: ENC[AES256_GCM,data:tVjK845hUjGneLhi1aIWbih3qvgwfIeYpFYs+amT5wE/P6rm5x7LDZG4o5KjeXqnqAIXM79+TEm5/At/pM1U/f3sf3QzczioPNzF1/WhLYpGgVR5pePAY3vI935T7PuN8TJ9Zdof1porxjfYbdORIwKysmZxlkB6ZvcByj78jgs=,iv:o64qPR+KhbiMIpPgAFD7KisPy5BG+OorTVQWj3X7jBM=,tag:eaizo/kVkyyj7sL0XmbAEA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
