creation_rules:
  # encrypt hub/cluster secrets to the hub age and Sam SSH recovery keys
  - age: >-
      age15v9ufl7p4vd2f67xsx5tstkmhzdrqgfj5408p9e3s7dyyc8mnacq44hkk9,
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFwawprQXEkGl38Q7T0PNseL0vpoyr4TbATMkEaZJTWQ
    encrypted_regex: ^(data|stringData)$
    path_regex: hub/cluster

  # encrypt Butane configs to the hub age and Sam SSH recovery keys
  - age: >-
      age15v9ufl7p4vd2f67xsx5tstkmhzdrqgfj5408p9e3s7dyyc8mnacq44hkk9,
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFwawprQXEkGl38Q7T0PNseL0vpoyr4TbATMkEaZJTWQ
    encrypted_comment_regex: "cryptme"
    path_regex: .*/butane/.*\.yaml$

  # encrypt hub k8s PKI artifacts with same key as hub/pki/etcd
  - age: age14taxy23wzym2r9jndzsq5h8dx2f5cj5vtusfet2ggjjepp8pkfdqf6mus0
    path_regex: hub/pki/k8s/.*\.enc$

  # encrypt everything else against Sam's personal key
  - age: age14taxy23wzym2r9jndzsq5h8dx2f5cj5vtusfet2ggjjepp8pkfdqf6mus0
