creation_rules:
  # encrypt files in hub/cluster to the hub age key
  - age: >-
      age1tu8l2llfk32g0c4mvklqazjkj977h9xwvx3ntwt2ucdert8sufgq2g8mgs,
      age14taxy23wzym2r9jndzsq5h8dx2f5cj5vtusfet2ggjjepp8pkfdqf6mus0
    encrypted_regex: ^(data|stringData)$
    path_regex: hub/cluster

  # encrypt hub Butane configs to the hub age key
  - age: >-
      age1tu8l2llfk32g0c4mvklqazjkj977h9xwvx3ntwt2ucdert8sufgq2g8mgs,
      age14taxy23wzym2r9jndzsq5h8dx2f5cj5vtusfet2ggjjepp8pkfdqf6mus0
    encrypted_comment_regex: "cryptme"
    path_regex: hub/butane/.*\.yaml$

  # encrypt ilumbaclusta Butane configs to the hub age key
  - age: >-
      age1tu8l2llfk32g0c4mvklqazjkj977h9xwvx3ntwt2ucdert8sufgq2g8mgs,
      age14taxy23wzym2r9jndzsq5h8dx2f5cj5vtusfet2ggjjepp8pkfdqf6mus0
    encrypted_comment_regex: "cryptme"
    path_regex: ilumbaclusta/butane/.*\.yaml$

  # encrypt everything else against Sam's personal key
  - age: age14taxy23wzym2r9jndzsq5h8dx2f5cj5vtusfet2ggjjepp8pkfdqf6mus0
