---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: internal
  namespace: ingress-nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      version: 4.13.0
  interval: 1h
  values:
    # https://github.com/kubernetes/ingress-nginx/blob/helm-chart-4.13.0/charts/ingress-nginx/values.yaml
    controller: 
      allowSnippetAnnotations: true
      metrics:
        enabled: true
      replicaCount: 3
      service:
        externalTrafficPolicy: Local
        loadBalancerClass: io.cilium/bgp-control-plane
      terminationGracePeriodSeconds: 5
