apiServer:
  service:
    spec:
      type: ClusterIP
bootstrapTokens:
  - extraGroups: [system:bootstrappers:kubeadm:default-node-token]
    # token ID+secret is set from HelmRelease spec.valuesFrom
clusterCIDRs: [172.22.0.0/16]
clusterDNS: [172.21.0.10]
clusterName: fedora-mobility-ci
etcd:
  certIssuer:
    name: etcd
    kind: ClusterIssuer
  endpoints:
    - https://hub-az1-cp1.hub.internal:2379
    - https://hub-az1-cp2.hub.internal:2379
    - https://hub-az1-cp3.hub.internal:2379
# see the ts-apiserver resources
# externalHostname: fedora-mobility-ci-apiserver.tailnet.hub.samcday.com
externalIP: 100.64.0.21
parentClusterDomain: cluster.hub.internal
scheduler:
  config:
    profiles:
      - pluginConfig:
          - name: NodeResourcesFit
            args:
              scoringStrategy:
                type: MostAllocated
                resources:
                  - name: cpu
                    weight: 1
                  - name: memory
                    weight: 100
  deployment:
    spec:
      replicas: 1
      strategy:
        type: Recreate
      template:
        spec:
          containers:
            - name: kube-scheduler
              # command:
              #   - -v=6
serviceCIDRs: [172.21.0.0/16]
serviceIP: 172.21.0.1
