apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: fedora-mobility-ci-infrastructure
  namespace: fedora-mobility-ci
spec:
  interval: 1h
  ref:
    branch: main
  url: https://forge.fedoraproject.org/mobility/ci-infrastructure.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fedora-mobility-ci-infrastructure
  namespace: fedora-mobility-ci
spec:
  decryption:
    provider: sops
    secretRef:
      name: age-key
  interval: 1h
  kubeConfig:
    secretRef:
      name: admin-kubeconfig
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: fedora-mobility-ci-infrastructure
  targetNamespace: default
  timeout: 5m
