apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: control-plane-values
    files:
      - values.yaml=control-plane-values.yaml
namespace: fedora-mobility-ci
resources:
  - ../../../.kustomize-config
  - age-key.yaml
  - cluster-autoscaler.yaml
  - control-plane.yaml
  - csi-driver.yaml
  # - descheduler.yaml
  - external-dns.yaml
  - hccm.yaml
  - hcloud-token.yaml
  - infra-config.yaml
  - kustomizations.yaml
  - node-bootstrap-token.yaml
  - tofu.yaml
  - ts-apiserver.yaml
  - vpas.yaml
