apiVersion: batch/v1
kind: Job
metadata:
  name: join-${NODE_NAME}
  labels:
    app.kubernetes.io/component: node-joiner
    bl.samcday.com/node: ${NODE_NAME}
spec:
  backoffLimit: 30
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        app.kubernetes.io/component: node-joiner
        bl.samcday.com/node: ${NODE_NAME}
    spec:
      restartPolicy: OnFailure
      volumes:
        - name: edge-kubeconfig
          secret:
            secretName: admin-kubeconfig
            defaultMode: 0400
            items:
              - key: value
                path: kubeconfig
      containers:
        - name: join
          image: ghcr.io/samcday/infra-node-joiner:2026042401 # {"$imagepolicy": "flux-system:node-joiner"}
          env:
            - name: NODE_NAME
              value: "${NODE_NAME}"
            - name: NODE_IP
              value: "${NODE_IP}"
            - name: HEADSCALE_URL
              value: https://headscale.tail22d0a0.ts.net
            - name: APISERVER_URL
              value: edge-apiserver.tailnet.hub.samcday.com:6443
            - name: TS_AUTH_KEY
              valueFrom:
                secretKeyRef:
                  name: node-ts-auth
                  key: key
            - name: BOOTSTRAP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bl-controllers-config
                  key: token
            - name: CA_HASH
              valueFrom:
                configMapKeyRef:
                  name: ca-hash
                  key: hash
          volumeMounts:
            - name: edge-kubeconfig
              mountPath: /etc/edge-kubeconfig
              readOnly: true
