apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: edge
resources:
  - rbac.yaml
  - deployment.yaml
configMapGenerator:
  - name: node-joiner-hook
    files:
      - hook.sh
      - job-template.yaml
