---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fabric-observer-readyz
rules:
  - nonResourceURLs:
      - /readyz
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fabric-observer-kube-vip-lease
  namespace: kube-system
rules:
  - apiGroups:
      - coordination.k8s.io
    resourceNames:
      - plndr-cp-lock
    resources:
      - leases
    verbs:
      - get
