PermitRootLogin prohibit-password
PasswordAuthentication no
KbdInteractiveAuthentication no
AllowAgentForwarding no
AllowTcpForwarding no
DisableForwarding yes
GatewayPorts no
PermitTunnel no
X11Forwarding no
