custom_build(
    'localhost:5001/etcdetcetc',
    'CC=gcc cargo build --target x86_64-unknown-linux-musl && ' +
    'tar cf /tmp/etcdetcetc-layer.tar -C target/x86_64-unknown-linux-musl/debug etcdetcetc && ' +
    'crane append -b alpine -f /tmp/etcdetcetc-layer.tar -t $EXPECTED_REF --insecure && ' +
    'crane mutate $EXPECTED_REF --entrypoint /etcdetcetc --insecure',
    deps=['src/', 'Cargo.toml', 'Cargo.lock'],
    skips_local_docker=True,
)

k8s_yaml(local('cargo run -p etcdetcetc -- crds 2>/dev/null'))
k8s_yaml('dev/deploy.yaml')

k8s_resource('etcdetcetc', objects=[
    'etcdetcetc:serviceaccount',
    'etcdetcetc:clusterrole',
    'etcdetcetc:clusterrolebinding',
    'etcdclusters.etcdetcetc.samcday.com:customresourcedefinition',
    'etcdtenants.etcdetcetc.samcday.com:customresourcedefinition',
])
