apiVersion: v1
kind: Secret
metadata:
    name: pagerduty
    namespace: monitoring
stringData:
    integration-key: ENC[AES256_GCM,data:/fqKt663h2aaFuHh3Jkz52Z+1kvJHcplqiH8MhtJ7SU=,iv:XrDTZb5bx/mXzjLnuYX+4tJyQEH36P3UbhqPL9Hg/rM=,tag:Q6kGGDU5shHOHn++Skv7Ww==,type:str]
sops:
    age:
        - recipient: age1tu8l2llfk32g0c4mvklqazjkj977h9xwvx3ntwt2ucdert8sufgq2g8mgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxK0tRZ0dWcHREWE1MZlNH
            QklBQllpU0lrR01BblRxdXNDMDh6Y1lvalI4CmxpUjZrdGdaSnorV1lEd3J3aFJr
            RXltblBvNHhvczFHME95cGc4eE1tUjgKLS0tIEhGLzg2cFFJTkZ0NUhlNnNRVGtI
            cVRzOGFTaU00d2lCRExQYklDTkprdUUKQrtk+McNhVeEN9k/97douYcNt/mmr501
            bkiYWb5zW4F9RcF3umynkvZLWCeMyDNeiCorq1f2bTeALuiw2JlbwQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14taxy23wzym2r9jndzsq5h8dx2f5cj5vtusfet2ggjjepp8pkfdqf6mus0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTXlZaU9qZytVK0Rha2c3
            am1CUEI0dWc4N3VkUDk1YjFjaXFVbkFEMGlzClptcEsxNUV0djRwQ3hCMENrSDBP
            d2V3OElWS0kyRWREeHBMNmJzVWxtbG8KLS0tIDc1RGt5L2VpZDJMVTRleWxOaHlr
            NWJKeS9LNjFYVFRldHdkcVNuY2l4dVUK07lTypvZVoie0gVzsl4k4h02IJXuYfEn
            gadCKqgFnXlwqQIWvK1kiAQwsRjAHwpQrxKESEfHyVZZ+9HREuUZhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-17T14:59:14Z"
    mac: ENC[AES256_GCM,data:CykvL10X4+jl7bDc9aesszAoUJMB1bJeIlFLoFQ+zhfczplS6KWsKRBAbOEH8BJCeWpV+53IGqzn6BY7y9VebZeVZkQ3y3CbLKOXS6IdNPUeEbopOV3yRg/3g6zU17czIx0auUg9+o6GzgkV3zpuEnnsJJnBsY6uFyNuSI3a5p4=,iv:Rh+GKHVeZ0y1J5fvgOuohLTtA9UOEJBMhkYnsYRS4pc=,tag:kuK4De0n70iGC1HkxDjfHg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
