apiVersion: v1
kind: Secret
metadata:
    name: pagerduty
    namespace: monitoring
stringData:
    integration-key: ENC[AES256_GCM,data:yKWD+jZGswMcKZSzpUg8sFcqUEvVxsgxS/J4oMZX+D0=,iv:cgj1nOMEjZwc0AOIxOhuzCCbLQs+lBdy02lbBmOxrx0=,tag:BPgXU/Tlrsr6NGqftxz3wg==,type:str]
sops:
    age:
        - recipient: age15v9ufl7p4vd2f67xsx5tstkmhzdrqgfj5408p9e3s7dyyc8mnacq44hkk9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZk9WcjZpVWV5T0pzUksr
            Rlh3dXZHYVgxSVdtYjYzSTRZZU5pWVo5Z0FnCmpWaTdaQWU1MjQ1UExHUjVORVRt
            cklqR1V5TVoyaHl5SFVqQXBFQkFIZzAKLS0tIDJlZXY5MGg0a2ovR2t6czBWcWN6
            Szk3c0I3SmVHUW9uYXRwaUE1OVpWRkkKcwlJzM1lw+3YMBAaCLk6MUTmvd5jH0Qp
            DXKsEiJVS5WI6fEt+8im4xoNAEJvm53mTZ/LYAHEKiCPcx8dqRVcEw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFwawprQXEkGl38Q7T0PNseL0vpoyr4TbATMkEaZJTWQ
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IEw2V0lpQSBySVFt
            d2tIK3FLK2sxa0VUdytkcnRrU2ZWT2VVN2RtTUJrVUtHYXhpT0VvCjhOSFlqQjJN
            T3pWU04zRHZHUncyZlZnK3VhTkdkYWVQdS9PQ3V3a2IyTFkKLS0tIC9qaWtpcHcr
            V3kxODJXUGVUOXdWd2xLMWxkTUhmSU93ZDREZ3ArWWd1SU0KMeP7ibzRAk4bEAEx
            lDZHGWemS6ZrsjfANJQdeiOTGFsBRgfAhrDefWKANVH3df6RR4NWGZQWG39XcXgh
            kI9FsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-07T19:42:02Z"
    mac: ENC[AES256_GCM,data:gxzXtkMYIbpfkB/YSXZlncPg3gRa3jkX+Zt6sgHJL+BIX57tido0qA3svzsA+hQk46NmplGFAikfTSHPElvSILS8jBSMgl0oC+ziYZ8mHbqvp2SUisKevXapzBg7P9xcAEfnFHBCqgFK6gZOmX7zR292W4bvTkzuFTYxkD3DCBU=,iv:fdSYVlG6luVCkiQ9nmD+fJ+Zf9bdHQ2/nh/RXWeRiII=,tag:H8WVnE966rHDmHOS8+CJBw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
