apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: etcd-ca
spec:
  commonName: etcd-ca
  isCA: true
  issuerRef:
    kind: ClusterIssuer
    name: selfsigned
  privateKey:
    algorithm: ECDSA
  secretName: etcd-ca
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: etcd
spec:
  ca:
    secretName: etcd-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: etcd-peer
spec:
  commonName: etcd
  dnsNames:
    - etcd
    - etcd.etcd.svc
    - etcd.etcd.svc.cluster.local
    - '*.etcd.etcd.svc'
    - '*.etcd.etcd.svc.cluster.local'
  issuerRef:
    kind: Issuer
    name: etcd
  privateKey:
    algorithm: ECDSA
  secretName: etcd-peer
  usages:
    - digital signature
    - key encipherment
    - client auth
    - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: etcd-root
spec:
  commonName: root
  issuerRef:
    kind: Issuer
    name: etcd
  privateKey:
    algorithm: ECDSA
  secretName: etcd-root
  usages:
    - digital signature
    - key encipherment
    - client auth
