---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: memos
  namespace: paste
spec:
  chart:
    spec:
      chart: generic
      sourceRef:
        kind: HelmRepository
        name: community-tooling-charts
        namespace: flux-system
      version: 8.1.1
  interval: 1h
  values:
    # https://github.com/community-tooling/charts/blob/main/charts/generic/values.yaml
    deploymentStrategy:
      type: Recreate
    env:
      MEMOS_DATA: /var/opt/memos
      MEMOS_INSTANCE_URL: https://paste.samcday.com
      MEMOS_PORT: "5230"
    image:
      repository: ghcr.io/usememos/memos
      tag: latest
    ingress:
      enabled: false
    persistence:
      accessMode: ReadWriteOnce
      enabled: true
      mountPath: /var/opt/memos
      storage: 100Gi
      storageClassName: ceph-block
    ports:
      - name: http
        containerPort: 5230
    service:
      ports:
        - targetPort: http
          protocol: TCP
          name: http
          port: 80

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: paste-public
  namespace: paste
  annotations:
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  hostnames:
    - paste.samcday.com
  parentRefs:
    - name: public
      namespace: ingress-nginx
  rules:
    - matches:
        - method: GET
          path:
            type: PathPrefix
            value: /
        - method: HEAD
          path:
            type: PathPrefix
            value: /
        - method: OPTIONS
          path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: memos-generic
          port: 80
    - matches:
        - method: POST
          path:
            type: Exact
            value: /api/v1/auth/status
      backendRefs:
        - name: memos-generic
          port: 80
