{{- if and $.Values.scheduler.enabled $.Values.scheduler.vpa.enabled -}}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: scheduler
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kube-scheduler
  updatePolicy:
    updateMode: Auto
{{- end -}}
