tenant:
  name: ""
  namespace: ""

namespace:
  create: true
  labels: {}
  annotations: {}

source:
  name: ""
  interval: 5m
  ref:
    branch: main
  url: ""
  ignore: ""
  suspend: false

kustomization:
  name: ""
  interval: 5m
  path: ""
  prune: true
  suspend: false
  targetNamespace: ""
  timeout: 2m

sops:
  enabled: false
  secretName: ""
  ageKey: ""

parent:
  releaseName: ""
  interval: 1h
  chart: charts/managed-cluster-tenant
  kubeConfigSecretName: admin-kubeconfig
  storageNamespace: flux-system
  createNamespace: true
  driftDetection:
    mode: enabled
  sourceRef:
    kind: GitRepository
    name: infra
    namespace: flux-system
  dependsOn:
    - name: flux

valuesFrom: []
