apiVersion: v1
kind: Secret
metadata:
    name: gateway-credentials
    namespace: llm-gateway
type: Opaque
stringData:
    CLIPROXY_API_KEY: ENC[AES256_GCM,data:ZcBvojpribEIOj8DXZvBGZknKd0wJ37Fz4x4x0p0WuFoIp/lFqPfyk8X+wxu2vN0ShrIeT2BwwEoOUicchueyw==,iv:Q3d3T0xXySykIIZnDtr/xsZjSQ46IZSDdKmDjFomFE0=,tag:XQXrTlrsmOLya/cQG/fZtg==,type:str]
    BIFROST_ADMIN_PASSWORD: ENC[AES256_GCM,data:dcwhfjHsrJmjwA9z+/eskzR7Q2ICcZHypQ4g/hwC97thrzRyig4IBH11MaGP+KpYlsKxheXYn9EximXUh/7XpRoVIj0=,iv:r8Z+Rm0nt2ZVP2Fy6CWahcs6ZVUryX1xw3C9r3q5ifc=,tag:mRkmSQH7D+h6ImlTDHASdg==,type:str]
    BIFROST_ENCRYPTION_KEY: ENC[AES256_GCM,data:r2K8x2Ihoqgj3O7Rw69oXF3EJUhf5O2/teG5VALwwDy4rFoLLDm8E/uaoLxFCQVWsnws8/qqN9KNcWefVFqPdQ==,iv:q8FfnVIFBKFzKz6HN0Z7Gteg4UsaI6zBlMiVwRwpfbw=,tag:nTI2fy2m5Un9yQRFkvQP4A==,type:str]
sops:
    age:
        - recipient: age15v9ufl7p4vd2f67xsx5tstkmhzdrqgfj5408p9e3s7dyyc8mnacq44hkk9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTemsrcmpaSlJ2TDZuWHhl
            bDMxaWlTcUc1RmxaSkhCb1c3b0ZYV0FmMmlZClc3eG1ZV3NZUXdTcEJibkV5QTVT
            ZnJUSVBPOUFMVzRIMEtTclZYTTAvejgKLS0tIDJEZWs3ZTRXYjkrUXdlS0xLb1hO
            d0trMHlvUjhFdXRNQnhMVFpxRWNNcEEKtZ+aplP6GOrnfmPGDqzg+fxhTxL56KwI
            FQDYLGxnP/FsHA9kWHsY7gU5eFi6jq40Zc2gRq8fxIffeMjmP8cS0g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFwawprQXEkGl38Q7T0PNseL0vpoyr4TbATMkEaZJTWQ
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IEw2V0lpQSA4ZDgy
            a05GcnIrQ0JXczR0cGdLbENEV3k4VVZNMkhKa2hvb0RyUTJPczNzClB2STUyS0Vm
            NjI1K3lObnl6elplbkhTNURMWU1TbTNVSDk4bERHRXlYOUEKLS0tIFpTZ2hDM3hL
            am9ZUW92UWxhcFZrK3U4T21WaGhuQjlENkt5NHE4UGZnWmcKIGUtTBoyZXus+vyF
            1XwaB3ou8I7GPrjU7Tjz4WW0fgSaw1By8rr+srfkoIfyTffnP+Zl/FcWudbh/RJD
            54bvTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-09T14:05:00Z"
    mac: ENC[AES256_GCM,data:hwoBPTzj4D513OD5eIX8B+dhCU3OojrBKrEKC8CWhTvxyxrLoTytDm5Lr6a1i3fHKUPCYcfo5x73SQAa9/bUG0I/bpb/hfTCNlcSZgaZ17McPdNHtgICtQdcbrqwV7ZbGkrjUIfIeROdqBAKLCiOJciq+yMhuKaFljxM9A6DBX8=,iv:LoF03TRardezs1TPTzRLtKh9XNxq0BRpZfERlr0cyzw=,tag:8tvrqjvFt11aqm14y98qRg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
