apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: llm-gateway
configMapGenerator:
  - name: bifrost-config
    files:
      - config.json=bifrost-config.json
  - name: cliproxyapi-config
    files:
      - config.yaml=cliproxyapi-config.yaml
      - prepare-config.sh=prepare-cliproxyapi.sh
resources:
  - bifrost.yaml
  - cliproxyapi.yaml
  - credentials.sops.yaml
  - route.yaml
