apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: fastboopmos
spec:
  ignore: |
    /*
    !/infra/
    /infra/*
    !/infra/k8s/
    !/infra/k8s/**
  interval: 1h
  ref:
    branch: main
  url: https://github.com/samcday/fastboopmos.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fastboopmos
spec:
  decryption:
    provider: sops
    secretRef:
      name: rokkitpokkit-age-key
  interval: 1h
  kubeConfig:
    secretRef:
      name: admin-kubeconfig
  path: ./infra/k8s
  prune: true
  sourceRef:
    kind: GitRepository
    name: fastboopmos
  targetNamespace: fastboopmos
  timeout: 2m
