apiVersion: v1
kind: ConfigMap
metadata:
  name: pmos-caddy-config
data:
  Caddyfile: |
    {
      admin off
    }

    :8080 {
      @health path /healthz
      handle @health {
        respond "ok" 200
      }

      handle {
        rewrite * /samcday-pmos{uri}
        reverse_proxy https://s3.eu-central-003.backblazeb2.com {
          header_up Host s3.eu-central-003.backblazeb2.com
        }
      }
    }
