apiVersion: v1
kind: Service
metadata:
  name: kube-vip-metrics
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kube-vip-ds
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 2112
      protocol: TCP
      targetPort: 2112
  selector:
    app.kubernetes.io/name: kube-vip-ds
