apiVersion: v1
kind: Secret
metadata:
    name: tofu-env
    namespace: kube-system
stringData:
    B2_APPLICATION_KEY: ENC[AES256_GCM,data:itOn+Eyqg9QJHuLsQ0kpfFbSv2eaozrze+OzweYt/1Xt5qdaqGlf4T9l,iv:lMadTfhY2keQ7PN25HIZUSXkN2lRjfLUvNlvNvyuuzg=,tag:Y8d278W2JBuMmMNdc6TVXQ==,type:str]
    B2_APPLICATION_KEY_ID: ENC[AES256_GCM,data:VvmhNvqHkrF6KaCZ,iv:dd1JUbrDcfbkCSA6w3bynzVzrX6LU/HbsvsWctMQhAg=,tag:SCTN1S0+lJHvNos9C5uoNg==,type:str]
    CLOUDFLARE_API_KEY: ENC[AES256_GCM,data:TR5EMJ4866ez3iz9IB1DcWeaQRC7Eiq4C7d9SzEQUqQP8rJ9QA==,iv:CTpEXyfnMYiYoS+3Gjlt9ye6KP10GDTUpYkpNjQbZDw=,tag:AsfRTj1rG1gg8IU3+umXPw==,type:str]
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:F3gOjjXnW+T+IUNW2NU=,iv:jKjRPVOpOQmpAxxKPERJyHjCJUnL6+aBMs0RZoVQfNY=,tag:wz5zdaFkU14JAOe4F7pl+Q==,type:str]
    DMS_TOKEN: ENC[AES256_GCM,data:FDUlJqyK5Vfc9V+AEMnpJGlIUnfpkg==,iv:Zg6wvixlqv/IrIJbJaGOyC+wm1QRGYfenKjpdrwfZog=,tag:9DOQXkf5etWiZAKl8LBXrA==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:GmRM7uD0VRy6CtiB45ieB91k26t56nqKlU1rBJIRKXmsob60rd9AK+PBFY06DsRLK7xNVaewscliPe3MoU/zVH4OHOxZrW4pYAct/XblQLMJgXvqIv2DuSmW4C0h,iv:TZ+YGclQmui3EmQncMs9KAHPOrzq21Z2VuM7l2l3dIU=,tag:k2UjYoWJSo8VqpuUZ9NybQ==,type:str]
    TAILSCALE_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:kr8IwNxRzlHlNby7At3szug=,iv:LKpr0oIk2kw7+EK2X3LXBpGkJHWPpV1Iflyf5/pTwI4=,tag:EBvWvDaOjEwMnl1XO+TLHw==,type:str]
    TAILSCALE_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:81c2i9imvAEN4E0A8x0VLR/pPY0KnryIYnT66TPVijBSpmXr+vhH8M1nlIi4oCbO+E9e6cjdI0wP+v2aO/f5,iv:EGREK8kRo6/yBQ3Az7byz/Y5MgpPOvjhMSZNxIS2u/M=,tag:zI1LmBk/VjjB46H/TQMeJg==,type:str]
sops:
    age:
        - recipient: age15v9ufl7p4vd2f67xsx5tstkmhzdrqgfj5408p9e3s7dyyc8mnacq44hkk9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKak41RFVjYmpDcHVJVTBs
            V0dJVWZ5bEpnWjJ1c0h1aUxZZFRnQWlrc0FFCkxLQ3JnYnhDZHduK2pSWS9TT0Nv
            NWY2czB6WGNHU2EvSE42Ynhmd3ZnTm8KLS0tIENlSWF0UHhvMWd3c1ZaaW9NUFFT
            UE5VUGthQ3JYcHJNdkVJemFpdHJiVWcKHwTtXsC22p5VYtYEIdhzL7jh7+kFA1un
            8cdmZ4UVr7vdLAUJD5YX5sxtZaQh9ZPdzTiiSAHmTpc4K5xVW/kpPQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFwawprQXEkGl38Q7T0PNseL0vpoyr4TbATMkEaZJTWQ
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IEw2V0lpQSB0d2d2
            YVpLMXRDY2UyMmlNV012bkkzTWxIKzBwV00zd0xOMkNneEZYNmdVCndJNXc3Nkp0
            QWR6NktmcGVpaVVLM1paQW56U0U1UDRndkJaSUh6WXRuelkKLS0tIDVTVzgvYTFF
            WUQzVG9yWkxDaTlIbGJUM0xOb1NOS2EyOXgzSFRWK3Nyd1UKmUuY8XU34Dg4uZ2c
            O7HbFCewGlmh12JzMwYs7grMAC4v/AWLXuWAXNIsWm4hUMJnkLWgD7ABLUHM6UtS
            D9dQsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-07T19:42:02Z"
    mac: ENC[AES256_GCM,data:5m5UieFsynv6lsAdFfkjv+VMmt6Q7IYEf6Koy8T4JmCXKYAyGogxdouBy+kpZo9O0wFHnusUWLS2C+lDeIyODB2vjCdA4HUwh9Wos8uh72sPvIEhfGShjGE0nriYHiVXUF83MEjhqxQP2rQiETou3Fcp1g/TF6mwezjOKtNFgWk=,iv:D2DTZPfO4CUvfJYcTdMF7esdXjBzKwK8xv9Zn1U7/WY=,tag:rmnweD/IvEk6d7FJla/CRA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
