apiVersion: v1
kind: Secret
metadata:
    name: tofu-env
    namespace: kube-system
stringData:
    CLOUDFLARE_API_KEY: ENC[AES256_GCM,data:6X0QjV9xnHf6oDPd0hV4tZBYR6J60wgSBVnwEwK/BC8sZXDC8g==,iv:gniqSxtX5p6Fa0oGMZXRy18Xt9heSJGvOQNVzDtfwv8=,tag:0HFbbRshrSkxuMaEAggDIw==,type:str]
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:4CtVyvsVHI9de5dw33k=,iv:IZQprEdgQ/Cr/WhjVshpX8+YDowH+QzsM4tHH7dlgd8=,tag:ba35jmCU1sIT8AR6+zYJZQ==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:BXh1BDo2culxky3EaN+vkcqMjAUYvd7m5vI6JPbqMMKEP84gUfPlHsEn9D7J00qGZVsn2YsdPzvjPbPZ9He8M9Xq614lO4bmnESp5tnUr8TUaaiP+T/hpNiJAH7/,iv:vi4FettAEeYVlptXebyJKK6nut3SD9BZYNYF5TdiTEM=,tag:HEhTsys8QFzjb8Fmoxop0A==,type:str]
    TAILSCALE_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:OtHWzozKpIwgGHjbl2Bfhos=,iv:SBXWOvNzu2Xcs4VvGZoHjKPp+wjKd6vfmAeyzf3kEFs=,tag:/OMS5hMjjOfBnfPEeMqTiw==,type:str]
    TAILSCALE_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:h1VUE7UnryUQ39obPjZodjAdpDztn6qDqCI3DzFSWww+tl+WNP8nV+OfJ9bvMyGzUFdJd2flYHSedAN73KDr,iv:+nPcK7x/g/gfCNXG/0eY6SV4D5x9e0rCl7482mjKq4U=,tag:AknAgej+9xwVYdt6X4WKSw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tu8l2llfk32g0c4mvklqazjkj977h9xwvx3ntwt2ucdert8sufgq2g8mgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGYjRNRjM4d2V5YTFVdkhM
            bkR4M0R2d2paVkhTdVNPUWRUOXRvMngxTUUwCng4VXFLdnppUWd3WnJndnphQmNy
            UWJaeExaNkc1cTRtTlUvQWVkWldvYzAKLS0tIHNSQnFLL0xNNVR5WTZDd2lWelg3
            UTFSdmV4bEZpKzhQQWlZbCtoTTNQL2cKcKZFZ2VmZDXZ8qKEDeQ/xTXxHOW1vKiS
            ogjcQYifR6UQ+2lvjUyi99ososzr2t80lbQLvlOxGVa23+v2fMoeqg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14taxy23wzym2r9jndzsq5h8dx2f5cj5vtusfet2ggjjepp8pkfdqf6mus0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPM2dmSDJqOFk3SWFyekRV
            RHR4SktZdlVVQlozVHpCTTkzb0pLS2xyMWpJCm1ESHNtZElMM1FMTkl5T0N3cnl0
            MGliaVhkUEYxYjVUaHR2YWpvc2E0RE0KLS0tIEdwZ1N6aXI1V0dOd0EwTjA1TXFZ
            K2NGNTFZNHUyK3c4ZlE3L0N5M0YyTlUKLdhECxxgrYOwED7BInTRoNSrWXQctm6U
            lRGrFUgRr3ofEANmY6ElfpkzJpovBHMq/0tzJJfTHGcYNiaF4JShsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-02T05:48:02Z"
    mac: ENC[AES256_GCM,data:kL/PQaMURVTZXyhfPVKmPEKUV9ilEFUFrvcfo9b0UtCC+mKj2ScBseN95VHgjQFZXb0vXjE3rYVaH9Sme4e5lWJWatYA7T0TqwU0bK/YFL7fcT8wR2FZmT0wQgbkvwYTOH4XN6gLzLHzBZPxzofYCXvWDK+UshUiQxgbvVcZkbQ=,iv:9ehx3HDif1so+7rZIULwTyu/cMtoO77Yj5DalyKhLRM=,tag:IetqU1XNpsfq9SjWOraOhg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
