apiVersion: v1
kind: Secret
metadata:
    name: bl-token
    namespace: edge
stringData:
    BL_API_TOKEN: ENC[AES256_GCM,data:XOXyQWtxJHVHt/KELLYMZCbq3DzEJTiB1pvZrKD6fjcDue8kZfjweo0ZlpOO+R1oeky5Nuh/0uQ9TQFQpfBxHw==,iv:t11d/N2/z0YnH7jbnb18uQMD4u1GKn/9P56cHLEQv2o=,tag:ik1U6/KlAV/AVirLw4Il8w==,type:str]
sops:
    age:
        - recipient: age1tu8l2llfk32g0c4mvklqazjkj977h9xwvx3ntwt2ucdert8sufgq2g8mgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6a05TT3lXazJwZnVjZ2ZM
            bHdCdnVtWjFOTnJrbUNRUm9xdDNGTnB3V2pjCmtQZVprVHNWNHh3Z3hSV2M0R3A5
            b3pTMVh5VktleG1OMUpiZkdHZGN5c28KLS0tIFpqbThhMUJsK3Q3TjRib1Jrd2I5
            Ky84Z25wb0lWaVBRQ21hNG1WK0o3cXcKKoCwxz83P5fSFWazxa5oEfyLVkYxU6RK
            km+HIgJApEpdaL1jeAhVnxn1GlKHRxFuUq88kLTtsy05t0OdqjULnA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14taxy23wzym2r9jndzsq5h8dx2f5cj5vtusfet2ggjjepp8pkfdqf6mus0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQcTE4Vy9SSnc3WCtmamhq
            YUl1YmZ3ZDM0aHp2N2JKa2llODZsRnhKRUhzCml1TXlvRGxWZE9IQmxoU252ZmhO
            LzBkai9aelJQNVpXK0hkVlY1VXVBS3cKLS0tIDk0SUQvZWxWZXVyN3NrWVpoVVJN
            YzhHZ0xacGtVeGhRSDY3NzZ2d09WdUkKkXxlVA4AVt4TDQax6Rziivwwf+XqP160
            SQg/dDZ9YQOn/BE4yFEjpOe4cRMO9JlaOqYNuMR96Sz1jJ0kBKAp0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T06:38:17Z"
    mac: ENC[AES256_GCM,data:IQhfQUf8YEXd2Dy3AXDjNQcgWrTEIAlU+kxphlaIKS+OL3hwxKkW1mmOrd7zKVtffQeSxLAHraKWxdRJWl80dvBimzQnGFtaiENq3ApmPdDC805cZh5mUfgc0tI/fGdokyvSk8nOKZ4HGHtDs8aW1zs4QvhRA2rKqkblgcDAoWU=,iv:RbG/qdGeeaTn6zVWkj3LuePSj96RNUTsJL9jchBG6AE=,tag:b9M7YCaSDWhAsOJyHF9xzw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
