apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: edge-au-east-control-plane
spec:
  chart:
    spec:
      chart: charts/k8s-control-plane
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: infra
  interval: 1h
  releaseName: edge-edge-au-east-control-plane
  valuesFrom:
    - kind: ConfigMap
      name: edge-au-east-control-plane-values
    - kind: Secret
      name: edge-au-east-node-bootstrap-token
      valuesKey: token
      targetPath: bootstrapTokens[0].token
