apiVersion: v1
kind: ConfigMap
metadata:
  name: fabric-etcd-server-ca
  namespace: etcdetcetc
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIEBTCCAm2gAwIBAgIUfjaEUpEpEfuqz9p/F0DXyYJwGQ4wDQYJKoZIhvcNAQEM
    BQAwGTEXMBUGA1UEAxMOZmFicmljLWV0Y2QtY2EwHhcNMjYwNzEzMTAzMTAwWhcN
    MzYwNzEwMTAzMTAwWjAZMRcwFQYDVQQDEw5mYWJyaWMtZXRjZC1jYTCCAaIwDQYJ
    KoZIhvcNAQEBBQADggGPADCCAYoCggGBAMp71J5TjIfFV84EmaQeHt8MbiIpgUiW
    73HC/EGjY53h31IOoZxG9wEiZ3nk/PPBl6uLVKOoVHdShiygXd9cNiAWr0DC8AZo
    gTeYaFeKTiB1f3F7GG2d9xLaVcAN/R/uBw49psex9qnvsppGbZgVe8Ezp9UC50g+
    C7HeFdKK28gW7K29bdGREx55PcxmRZ3bgzEhstmQHCbir3hF+Z1nT/KAsoOc/zsM
    lqqfF1qyj40edyzJaZMjoo6O09uQkKm2ZZsk4QXHwNg183PB0008UspwutMh8aP7
    GO7KvimZr0cU4i/0KWKnqW5Ctgxwb5LQf4Z7ClgSETf1j5Ns7MOGPT54OBj0fxYV
    ju/KB1oi90gBIOadKj0n/L3/pjfYHJzDWVsb9KtqJuXf/8zX6ntVWRlY/jQPEfj9
    HolzHnlhIkU98Xbacbs18OmFpJIKYLjpAzhrrkK8p7AP5nqLT+5G5gJWe8whL4TA
    Av/Wrc09Pv6yoc3TLsEvaSWLP4AgyLhmEQIDAQABo0UwQzAOBgNVHQ8BAf8EBAMC
    AQYwEgYDVR0TAQH/BAgwBgEB/wIBADAdBgNVHQ4EFgQUGzez1tM944A+e3ZZ07VN
    /dcKGdIwDQYJKoZIhvcNAQEMBQADggGBABYlhp6Du3XAIgXV+UcxVTsYClNXYLoc
    WhM37doaC2tTUpK3Olglq1lJwnM+9UGlaWy5k9znLCtuT5+N50UmPQ5ow4SabDP4
    nhGJZhBY4aPhDWn52G5AwN4P2H4P54NmK0l+B7cJksSrmbQRPeuvqGrTZI9PAtPr
    R3QvGA0MZoxdKZ5z3eMxqOM5UpWrG478+vkz78MAc0eH/CEdUBVX4A5ML1Tri+PD
    ACtISQvkcYyUo2o9EPhP9iQdAPwYU5+DCbb2n06+RLoPjfmHzxiJNcel4wtoTvDA
    x0kPn603Z58RptzxFu7XKpWQYXOVvnmtCs/QSqv50pTT9y2eEIoyP3C6T0J1O7zq
    n5cKzA+GBMeixgL7gnHIPwa1rPLHL8WSn3FP9hSIB0LwNldDxu3mLYogxLkrS3wM
    gve2r7hYea+bvOBFU0qEE6Ra63aRD4/1Bd2unyYpM2KfW+LKpOfQ70bd+UPEGB4d
    p0n0u3tjo6xRapLuA4SwqoyZh5tb3dAHxg==
    -----END CERTIFICATE-----
