---
apiVersion: v1
kind: Node
metadata:
  name: hub-az1-cp1
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    kustomize.toolkit.fluxcd.io/ssa: merge
    samcday.com/boot-profiles: var,tpm
  labels:
    node-role.kubernetes.io/control-plane: ""
    node-role.kubernetes.io/etcd: ""
    samcday.com/mac: 6c-4b-90-2d-cd-18
    topology.kubernetes.io/zone: az1
---
apiVersion: v1
kind: Node
metadata:
  name: hub-az1-cp2
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    kustomize.toolkit.fluxcd.io/ssa: merge
    samcday.com/boot-profiles: var
  labels:
    node-role.kubernetes.io/control-plane: ""
    node-role.kubernetes.io/etcd: ""
    samcday.com/mac: 00-23-24-b9-6d-75
    topology.kubernetes.io/zone: az1
---
apiVersion: v1
kind: Node
metadata:
  name: hub-az1-cp3
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    kustomize.toolkit.fluxcd.io/ssa: merge
    samcday.com/boot-profiles: var,tpm
  labels:
    node-role.kubernetes.io/control-plane: ""
    node-role.kubernetes.io/etcd: ""
    samcday.com/mac: 6c-4b-90-3d-02-ee
    topology.kubernetes.io/zone: az1
