apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: internal-network
spec:
  hostname: internal-network
  subnetRouter:
    advertiseRoutes:
      - 10.0.2.0/24
      - 10.0.1.0/24
      - 172.30.0.0/16
      - 172.31.0.0/16
