apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ include "managed-cluster-tenant-parent.releaseName" . }}
  namespace: {{ .Release.Namespace }}
spec:
  chart:
    spec:
      chart: {{ .Values.parent.chart }}
      reconcileStrategy: Revision
      sourceRef:
{{ toYaml .Values.parent.sourceRef | indent 8 }}
{{- with .Values.parent.dependsOn }}
  dependsOn:
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.parent.driftDetection }}
  driftDetection:
{{ toYaml . | indent 4 }}
{{- end }}
  install:
    createNamespace: {{ .Values.parent.createNamespace }}
  interval: {{ .Values.parent.interval }}
  kubeConfig:
    secretRef:
      name: {{ .Values.parent.kubeConfigSecretName }}
  storageNamespace: {{ .Values.parent.storageNamespace }}
  targetNamespace: {{ include "managed-cluster-tenant-parent.namespace" . }}
  values:
    tenant:
{{ toYaml .Values.tenant | indent 6 }}
    namespace:
{{ toYaml .Values.namespace | indent 6 }}
    source:
{{ toYaml .Values.source | indent 6 }}
    kustomization:
{{ toYaml .Values.kustomization | indent 6 }}
    sops:
{{ toYaml .Values.sops | indent 6 }}
{{- with .Values.valuesFrom }}
  valuesFrom:
{{ toYaml . | indent 4 }}
{{- end }}
