apiVersion: v1
kind: Secret
metadata:
    name: admin-token
    namespace: vaultwarden
type: Opaque
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:J62uF6mNjfDknGvCeqoNSULFyY69BkFxVDB5UpoJaEBhOB+rNMr56Fa7Fmjmp9US6hmdJVh5JZmXfK1JVeOtSg==,iv:/z/BWkiNm9Zlrtn30pGPIhjEz+RGB6z9oF0qflOYQBs=,tag:zj4K3wUqsFV606u8b3VRWg==,type:str]
sops:
    age:
        - recipient: age15v9ufl7p4vd2f67xsx5tstkmhzdrqgfj5408p9e3s7dyyc8mnacq44hkk9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBja04zc3FUT3EydWtOcFIr
            bGJZVzFBbVF1VXNFNjBoUVo5Nkx5VDZXaUJjCnFWOStpUzZCVnlUSUFIYm5rNDRT
            ZzZjMXBFUjg1RWY1KzhJYjNoeXpyV28KLS0tIHR2TjJSekNPOE00MFBEb2hFV2w1
            WmhDWCttNjhoT25DajFqVUxXbnBWZTQKcjd7XOxZa0F/3KfMyFGrTIA+BdkDZyRs
            Yz6Jl3vgzrCibyoctSa+qnDyr8jVwRBnaAe5KZgYDNDg8vu8fMgVpA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFwawprQXEkGl38Q7T0PNseL0vpoyr4TbATMkEaZJTWQ
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IEw2V0lpQSB0Q3cx
            NDZUOXBmS0N0SWJXQUZxOFZ3RDBsa3UwMzdJTDJrTXBFM0ZwYUJ3CkZYVDRmV1ow
            cmtZcHI2TmdZdU1BaEFpWUZOcmtLWkZ4aUlwK2VFaUlCcU0KLS0tIERmWmh2NERZ
            eTkzeTNrVFg2SHF2VnJkSmI2V1F5ZE1jNlRObHVPWml0OUEKKtXoeFRCjCq/Gdgt
            Nsd78sl0sns8+GbwMYi4TwFFVNeztFOQk6rvgcOtJhuXEEIEy5iWnJbUDqHboILV
            zJRHIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-07T19:42:02Z"
    mac: ENC[AES256_GCM,data:cTVKnhcKSQp6D7dkTwR/zZXxrl8fdQbiX9Kkjw7vudjCVX3mvPnzn9pfuJsk5lHibUQqX15mTUYjkSmXveSBJ/V97KqEM+pf9jh8k/t/tNaniLpDZ/rkplhUchuyiGKhI5dSsqZe5xigX3H8c8jFigNVRXruEtbO2U2jJmPJogQ=,iv:aIaWT6NIXD6K/iBqo6akFm5Cy4zqgafiRvd4N6uvgS4=,tag:OTsmeBq5RpIkLlfeRLGyUA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
