variant: fcos
version: 1.5.0
passwd:
    users:
        - name: sam
          groups:
            - adm
            - wheel
            - sudo
            - systemd-journal
          ssh_authorized_keys:
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFwawprQXEkGl38Q7T0PNseL0vpoyr4TbATMkEaZJTWQ
storage:
    files:
        - path: /var/lib/extensions/tailscale.raw
          contents:
            # https://extensions.fcos.fr/extensions/tailscale/tailscale-0-1.88.1-1-43-x86-64.raw
            source: http://10.0.5.1/static/tailscale-0-1.88.1-1-43-x86-64.raw
        # This file doesn't seem to end up in the right place when installing tailscale as a sysext.
        - path: /etc/default/tailscaled
          contents:
            inline: |
                PORT="41641"
                FLAGS=""
        - path: /etc/zincati/config.d/90-disable.toml
          contents:
            inline: |
                [updates]
                enabled = false
          overwrite: true
systemd:
    units:
        - name: systemd-sysext.service
          enabled: true
        - name: tailscaled.service
          enabled: true
        - name: tailscale-up.service
          enabled: true
          contents: |-
            [Unit]
            After=tailscaled.service
            Requires=tailscaled.service

            [Service]
            Type=oneshot
            RemainAfterExit=yes
            ExecStart=tailscale up --login-server=https://headscale.tail22d0a0.ts.net --accept-routes --auth-key=file:/etc/ts-authkey
            Restart=on-failure
            RestartSec=10s

            [Install]
            WantedBy=multi-user.target
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tu8l2llfk32g0c4mvklqazjkj977h9xwvx3ntwt2ucdert8sufgq2g8mgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMeFdiV2xQWFVvV2ZBNTJQ
            QjVFT09uY29aZHA0d0tXSXhzdzhpNFhFdkNZCitjVUtCY3hQeFkrbUJ5Vkt2eUJK
            KzMvNUdQZXgzS2Qycm5FaGYwM0FzWGsKLS0tIFRTNUJjdWErckRCNmRjR1lrRk8z
            K3RNbGVRQ2FFcW5najdhTnROU1JKeXcKPzBYu5KDGCHIqaJddzZXg5bkkvbltCN4
            fZrQtPZ3Tdm0vmIK4zIUZ7bYCj97Rk82jTiNNj3B4IAKs1rlG8Gdow==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14taxy23wzym2r9jndzsq5h8dx2f5cj5vtusfet2ggjjepp8pkfdqf6mus0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkWTZ6eURqT3J4VDFibDU5
            OWp5SjNaSWNVdCtsYmdiVzdrc25IMXBmZDA0CnNhN1BtRzBTaWJ2bjdtUkYzaUJ3
            OGVNREl2YU1lVXc0SHZndXplckV0QWcKLS0tIEpERnJEcEI0N055YTBsWVJUc0c3
            OHlmUDFjakpLTFRqcmxrOS91ZzhPRmcK3617v1czLyoJypQ42RP7+BGc51K5s/4r
            1emqJ32ptvOf3qKdOr/wzP44U6SaMv1U2lafLO3E/Atv0fBzBoWhUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-17T00:49:15Z"
    mac: ENC[AES256_GCM,data:dxHh35BUgoYFVNx4NmQEEL0M9oWmyHLo/IqoFlgDVz7wCgHCJ/qIq/KsTJaRcawZpUT2DQnHCmeuAvKiwBVgZVt9TEEm6gXlp9h7wngoTrTIpGqgdXWL96rxfBmvQwNeK3wOfFosAPgTCC1oI51/B8k2wgNAZZ+vljIPj14dYwg=,iv:jnw8IjWlGkqNxsUhvuaRsusriV3wI6n1kX7Nox/EKC0=,tag:gfs564bCEHGcSo2L/3h8tA==,type:str]
    pgp: []
    encrypted_comment_regex: cryptme
    version: 3.9.4
