---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cloud-cluster
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      version: v1.17.1
  interval: 1h
  kubeConfig:
    secretRef:
      name: admin-kubeconfig
  postRenderers:
    - kustomize:
        patches:
          - target:
              group: admissionregistration.k8s.io
              version: v1
              kind: ValidatingWebhookConfiguration
              name: kube-system-cert-manager-webhook
            patch: |-
              $patch: delete
              apiVersion: admissionregistration.k8s.io/v1
              kind: ValidatingWebhookConfiguration
              metadata:
                name: kube-system-cert-manager-webhook
          - target:
              group: admissionregistration.k8s.io
              version: v1
              kind: MutatingWebhookConfiguration
              name: kube-system-cert-manager-webhook
            patch: |-
              $patch: delete
              apiVersion: admissionregistration.k8s.io/v1
              kind: MutatingWebhookConfiguration
              metadata:
                name: kube-system-cert-manager-webhook
  storageNamespace: kube-system
  targetNamespace: kube-system
  values:
    # https://github.com/cert-manager/cert-manager/blob/master/deploy/charts/cert-manager/values.yaml
    config:
      apiVersion: controller.config.cert-manager.io/v1alpha1
      kind: ControllerConfiguration
      enableGatewayAPI: true
    installCRDs: true
    prometheus:
      servicemonitor:
        enabled: true
    startupapicheck:
      enabled: false
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-issuers
  namespace: cloud-cluster
spec:
  chart:
    spec:
      chart: charts/resources
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: infra
        namespace: flux-system
  dependsOn:
    - name: cert-manager
    - name: etcd-ca
  driftDetection:
    mode: enabled
  interval: 1h
  valuesFrom:
    - kind: Secret
      name: cloudflare
      valuesKey: token
      targetPath: cloudflare.stringData.token
  kubeConfig:
    secretRef:
      name: admin-kubeconfig
  storageNamespace: kube-system
  targetNamespace: kube-system
  values:
    _:
      apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
    letsencrypt:
      spec:
        acme:
          email: me@samcday.com
          server: https://acme-v02.api.letsencrypt.org/directory
          privateKeySecretRef:
            name: letsencrypt
          solvers:
            - dns01:
                cloudflare:
                  apiTokenSecretRef:
                    name: cloudflare
                    key: token
    selfsigned:
      spec:
        selfSigned: {}
    etcd:
      spec:
        ca:
          secretName: etcd-ca
    cloudflare:
      apiVersion: v1
      kind: Secret
      metadata:
        name: cloudflare
        namespace: kube-system
      stringData:
        token: ""
