apiVersion: apps/v1
kind: Deployment
metadata:
  name: matchbox
  namespace: matchbox
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      name: matchbox
  template:
    metadata:
      labels:
        name: matchbox
    spec:
      containers:
        - name: matchbox
          image: quay.io/poseidon/matchbox:v0.11.0
          env:
            - name: MATCHBOX_ADDRESS
              value: "0.0.0.0:8080"
            - name: MATCHBOX_LOG_LEVEL
              value: "debug"
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8081
          livenessProbe:
            initialDelaySeconds: 5
            httpGet:
              path: /
              port: 8080
          resources:
          volumeMounts:
            - name: data
              mountPath: /var/lib/matchbox
            - name: assets
              mountPath: /var/lib/matchbox/assets
      volumes:
        - name: data
          emptyDir: {}
        - name: assets
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: matchbox
  namespace: matchbox
spec:
  loadBalancerClass: io.cilium/bgp-control-plane
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    name: matchbox
  type: LoadBalancer
