apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  name: fabric-root-consensus-placement
spec:
  policyName: fabric-root-consensus-placement
  validationActions:
    - Deny
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  name: fabric-root-consensus-binding
spec:
  policyName: fabric-root-consensus-binding
  validationActions:
    - Deny
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  name: fabric-root-consensus-node-invariant
spec:
  policyName: fabric-root-consensus-node-invariant
  validationActions:
    - Deny
