apiVersion: v1
kind: Secret
metadata:
    name: gibblox-webhook-token
    namespace: cloud-cluster
stringData:
    token: ENC[AES256_GCM,data:e6eBxkmF3NBVr+j543eqF5TnuiBD1fzFXj9aD+z8NbDRcOmkH7eiLjiE5jrUD4tmbfBu9s9ENM5SZt4dmXqwaA==,iv:YOzZAYZGf4kbVNxF7TrCr4wvKIOHPBZskYUSGy6GEFU=,tag:XCgriiSkjUm7visVDqmebQ==,type:str]
sops:
    age:
        - recipient: age15v9ufl7p4vd2f67xsx5tstkmhzdrqgfj5408p9e3s7dyyc8mnacq44hkk9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQUTZnWEYvOUtRQ24zQTJ0
            MnBmaE82MS9qWCtwVnlpMzh6SDhlVmxrSEZZCjQ2VDR4UFI1RS9QWk9UV2hKQmts
            dUNyQjJlazdQWVdabDFUMml5cm1CSTAKLS0tIFJRVEJrVzYwR3FmSnlOczI1NUls
            OEJVb29Vc2VMYjFJdzZDYitwSVVYZlEKbYf/6xnh+ObloUFLohCXnja+9gtYMtPJ
            /a4tZO3eEAUbB0wvA5dcBHSSVcsMFhBmKFL3DLyFEOYeppz2QibC4A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFwawprQXEkGl38Q7T0PNseL0vpoyr4TbATMkEaZJTWQ
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IEw2V0lpQSBva21X
            MDZFQjFkd04zaHNyMkFWOTdlbGFKSDdkRXV0aVRJV0h3TmY1dzFjCmxmbHdJdjN0
            ZHU3SXg1OEt4dFRsWlltdlJScFRSZTZMK2g5T0VYK1VmR1UKLS0tIG5wc1RqRUpz
            d0pMUU9SNE5FVThCSHlpaTFKN1FjbHdMdUpXOURDLzd6L00KPG/9SXSmgEmVClJq
            UowrLmVApFLv52+przXDJbRPeccFDqHfWjoXClWmHopI8Ee4qf2Mqhdy1QjcUqJP
            uaPfXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-07T19:45:03Z"
    mac: ENC[AES256_GCM,data:QASYUKvZbpxlPxX1kJmPmj2sg72Nn96znInYmLgPlJIfWcm4M0brOKGqrJ2KBV8NvqpzZsOkO7ub89pQzF5XdeTYUl4KBPQ6jy9WTSSOH/vkEDWCaoRkqxpTMkz5BOKjjNxDv/OTWHtRGsCVrifOe01yQtZnLNJYFvlKJTxxoP0=,iv:UynWw5YvKxPDIzhQJUqrqdpNmUI2OlVnKoQ+ANpa+00=,tag:1dvLvwefwGORpLqNErLgYA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
