apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gibblox-tenant
  namespace: cloud-cluster
spec:
  chart:
    spec:
      chart: charts/managed-cluster-tenant
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: infra
        namespace: flux-system
  dependsOn:
    - name: flux
  driftDetection:
    mode: enabled
  install:
    createNamespace: true
  interval: 1h
  kubeConfig:
    secretRef:
      name: admin-kubeconfig
  storageNamespace: flux-system
  targetNamespace: gibblox
  values:
    tenant:
      name: gibblox
    namespace:
      create: false
    source:
      interval: 5m
      url: https://github.com/samcday/gibblox
    kustomization:
      interval: 5m
      path: ./infra/k8s
      prune: true
      timeout: 2m
