apiVersion: v1
kind: Secret
metadata:
    name: rokkitpokkit-webhook-token
    namespace: cloud-cluster
stringData:
    token: ENC[AES256_GCM,data:iPmUEkioOIQYQ71nO9bi9VwoG4ONGOLQVtJimBBVahA39CO1k9O1m9OaXh/e0tEw4i3Y7W5Mv2R94ta2yzWNYg==,iv:Hv4cu6uoUxKEcwzv9Vlgo74wjPHq7TngF04cYsrKm9M=,tag:i0cU+qskLKVVNcPO+stpnA==,type:str]
sops:
    age:
        - recipient: age15v9ufl7p4vd2f67xsx5tstkmhzdrqgfj5408p9e3s7dyyc8mnacq44hkk9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCNUxqcnpucFFSdlltZy9w
            d1V5WU43UW8zVnphZEFUWmFCRkVjQ3loWkZNCjdmL1RiMUJSMjdNdGlOdGNWQTlq
            VGUrRDBIQWYxWjVxUnBHK1p1STQzdkkKLS0tIGhCQUZTYXpaaEpwcWtPckJQYVN2
            S2U0ZlZjT004TFBRVUM1b1hGMDJDazAK26/SXECuyVmQyBrIgaa1DD82VRTT6Qez
            GrTEChg/yR+b9wj5LfM1ndG+H3eVABzj/ZAjZEPkfnNfUUrKuV9r+w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFwawprQXEkGl38Q7T0PNseL0vpoyr4TbATMkEaZJTWQ
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IEw2V0lpQSA4eDVP
            WWNSRmUrRmUyYkdIMEZRWWtOMGlkTmhaZGQ5bk1XbFVTTGlub0gwCmV3ZmRBV3Bt
            dXpQTHQxMGcxVzhJT3djVzdEY2duWnd5NnJ4M202UmFuUDQKLS0tIDBmL0E5emRE
            RUFhbkNzTDZZbERkcEN3eDZ3T2ZNalZOUFRqNXdRVUdrZGcKfEEbxatY2vzlrH/O
            4PeyvV97p9/nsFV52p+xYRzU20980o70IIV8adB1vPqcLcJaCG78iZ9wWhSYcnUw
            FlF2Rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-07T19:45:03Z"
    mac: ENC[AES256_GCM,data:vVtkQzl8fscm0Xxct9Xo0y+2Ey6zmacjsDTZfVh6W+C0md6D2OOyM5EyPy+0jREti6gsSW/PcZM1qrozp1c1ZVoqH0rBJiqaKOJwFD/RDRXXZOoKVPrfUhR9jMBpZM9o8IHyCMsBoLWQsNiqSXNCyGGqdwr/3VdxpelqukUFklE=,iv:4Nh/OTgI4W4tEup5tfmoEjYTY4y0AaWT3AHVG/kwB78=,tag:WNOD5MfainftILMJFboYKQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
