apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rokkitpokkit-tenant
  namespace: cloud-cluster
spec:
  chart:
    spec:
      chart: charts/managed-cluster-tenant
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: infra
        namespace: flux-system
  dependsOn:
    - name: flux
  driftDetection:
    mode: enabled
  install:
    createNamespace: true
  interval: 1h
  kubeConfig:
    secretRef:
      name: admin-kubeconfig
  storageNamespace: flux-system
  targetNamespace: rokkitpokkit
  valuesFrom:
    - kind: Secret
      name: rokkitpokkit-age-key
      valuesKey: age.agekey
      targetPath: sops.ageKey
  values:
    tenant:
      name: rokkitpokkit
    namespace:
      create: false
    source:
      ignore: |
        /*
        !/infra/
        !/infra/**
      interval: 5m
      url: https://github.com/samcday/rokkitpokkit.git
    kustomization:
      interval: 5m
      path: ./infra/k8s
      prune: true
      timeout: 2m
    sops:
      enabled: true
      secretName: rokkitpokkit-age-key
