apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rbac.yaml
  - deployment.yaml
configMapGenerator:
  - name: bootie-node-inventory
    namespace: bootie
    files:
      - nodes.tsv
    options:
      immutable: true
      labels:
        app.kubernetes.io/name: bootie
        app.kubernetes.io/part-of: fabric
