apiVersion: v1
kind: Secret
metadata:
    name: dex-oauth
    namespace: forgejo
stringData:
    key: ENC[AES256_GCM,data:QzR7OlwhsA==,iv:fEoEkqDfrP/2AGDYD4J4UKm+EW8Wn4LsyO+q0PYgFno=,tag:BSlGIbT4nS56dHX+F2jFAA==,type:str]
    secret: ENC[AES256_GCM,data:t9LUrTLScTB83TlhyyeZlsavtYLsq/WHCjbkHLnaf3F7YFPcHyw76aPDURi9oIIIqITvWzBlQUhev5N9lTovmQ==,iv:DEcFT69jbnUwwQ9m76sidUW98AlMfHrsesXbhrf4QRc=,tag:IWEZuucVUn8drb8R7PiKgg==,type:str]
sops:
    age:
        - recipient: age1tu8l2llfk32g0c4mvklqazjkj977h9xwvx3ntwt2ucdert8sufgq2g8mgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWM01XSnFja1QvUVlXRzBu
            Y0VvM0cvaEhhV0k2dUxrRk9MNll0dUc0ZEdNCmFtRjg0c2NBT1l0NkRKRnFhK0RW
            WFNzL1ZydHpFSDFtRUVETzZiQ1Naa2cKLS0tIDJwRGVtUnpua01GVVZLKy9LNGhR
            WXVxeWk4UXFiQkY0SWZnem1WOUxPWDQKRh4zZOIq8RqY6WM9A3Qs/c7jCz1a+ogJ
            K5B2uCPOfYjvX0ei33nP6vLmMO0oamnNCUd+xfHLxj+R7F8YZ9a1jg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14taxy23wzym2r9jndzsq5h8dx2f5cj5vtusfet2ggjjepp8pkfdqf6mus0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwZTJnVTIwOC84OVZzaXFG
            dkxWbC9kaEd0YSs4R1VYVHNPQ2l1SDVUcTNRCkowSms4TEQwUk55VFRZZUlyWkIy
            T1dYc2Q5R0pXNmdOVWljTHk1c2xwaGMKLS0tIGlMeFREYTcwZkRyaE9LanFWVGNG
            N0VqTkZzc1JSdXJqVkZwWGpKdDVHV0kKnlT5RWrDys/8jl3Bos2/w5cZwasZ9bvr
            Lsd2bSi2plDgjTHjh91/kBQqb8NHRBE0vFfBprSu6am9BxvqEfDiEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-23T10:30:45Z"
    mac: ENC[AES256_GCM,data:QTqi9qU8XNRRoh4p+KdbHlDHo+HGRmEW6VET9ttko4XyRvwGjX7fSYHkqA2zyczEUrh+QTGxAxhzf1aaXnypioJMya/B5/6z00R0Yy5jKgdZz7vWr4K65j5JdKrcabKmWTpqsHbYUuBo9MJsgi0B9De130l2wvdChXcglo3fVU4=,iv:iZkcrbvNDSzryHSp15ebryTEaCglurJdxb+IFX48PGk=,tag:ifIfYKG5BICkV7agXpD5Rg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
