apiVersion: v1
kind: Secret
metadata:
    name: dex-oauth
    namespace: forgejo
stringData:
    key: ENC[AES256_GCM,data:6rmjDre42w==,iv:AXKKZeD5IRnCaAOmiqOrwazxPo1sHEeYb8iFuZVUQQE=,tag:Wz/0egkoxmzuuRmBuG6GCw==,type:str]
    secret: ENC[AES256_GCM,data:1g+JIJDzzl4uJ8bicHWEjZDHpaEYgTr2XLBXIvJ2RGYxhEw7yR6UQqivEc3YLXH/iDV2R8vYFPpV3u7UGLvX8w==,iv:ZYTWhW7IQqEEq60hySIqc+egGt961hYyVy9dHOsacXw=,tag:gRwvZrSlhY6LkEFpfdhzhQ==,type:str]
sops:
    age:
        - recipient: age15v9ufl7p4vd2f67xsx5tstkmhzdrqgfj5408p9e3s7dyyc8mnacq44hkk9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZ1c2YjhXREtteVgvRjBL
            cDAxL3d4by84aW1ESUhabnRMaXVzbFE5OVhjCnFlb2NqR3JIQTlMRkU0Rk9KTG8w
            cE93a1dHUFE4S2duV0JzTlpFNEV2SXcKLS0tIGl2blh2SlllQmM3WlluZWdTWEdT
            YnlzQzJNaGF6K1lIalAwRGVUN2FMTUEK7ZN/ttA487rSSc+dc3oZYH9lZ+FNjEqW
            JcgISET/B1qIYkDQpQiL5UAtsPm6oGYYFWaE3/Ljs6TrMhXMiG1+qQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFwawprQXEkGl38Q7T0PNseL0vpoyr4TbATMkEaZJTWQ
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IEw2V0lpQSBEdFlQ
            SG9nZWZFZDZ4eFczNHNzQ2FiQzNPQmFuOWR1STJ4Rkl6SVYyTms4CnZNQSs5c2ZV
            c1l5Smw1bG5DUE85T3FuQkxTeUdoVk9PTnFUVHNGT293ZnMKLS0tIDBRRU9BV2pX
            T3cyY1JWTzJEK0E0NEFPYUhDRUx2MlBRRTFPTE1uVVZQbEkKDt5U7eaXZqIaWIFo
            vyjG/haQ/gdY6b1GG/w+RDUiv+Wi29G4lkrJZOL/4U7XfTlwEWPhy7jPxEikPYwZ
            ADJFRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-07T19:42:02Z"
    mac: ENC[AES256_GCM,data:+DI1R5aCPcilos4pg0dQYLqxZLhZgxA7GxSCy6pqbGtJdOkrGAb4J3zOXNC3T+O4iMbwb3FDL90JRSzybhmA7/qDcvoYt8rkHdlFqjTMq9W7H9fa5RLCPAnpuKTvFdTGgtzwa+5GJs0FhyeRN6C6tci2nneAixi98dX9iMkVrkw=,iv:/22BXnGJ7L07yaAjBA9dj6Nnpo4m1T8i7Tfta92Q5bk=,tag:yi6/YzzMeAQy4rH/gKEtmA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
