apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: db
  namespace: forgejo
spec:
  affinity:
    podAntiAffinityType: required
  bootstrap:
    initdb:
      database: forgejo
      owner: forgejo
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql
    major: 15
  instances: 1
  storage:
    size: 20Gi
    storageClass: ceph-block
