apiServer:
  extraArgs:
    - --oidc-issuer-url=https://dex.samcday.com
    - --oidc-client-id=fastboop-kubectl
    - --oidc-username-claim=email
    - '--oidc-username-prefix=oidc:'
  service:
    spec:
      type: ClusterIP
bootstrapTokens:
  - extraGroups: [system:bootstrappers:kubeadm:default-node-token]
    # token ID+secret is set from HelmRelease spec.valuesFrom
clusterCIDRs: [172.28.0.0/16]
clusterDNS: [172.27.0.10]
clusterName: cloud
etcd:
  certIssuer:
    name: etcd
    kind: ClusterIssuer
  endpoints:
    - https://hub-az1-cp1.hub.internal:2379
    - https://hub-az1-cp2.hub.internal:2379
    - https://hub-az1-cp3.hub.internal:2379
# see the ts-apiserver resources
externalHostname: cloud-cluster-apiserver.tailnet.hub.samcday.com
externalIP: 100.64.0.3
konnectivity:
  agent:
    image: registry.k8s.io/kas-network-proxy/proxy-agent:v0.32.0
  server:
    image: registry.k8s.io/kas-network-proxy/proxy-server:v0.32.0
parentClusterDomain: cluster.hub.internal
scheduler:
  deployment:
    spec:
      replicas: 1
      strategy:
        type: Recreate
      template:
        spec:
          containers:
            - name: kube-scheduler
              # command:
              #   - -v=6
serviceCIDRs: [172.27.0.0/16]
serviceIP: 172.27.0.1
users:
  - name: forgejo-runner-sync
    commonName: forgejo-runner-sync
    exportKubeconfigs:
      - name: cloud-cluster-forgejo-runner-sync-kubeconfig
        namespace: forgejo
        external: false
    rbac:
      - namespace: forgejo-runners
        rules:
          - apiGroups: [""]
            resources: ["secrets"]
            verbs: ["create"]
          - apiGroups: [""]
            resources: ["secrets"]
            resourceNames: ["forgejo-runner-secrets"]
            verbs: ["get", "update", "patch"]
