apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: fastboop
spec:
  ignore: |
    /*
    !/infra/
    /infra/*
    !/infra/k8s/
    !/infra/k8s/**
  interval: 5m
  ref:
    branch: main
  url: https://github.com/samcday/fastboop.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fastboop
spec:
  decryption:
    provider: sops
    secretRef:
      name: fastboop-age-key
  interval: 5m
  kubeConfig:
    secretRef:
      name: admin-kubeconfig
  path: ./infra/k8s
  prune: true
  sourceRef:
    kind: GitRepository
    name: fastboop
  suspend: false
  timeout: 2m
