apiVersion: v1
kind: Secret
metadata:
    name: flux-webhook-token
    namespace: cloud-cluster
stringData:
    token: ENC[AES256_GCM,data:olmDPpu4Uo2e7XXoZP0uv/UHq0nTmXoYZICGqI/HK5w=,iv:lPpmxzxnyeo4jo34Wio3As35V3nFSmLxZ0CHU+29wyA=,tag:RDjSqif3OPzou90pCPFiEg==,type:str]
sops:
    age:
        - recipient: age15v9ufl7p4vd2f67xsx5tstkmhzdrqgfj5408p9e3s7dyyc8mnacq44hkk9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0cWppVHJlenYwdG9nZUVk
            UnkzTEUrN3Q5M2JIRTMvVnN0TUlIdVI3clFZCmo3WnhSSzlDckZObXNBV3NCRzU5
            OStKUjFvU05CU0IzbWY5WkdxVHYrVkEKLS0tIDZsQWMvTGZlWTRFbUhXRXh5cHAz
            OVBRY0Y3eG9hZGNobUV0bkxYQ2dodlEKGJICf/XpJSSdEACSUHkSysIAL04nTzcz
            HBa1dbKwxo7QvS4WLpAD36/Mp3k9gVgiwmYNqdPzHw6YVgIHcuP3Sw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFwawprQXEkGl38Q7T0PNseL0vpoyr4TbATMkEaZJTWQ
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IEw2V0lpQSBUZjdN
            aUhCTlM2TnFPTUtIMHJZMTh5VmhnWHJUNnVDeWtZbUViaW1CSVNJCk11dGw1dnRG
            TFRMeTdrTE1Xa0pnUFI0UEhMQ3B1SmlEUEd5WVIrSnFYLzAKLS0tIDdlWEczdUNB
            dGhmVEQrbnV6MloxV0NnTndnYjhvQWthNlovRmhmN25PdzgKgvQbPIQS/XaFIOZq
            JXnAuSYDzZ5QLh8GNAWKpoDmIBrOVaVknaHHgKvGQy8/zKzAnKcTrwqzPD2eWg6N
            oAOi7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-07T19:25:52Z"
    mac: ENC[AES256_GCM,data:S+ebtcaIRQ6UfwfvQb7iYj/w9m5myvJe9TPIvEwc0FJ8lgxQPTR4HrB37YeBVMvJ5SrmRJ5N3nTt81hQRGyDh4WDsPXHb8BqeWB/eNeccLhzlCW5ywC2ZJeO2tDvkptRuo6TSj9J+NS+/oFe8Luj4FXQVWwDLc2ZSqGbY+SlqcE=,iv:NhqDSEPD59LwnseGKceAZnPNMGD/5XI/fAdL/vlx2mo=,tag:19t34ItLoJd74m2IxwkNfw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
