apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kustomizations
  namespace: cloud-cluster
spec:
  chart:
    spec:
      chart: charts/resources
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: infra
        namespace: flux-system
  driftDetection:
    mode: enabled
  interval: 1h
  values:
    _:
      apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      spec:
        interval: 1h
        prune: true
        sourceRef:
          kind: GitRepository
          name: infra
          namespace: flux-system
        timeout: 5m
    kube-system:
      spec:
        path: hub/cluster/cloud-cluster/kube-system
    gateway-api:
      spec:
        dependsOn: [name: kube-system]
        kubeConfig:
          secretRef:
            name: admin-kubeconfig
        path: hub/cluster/cloud-cluster/gateway-api
    etcd:
      spec:
        dependsOn: [name: kube-system]
        kubeConfig:
          secretRef:
            name: admin-kubeconfig
        path: hub/cluster/cloud-cluster/etcd
    forgejo-runners:
      spec:
        dependsOn: [name: kube-system]
        kubeConfig:
          secretRef:
            name: admin-kubeconfig
        path: hub/cluster/cloud-cluster/forgejo-runners
        targetNamespace: forgejo-runners
