apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-gateway-test
  namespace: cloud-cluster
spec:
  chart:
    spec:
      chart: charts/resources
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: infra
        namespace: flux-system
  dependsOn:
    - name: nginx-gateway-fabric
    - name: wasmcloud-demo
  driftDetection:
    mode: enabled
  interval: 1h
  kubeConfig:
    secretRef:
      name: admin-kubeconfig
  storageNamespace: nginx-gateway
  targetNamespace: nginx-gateway
  values:
    certificate:
      apiVersion: cert-manager.io/v1
      kind: Certificate
      metadata:
        name: wasmclouddemo-nginx-gateway-certificate
      spec:
        dnsNames:
          - wasmclouddemo.samcday.com
        issuerRef:
          group: cert-manager.io
          kind: ClusterIssuer
          name: letsencrypt
        secretName: wasmclouddemo-nginx-gateway-certificate
    gateway:
      apiVersion: gateway.networking.k8s.io/v1
      kind: Gateway
      metadata:
        name: nginx-edge
      spec:
        gatewayClassName: nginx-edge
        listeners:
          - allowedRoutes:
              namespaces:
                from: All
            name: http-alt
            port: 81
            protocol: HTTP
          - allowedRoutes:
              namespaces:
                from: All
            name: https-alt
            port: 444
            protocol: HTTPS
            tls:
              certificateRefs:
                - name: wasmclouddemo-nginx-gateway-certificate
              mode: Terminate
    wasmcloud-demo-route:
      apiVersion: gateway.networking.k8s.io/v1
      kind: HTTPRoute
      metadata:
        name: nginx-edge-wasmcloud-demo
        namespace: wasmcloud
      spec:
        parentRefs:
          - name: nginx-edge
            namespace: nginx-gateway
        rules:
          - backendRefs:
              - name: hello-world
                port: 80
            matches:
              - path:
                  type: PathPrefix
                  value: /
