apiVersion: v1
kind: Secret
metadata:
    name: rokkitpokkit-tofu-state-passphrase
    namespace: cloud-cluster
stringData:
    TF_VAR_state_passphrase: ENC[AES256_GCM,data:l2a94/R1m6sVYcafjDJ4oAFXaiIvB59swSf2km2pHfU=,iv:3DEbYm0diRGGlIc2tyBMaleKs6PkYEVAVJJYRcD1HMM=,tag:ltzYLPk3ThF3+6RZUkJtBQ==,type:str]
sops:
    age:
        - recipient: age1tu8l2llfk32g0c4mvklqazjkj977h9xwvx3ntwt2ucdert8sufgq2g8mgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzT1oxTEwvNnZTSTF4dHBB
            cmg5S0QyTDRmQVE1WDh2SUhSSkNUYzB1Sm5BCmVLb0JwRVREcFpuYkpQRmVoSkRm
            aS9pdUVRRGx6T1VZYlBybFRqNjBrMGMKLS0tIFFzYVpEVU1aRFdXMGUxWjg2dHc2
            MHZDK29zcHdWK2djMy9jTW5rSW8zN1UKw0HMztlzb0lHUJPoPAr5Brnei4XqFc2m
            OE0eynWBWc6BAN9cXXvY9ErTRgGfiYWRv4f177TXWnnZXO4U3n7iRg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14taxy23wzym2r9jndzsq5h8dx2f5cj5vtusfet2ggjjepp8pkfdqf6mus0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4cThVWk12YWRWdE1DSmcy
            cVorVnFoQXl2SjZNRXVSV29WZVpOWDRvSHdZCjNqeDBWTjdBWHpiUWlaTk8vV1V5
            MFFkNDAwWWZhdTNjOXFHaDVZaFpGdmsKLS0tIEs5N3RGVTBuOXgvL1JITEx2c3Jr
            bGxQWFkwNGU0ekxHL1czaU95U0Y0T2sKV/Z0tpH/clCaFZLbrWa84fXqfOBKlAyX
            oK3e/FkRLmUFrpUcNUcraSrHFsWQgUr7yHyVreaqhv7RToopwpUEfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T05:20:49Z"
    mac: ENC[AES256_GCM,data:VaK4/f0LSvlAD/rP3LvP6u5GlelVCrjMsjTxeA5rNG6fEY6sA+FaO5l+qhdcr6wXllc8jfaHjMDUk9ou4DpTS0hUMtysduReyPTt4Hsifakw4Dz6Lxgm7RV3lFEWKnm4wJ0dyrXcAHn2L2yXTTqEWIevT8o1O98kPu1Rx4mpyxU=,iv:DjF+iabfb2OqPFYhZCFrnP5kvMmmHZRpOU5KhFlc4yU=,tag:VhjZSODUcx/gbD/RbwA5aQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
