
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: rokkitpokkit
  namespace: cloud-cluster
spec:
  ignore: |
    /*
    !/infra/
    /infra/*
    !/infra/k8s/
    !/infra/k8s/**
  interval: 5m
  ref:
    branch: main
  url: https://github.com/samcday/rokkitpokkit.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rokkitpokkit
  namespace: cloud-cluster
spec:
  decryption:
    provider: sops
    secretRef:
      name: rokkitpokkit-age-key
  interval: 5m
  kubeConfig:
    secretRef:
      name: admin-kubeconfig
  path: ./infra/k8s
  prune: true
  sourceRef:
    kind: GitRepository
    name: rokkitpokkit
  targetNamespace: rokkitpokkit
  timeout: 2m
