apiVersion: v1
kind: Secret
metadata:
    name: rokkitpokkit-tofu-state-passphrase
    namespace: cloud-cluster
stringData:
    TF_VAR_state_passphrase: ENC[AES256_GCM,data:Abmq9rowBkpY8GyCH7epEnUMY5aRpcpsUJXjP0ieowM=,iv:M1k5G67+3zV2FH2NLCl+j2k3+2UJCkti5m5JEbnURrk=,tag:vKNYCwo2nXJBz+KcxBH78g==,type:str]
sops:
    age:
        - recipient: age1tu8l2llfk32g0c4mvklqazjkj977h9xwvx3ntwt2ucdert8sufgq2g8mgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzT1oxTEwvNnZTSTF4dHBB
            cmg5S0QyTDRmQVE1WDh2SUhSSkNUYzB1Sm5BCmVLb0JwRVREcFpuYkpQRmVoSkRm
            aS9pdUVRRGx6T1VZYlBybFRqNjBrMGMKLS0tIFFzYVpEVU1aRFdXMGUxWjg2dHc2
            MHZDK29zcHdWK2djMy9jTW5rSW8zN1UKw0HMztlzb0lHUJPoPAr5Brnei4XqFc2m
            OE0eynWBWc6BAN9cXXvY9ErTRgGfiYWRv4f177TXWnnZXO4U3n7iRg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14taxy23wzym2r9jndzsq5h8dx2f5cj5vtusfet2ggjjepp8pkfdqf6mus0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4cThVWk12YWRWdE1DSmcy
            cVorVnFoQXl2SjZNRXVSV29WZVpOWDRvSHdZCjNqeDBWTjdBWHpiUWlaTk8vV1V5
            MFFkNDAwWWZhdTNjOXFHaDVZaFpGdmsKLS0tIEs5N3RGVTBuOXgvL1JITEx2c3Jr
            bGxQWFkwNGU0ekxHL1czaU95U0Y0T2sKV/Z0tpH/clCaFZLbrWa84fXqfOBKlAyX
            oK3e/FkRLmUFrpUcNUcraSrHFsWQgUr7yHyVreaqhv7RToopwpUEfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T05:21:36Z"
    mac: ENC[AES256_GCM,data:y9ktHWaL+kD4s59CRDnJ4gTAbS33eQlyKB68iN1JsBQMva1CHL4OcZ9X7uLUafwAKd/wsAFY/Wx3lPE4y5OYQz/WZA5EzkqpR7uLJmo2pMzyI+AXnp/p2HJ6wVHZGWseZJF4XxpIEbI470zn3Ap+JBc8M+7eU+spEgfi9CV6Uco=,iv:tjmMlmo/WCyztk04fUXWexdwVqzMJcyLlqZGYg+f/wc=,tag:llUHg8nAc2giB/up9/Y8tg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
