apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rokkitpokkit-tofu
  namespace: cloud-cluster
spec:
  chart:
    spec:
      chart: charts/resources
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: infra
        namespace: flux-system
  dependsOn:
    - name: flux
  driftDetection:
    mode: enabled
  interval: 1h
  kubeConfig:
    secretRef:
      name: admin-kubeconfig
  storageNamespace: flux-system
  targetNamespace: flux-system
  values:
    rokkitpokkit:
      apiVersion: source.toolkit.fluxcd.io/v1
      kind: GitRepository
      metadata:
        name: rokkitpokkit
      spec:
        ignore: |
          /*
          !/infra/
          !/infra/**
        interval: 5m
        ref:
          branch: main
        url: https://github.com/samcday/rokkitpokkit.git
    rokkitpokkit-tofu-auth:
      kind: Secret
  valuesFrom:
    - kind: Secret
      name: rokkitpokkit-tofu-generated
      valuesKey: GITHUB_TOKEN
      targetPath: rokkitpokkit-tofu-auth.stringData.GITHUB_TOKEN
    - kind: Secret
      name: rokkitpokkit-tofu-generated
      valuesKey: TF_VAR_b2_application_key_id
      targetPath: rokkitpokkit-tofu-auth.stringData.TF_VAR_b2_application_key_id
    - kind: Secret
      name: rokkitpokkit-tofu-generated
      valuesKey: TF_VAR_b2_application_key
      targetPath: rokkitpokkit-tofu-auth.stringData.TF_VAR_b2_application_key
    - kind: Secret
      name: rokkitpokkit-tofu-state-passphrase
      valuesKey: TF_VAR_state_passphrase
      targetPath: rokkitpokkit-tofu-auth.stringData.TF_VAR_state_passphrase
