apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: scaleup-probe
  namespace: cloud-cluster
spec:
  chart:
    spec:
      chart: charts/resources
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: infra
        namespace: flux-system
  interval: 1h
  kubeConfig:
    secretRef:
      name: admin-kubeconfig
  storageNamespace: kube-system
  targetNamespace: kube-system
  values:
    scaleup-probe:
      apiVersion: apps/v1
      kind: Deployment
      spec:
        replicas: 1
        selector:
          matchLabels:
            app.kubernetes.io/name: scaleup-probe
        template:
          metadata:
            labels:
              app.kubernetes.io/name: scaleup-probe
          spec:
            containers:
              - name: pause
                image: registry.k8s.io/pause:3.10.1
                resources:
                  requests:
                    cpu: 100m
                    memory: 1500Mi
