apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wasmcloud
  namespace: cloud-cluster
spec:
  chart:
    spec:
      chart: runtime-operator
      sourceRef:
        kind: HelmRepository
        name: wasmcloud
        namespace: flux-system
      version: 2.0.1
  dependsOn:
    - name: wasmcloud-nats
  driftDetection:
    mode: enabled
  interval: 1h
  kubeConfig:
    secretRef:
      name: admin-kubeconfig
  postRenderers:
    - kustomize:
        patches:
          - target:
              group: apps
              version: v1
              kind: Deployment
              name: runtime-operator
            patch: |
              - op: replace
                path: /spec/template/spec/containers/0/args/0
                value: -nats-url=nats://wasmcloud-nats:4222
              - op: add
                path: /spec/template/spec/containers/0/args/-
                value: -nats-tls-first
          - target:
              group: apps
              version: v1
              kind: Deployment
              name: hostgroup-default
            patch: |
              - op: replace
                path: /spec/template/spec/containers/0/args/3
                value: --scheduler-nats-url=nats://wasmcloud-nats:4222
              - op: replace
                path: /spec/template/spec/containers/0/args/7
                value: --data-nats-url=nats://wasmcloud-nats:4222
              - op: add
                path: /spec/template/spec/containers/0/args/-
                value: --scheduler-nats-tls-first
              - op: add
                path: /spec/template/spec/containers/0/args/-
                value: --data-nats-tls-first
  storageNamespace: wasmcloud
  targetNamespace: wasmcloud
  values:
    global:
      certificates:
        generate: false
        operatorCertSecretName: wasmcloud-nats-operator-tls
        runtimeCertSecretName: wasmcloud-nats-runtime-tls
        dataCertSecretName: wasmcloud-nats-data-tls
    nats:
      enabled: false
