apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wasmcloud
  namespace: cloud-cluster
spec:
  chart:
    spec:
      chart: runtime-operator
      sourceRef:
        kind: HelmRepository
        name: wasmcloud
        namespace: flux-system
      version: 2.0.7
  driftDetection:
    mode: enabled
  interval: 1h
  kubeConfig:
    secretRef:
      name: admin-kubeconfig
  postRenderers:
    - kustomize:
        patches:
          - target:
              group: apps
              version: v1
              kind: Deployment
              name: hostgroup-default
            patch: |
              - op: add
                path: /spec/template/spec/containers/0/args/-
                value: --scheduler-nats-tls-first
              - op: add
                path: /spec/template/spec/containers/0/args/-
                value: --data-nats-tls-first
  storageNamespace: wasmcloud
  targetNamespace: wasmcloud
  values:
    gateway:
      enabled: false
    operator:
      image:
        tag: v2.0.7
    runtime:
      image:
        tag: v2.0.7
