apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wasmcloud-demo
  namespace: cloud-cluster
spec:
  chart:
    spec:
      chart: charts/resources
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: infra
        namespace: flux-system
  dependsOn:
    - name: wasmcloud
  driftDetection:
    mode: enabled
  interval: 1h
  kubeConfig:
    secretRef:
      name: admin-kubeconfig
  storageNamespace: wasmcloud
  targetNamespace: wasmcloud
  values:
    hello-world:
      apiVersion: runtime.wasmcloud.dev/v1alpha1
      kind: WorkloadDeployment
      spec:
        replicas: 1
        template:
          spec:
            hostSelector:
              hostgroup: default
            components:
              - name: hello-world
                image: ghcr.io/wasmcloud/components/hello-world:0.1.0
            hostInterfaces:
              - namespace: wasi
                package: http
                interfaces:
                  - incoming-handler
                config:
                  address: 0.0.0.0:8080
    route:
      apiVersion: gateway.networking.k8s.io/v1
      kind: HTTPRoute
      spec:
        hostnames:
          - wasmclouddemo.samcday.com
        parentRefs:
          - name: shared
            namespace: kube-system
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - name: runtime-gateway
                port: 80
