apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - vendor/v1.8.4/kubevirt-operator.yaml
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: virt-operator
      namespace: kubevirt
    patch: |-
      - op: replace
        path: /spec/template/spec/affinity/nodeAffinity
        value:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/worker
                    operator: In
                    values:
                      - "true"
      - op: add
        path: /spec/template/spec/nodeSelector/node-role.kubernetes.io~1worker
        value: "true"
      - op: replace
        path: /spec/template/spec/tolerations
        value:
          - key: CriticalAddonsOnly
            operator: Exists
