apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: edge-au-east-control-plane-inputs
  namespace: cloud-cluster
spec:
  chart:
    spec:
      chart: charts/resources
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: infra
        namespace: flux-system
  driftDetection:
    mode: enabled
  interval: 1h
  kubeConfig:
    secretRef:
      name: admin-kubeconfig
  storageNamespace: edge
  targetNamespace: edge
  valuesFrom:
    - kind: Secret
      name: edge-au-east-node-bootstrap-token
      valuesKey: id
      targetPath: nodeBootstrapToken.stringData.id
    - kind: Secret
      name: edge-au-east-node-bootstrap-token
      valuesKey: secret
      targetPath: nodeBootstrapToken.stringData.secret
  values:
    nodeBootstrapToken:
      kind: Secret
      metadata:
        name: edge-au-east-node-bootstrap-token
      stringData:
        id: ""
        secret: ""
