apiVersion: v1
kind: Secret
metadata:
  name: fabric-subnet-router-svc1-state
  namespace: fabric-tailnet
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: fabric-subnet-router-svc2-state
  namespace: fabric-tailnet
type: Opaque
