---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: litestream
  namespace: headscale
spec:
  generateBucketName: headscale-litestream-
  storageClassName: ceph-bucket

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headscale
  namespace: headscale
spec:
  chart:
    spec:
      chart: generic
      sourceRef:
        kind: HelmRepository
        name: community-tooling-charts
        namespace: flux-system
      version: 8.1.1
  interval: 1h
  values:
    # https://github.com/community-tooling/charts/blob/main/charts/generic/values.yaml
    additionalContainers:
      - name: litestream
        image: docker.io/litestream/litestream:v0.5.8@sha256:9874588ddb04789179d0d93cc902ba9309bb0cac4c33eb5631599d4559c60106
        args:
          - replicate
          - -config
          - /etc/litestream.yml
        envFrom:
          - secretRef:
              name: litestream
          - configMapRef:
              name: litestream
        volumeMounts:
          - name: data
            mountPath: /var/lib/headscale
          - name: configmap
            mountPath: /etc/litestream.yml
            subPath: litestream.yml
            readOnly: true
    additionalVolumeMounts:
      - name: config
        mountPath: /etc/headscale
      - name: noise-privkey
        mountPath: /var/lib/headscale/noise_private.key
        subPath: noise_private.key
    additionalVolumes:
      - name: config
        configMap:
          name: config
      - name: noise-privkey
        secret:
          secretName: noise-privkey
    args:
      - serve
    configMap:
      enabled: true
      data:
        litestream.yml: |-
          dbs:
            - path: /var/lib/headscale/db.sqlite
              restore-if-db-not-exists: true
              replica:
                url: s3://${BUCKET_NAME}/db.sqlite?endpoint=http://${BUCKET_HOST}:${BUCKET_PORT}&region=${BUCKET_REGION}&force-path-style=true
      mountFiles:
        - subPath: litestream.yml
          mountPath: /etc/litestream.yml
    deploymentStrategy:
      type: Recreate
    image:
      repository: ghcr.io/juanfont/headscale
      tag: v0.26.1
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        tailscale.com/funnel: "true"
      className: tailscale
      hosts:
        - host: headscale
          paths:
            - path: /
              servicePortName: http
      tls:
        - hosts: [headscale]
    livenessProbe:
      httpGet:
        path: /metrics
        port: metrics
    initContainers:
      - name: litestream-restore
        image: docker.io/litestream/litestream:v0.5.8@sha256:9874588ddb04789179d0d93cc902ba9309bb0cac4c33eb5631599d4559c60106
        command:
          - /bin/sh
          - -ec
        args:
          - >-
            litestream restore
            -if-db-not-exists
            -if-replica-exists
            -config /etc/litestream.yml
            /var/lib/headscale/db.sqlite
        envFrom:
          - secretRef:
              name: litestream
          - configMapRef:
              name: litestream
        volumeMounts:
          - name: data
            mountPath: /var/lib/headscale
          - name: configmap
            mountPath: /etc/litestream.yml
            subPath: litestream.yml
            readOnly: true
    ports:
      - name: grpc
        containerPort: 50443
      - name: http
        containerPort: 8080
      - name: metrics
        containerPort: 9090
    persistence:
      enabled: true
      mountPath: /var/lib/headscale
      storage: 2Gi
      accessMode: ReadWriteOnce
      storageClassName: ceph-block
    readinessProbe:
      httpGet:
        path: /metrics
        port: metrics
    service:
      ports:
        - targetPort: grpc
          protocol: TCP
          name: grpc
          port: 50443
        - targetPort: http
          protocol: TCP
          name: http
          port: 80

---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: headscale
  namespace: headscale
spec:
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
  selector:
    matchLabels:
      app.kubernetes.io/instance: headscale
