---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: litestream
  namespace: headscale
spec:
  generateBucketName: headscale-litestream-
  storageClassName: ceph-bucket

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headscale
  namespace: headscale
spec:
  chart:
    spec:
      chart: generic
      sourceRef:
        kind: HelmRepository
        name: community-tooling-charts
        namespace: flux-system
      version: 8.1.1
  interval: 1h
  values:
    # https://github.com/community-tooling/charts/blob/main/charts/generic/values.yaml
    additionalVolumeMounts:
      - name: config
        mountPath: /etc/headscale
      - name: noise-privkey
        mountPath: /var/lib/headscale/noise_private.key
        subPath: noise_private.key
    additionalVolumes:
      - name: config
        configMap:
          name: config
      - name: noise-privkey
        secret:
          secretName: noise-privkey
    args:
      - serve
    deploymentStrategy:
      type: Recreate
    envValueFrom:
      HEADSCALE_DATABASE_POSTGRES_PASS:
        secretKeyRef:
          name: db-app
          key: password
    image:
      repository: ghcr.io/juanfont/headscale
      tag: v0.26.1
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        tailscale.com/funnel: "true"
      className: tailscale
      hosts:
        - host: headscale
          paths:
            - path: /
              servicePortName: http
      tls:
        - hosts: [headscale]
    livenessProbe:
      httpGet:
        path: /metrics
        port: metrics
    ports:
      - name: grpc
        containerPort: 50443
      - name: http
        containerPort: 8080
      - name: metrics
        containerPort: 9090
    persistence:
      enabled: true
      mountPath: /var/lib/headscale
      storage: 2Gi
      accessMode: ReadWriteOnce
      storageClassName: ceph-block
    readinessProbe:
      httpGet:
        path: /metrics
        port: metrics
    service:
      ports:
        - targetPort: grpc
          protocol: TCP
          name: grpc
          port: 50443
        - targetPort: http
          protocol: TCP
          name: http
          port: 80

---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: headscale
  namespace: headscale
spec:
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
  selector:
    matchLabels:
      app.kubernetes.io/instance: headscale
