apiVersion: v1
kind: Secret
metadata:
    name: internal-net-router-auth
    namespace: headscale
stringData:
    TS_AUTHKEY: ENC[AES256_GCM,data:Q92sjET0DOmlQw6P7PQJtyBqEWYK3HUr1FMDx8CE/4338DNPaoUJ2RM7Hz2UczQN,iv:yMWt0zDuo1YUG5j+KjIgFkCUMeZA/62u3E7Z+zQOuEk=,tag:m1bG0rnaOKYGTT1ZIwxngQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tu8l2llfk32g0c4mvklqazjkj977h9xwvx3ntwt2ucdert8sufgq2g8mgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnN3djZWE4OXpEN0IvQjlS
            ZFFmcG5BQTcyaHlleEZiOVBkWFNEUm1KQlRrCm5zUlcvQmViNWYxOHp0aXJ1dTJN
            VERvRllwOHMwck1qa2VjRW5ERGZmeE0KLS0tIG5ldjBySDQwQlMxeHZyUGt0ckV5
            UEhYbEptSHVOeHZlSSsvQW1VTmRuaWMK3nlbb63ZjhwyUzP037Y8gyayHeI+DrVg
            FgvLr81Nh+/jAXoJbNEIvvQdkrpcBEdo67syE0a1uyPrQLBshx9idQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14taxy23wzym2r9jndzsq5h8dx2f5cj5vtusfet2ggjjepp8pkfdqf6mus0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNYWdNcXJmNXB2VGgvKy9y
            MW8wbU9kNDFPTExOR0RUZmxQV2dUa0ZNa1YwCnYwWjhBaDZLSEFuckZjeVFxZkFu
            OVVZM2I1eXdMeHpTd3IrRVBmOGFmaDQKLS0tIHdjVGkzNmFoL0RSNld6MDl3UXl3
            K0xYK0VFNmVUUXhtT2VMeFVtenVSUVEK5bRY0JfQJGdlc25b3oneQKfYNIokPkdX
            6KGArGDAPND9GwxFIn78WppeKQonamnvLHwoIsuQNYC7eb+LghhDag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-10T07:06:40Z"
    mac: ENC[AES256_GCM,data:fcVjdRSeXu+E2Kllz2n/RRbY8U7O+g7s/ambShK7PziPSrb7PC222qDSx0PiBrPvZQ/H9oZvOa5ZIcmTS1eSjycGrGAR4GIrzrVE2uYRE+Oll7VQyX+7/zBHMZfzEDmXm08UmQO+4t7tSYwnjpjdBedCMPCjUJC4c6FGQRav8vQ=,iv:xF6nYIxhqvkKqBwYQ/8BrtU/elLmhq0ALag8T31QMU0=,tag:Q9t+u5HxFBOvXqpoN9Utow==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
