apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: headscale
configMapGenerator:
  - name: config
    files:
      - acls.json
      - config.yaml
resources:
  - ../../../.kustomize-config
  - helm-release.yaml
  - noise-privkey.yaml
  - subnet-router.yaml
  - tofu.yaml
  - vpas.yaml
