apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: headscale
configMapGenerator:
  - name: config
    files:
      - acls.json
      - config.yaml
resources:
  - ../../../.kustomize-config
  - helm-release.yaml
  # - internal-net-router-auth.yaml
  # - internal-net-router.yaml
  - noise-privkey.yaml
  - postgres.yaml
  - tofu.yaml
