apiVersion: v1
kind: Secret
metadata:
    name: noise-privkey
    namespace: headscale
stringData:
    noise_private.key: ENC[AES256_GCM,data:dhGpA02y66B0HmUkpFvBlQHq159ILEVBilZgglpuxqzIDadEW2UFJI5gBevdnxRwelocIf5XmvVkyGxqBvuflNpBiYXbtDDm,iv:bFOYPklzaYbfpCp3ox15rnIgIyWg0h+L5d6oIFQlHMA=,tag:3c67ScJdU1ITjJjPU2vbfA==,type:str]
sops:
    age:
        - recipient: age15v9ufl7p4vd2f67xsx5tstkmhzdrqgfj5408p9e3s7dyyc8mnacq44hkk9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWWkMxRHpkVzkxVTE0Yjdi
            SjdDREFyeXZXK0U5bmQ5L0dpeHFZR0tsRnlrCkFLUXFibWVBR0x3WGg5Mlp0aEhh
            c2xmZXdWbWNEREMzRk9XTC9BNjF1eE0KLS0tIHV6TUVFeWgxeHZPUDA5QmR5QzBz
            RTNBRUlabDhwOUlJWXlSMFF1YnROc1UKxXHXw9NHu/JFJy4J59wWvkXfMbNMsrjy
            HMLHYHuISV8UPaKC0GhdEAj2qrR8LxuE0SWB3ECyJdUB6FCMZGDV7w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFwawprQXEkGl38Q7T0PNseL0vpoyr4TbATMkEaZJTWQ
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IEw2V0lpQSB5bTZr
            Tm9KbStKMDdWSFJlb1o1R2kvbThsMXFucTdMbGQ5aUxLNEZJVG5RClowMWhheVI3
            Q0ZJWVo2MWNVbkF0U1hyNmlYeWl0TFIxMVhrT1JhV2RnekkKLS0tIERlQzhYdVNE
            eGxEUTdnaHBuZE9NamRnVDlhKzEvb0o4UlpPQ2p3OVNCMlUKs4/xxpYJDYmV7ypZ
            1N2/eM7V0+qkJueFMlZHpOfRmGHnMWKbawqkh23rWmFA4T7VZTMfDz6rHrcQWuLf
            48pmrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-07T19:42:02Z"
    mac: ENC[AES256_GCM,data:WEIC4UFXvqfxsZdnis6upQmLABR+A/4kAwKcbb3Lwtf27nCaQCAICyGWlgmbaZ3eeVFpxbhyaBRnmhA3XwAww3vVsHsTu9YDvJB8/B66QOZ2cHMVbOr5HAsiES3+3Jj0wYJ86FPOFhHev4pxDH/ehg5S4iawSZ3wVL+HRYX/vvY=,iv:Q/+8oMBhUQGdGOzBz/7aPnFyJSOfp5H/7jnzFcoeLYg=,tag:ArK/fD/zrWMX3bplcAnXqw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
