apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: subnet-router
  namespace: headscale
spec:
  replicas: 2
  selector:
    matchLabels:
      app: subnet-router
  template:
    metadata:
      labels:
        app: subnet-router
    spec:
      serviceAccountName: subnet-router
      containers:
        - name: tailscale
          # NOTE: don't upgrade past 1.84.3 until https://github.com/tailscale/tailscale/issues/16804 is resolved
          image: ghcr.io/tailscale/tailscale:v1.90.8
          env:
            - name: TS_EXTRA_ARGS
              value: --login-server=https://headscale.tail22d0a0.ts.net --accept-routes
            - name: TS_KUBE_SECRET
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: TS_DEBUG_FIREWALL_MODE
              value: auto
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: subnet-router-ts-auth
                  key: key
            - name: TS_ROUTES
              value: 10.0.2.0/24,10.0.1.0/24,172.30.0.0/16,172.31.0.0/16
          # livenessProbe:
          #   exec:
          #     command:
          #     - tailscale
          #     - ping
          #     - hub-cluster-router
          #   initialDelaySeconds: 1
          #   periodSeconds: 5
          securityContext:
            capabilities:
              add: [NET_ADMIN]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: subnet-router
  namespace: headscale
rules:
- apiGroups: [""]
  resources: [secrets]
  verbs: [create]
- apiGroups: [""]
  resourceNames: [subnet-router-0, subnet-router-1]
  resources: [secrets]
  verbs: [get, update, patch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: subnet-router
  namespace: headscale
subjects:
- kind: ServiceAccount
  name: subnet-router
roleRef:
  kind: Role
  name: subnet-router
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: subnet-router
  namespace: headscale
