apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
secretGenerator:
  - name: butane
    files:
      - base.bu
      - control-plane.bu
      - etcd.bu
      - tpm.bu
      - var.bu
    options:
      disableNameSuffixHash: true
