apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: etcdetcetc
rules:
  - apiGroups: ["etcdetcetc.samcday.com"]
    resources: ["etcdclusters", "etcdtenants"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["etcdetcetc.samcday.com"]
    resources: ["etcdclusters/status", "etcdtenants/status"]
    verbs: ["update"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get"]
  {{- if .Values.legacyClusterWideCoreWatches }}
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list", "watch"]
  {{- end }}
