{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: etcdetcetc
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: etcdetcetc
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: controller
{{- end }}
