apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: etcdetcetc
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "create", "patch", "delete"]
  - apiGroups: ["cert-manager.io"]
    resources: ["certificates"]
    verbs: ["get", "create", "patch", "delete"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    resourceNames:
      - {{ .Values.leaderElection.leaseName }}
    verbs: ["get", "update"]
