apiVersion: v1
kind: Secret
metadata:
    name: ignition-key
    namespace: kube-system
stringData:
    age.agekey: ENC[AES256_GCM,data:2TQs2slCbloJ5CqhGWyrHWfWqd3KIl0EIW+0FIl5awq0lmnRdYvYB2nbk7YHBPXhOuPPdoWS+AjD5HZEMPgnMQgf3sMpRZ5fB4vCo3PdpIWkhISkMrFQEbWfIWuvEJ0UUCYuk0uwlTinHwLr2N0ucev2/KoFiTcMiBFjxWIeEx74TLgF/vUmagK8yV9WYcWtldyv8lzcFSMhv3CK0mer62WC4x0IxXr0qTx1tu0BkTdj5Mg3R8mIT/bSWxc=,iv:m/JmRUPcGrewgrrdBq3rbdq2KZH+MjpsFTryHdgHPCQ=,tag:wajp0l6f73NpGxsMJW0BiQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jl2wrpps4htmzkfuz2rhtuactm45c5ph3dyu8pxul9nt2scsh4aq36rv56
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEaWZNWmpQckxtYXBCNmp3
            VWF2KzVGLzFRclVwdGttQ0lXaUlORFdLb0djCklIM3krQzNJc0RBUnBub1E4K09Y
            Nm9rNno4cTMrTXh5VUc5NmJjdWhXNVUKLS0tIFdlRkdIc1pvYWd5MUIydHU3VjlZ
            b0pGZnRlY1BDYks2MWM0Z05HL0VDbUEKNW8rX525J6+0l7PxJDl5aHGgBd7buTdw
            P12Wo+f6pm7jcTdFa1zqT/CM+NUny9uy4WRoFGO2LzgRGg8xnVk4KQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age127cqf4nc9f36nmsm25mm8lmjlxfh35s7w3hc33nl3ryzy7whp36qe6e2ca
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJM1A0ckZIVXpTM2NmaTNa
            VUxFQ3NEUmxEbHdDaUdZbzZjdE9oMC9tdURVCkpKQUNZYzZOaGc4aWdYUm4zSnlv
            akFDWVZkRzQ1OXIwMW1JVGxZS2pIbGsKLS0tIE5MQTFUQWtEZTlZVUlTMjUrYit2
            cGlLb0lYRWFmcVFtOUQrRnp2U09NT0UKyBKIVgf/g+Qa4RaYAAqC6uYIxBmnfR/G
            N4tp1RGen3TOZPqU8ibHYSRqqI1fW3D5MFij6SdTcM6r1npYUussUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-09T09:11:06Z"
    mac: ENC[AES256_GCM,data:PQ8AQdJlSwoC/xd534w6kObba0ENIKP8GJIlh10UsXWbhtwGLSJlB1Ou/QFlrCGImSRUwmHd+4gLqRRq32ulI9r4zSbhtfKV7iWBjSCf9qyE4xdf9cftgFM1QRM2Lq2zC5Z2RvEqKF78kDEvIDddWFVveLUPIcrc+H/TpIhqI24=,iv:Zsnx3LY0HWu3ZirwDWCfWP63zxE6pgvddNRqjePgpks=,tag:cEPXZ/4Rpt7J2wibQAOOkw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
