apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pixiecore
configMapGenerator:
  - name: api-scripts
    files:
      - api/boot-request.sh
      - api/generate-ignition.sh
      - api/nginx.conf
resources:
  - ../../../.kustomize-config
  - butane.yaml
  - pixiecore.yaml
  - rbac.yaml
