router bgp 64666
  bgp router-id 10.0.5.1
  neighbor cluster peer-group
  neighbor cluster remote-as 64666
  neighbor cluster soft-reconfiguration inbound
  bgp listen range 10.0.5.0/24 peer-group cluster
  address-family ipv4 unicast
    neighbor cluster route-server-client
  exit-address-family
