---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: heisenbridge
  namespace: heisenbridge
spec:
  chart:
    spec:
      chart: generic
      sourceRef:
        kind: HelmRepository
        name: community-tooling-charts
        namespace: flux-system
      version: 8.1.1
  interval: 1h
  values:
    # https://github.com/community-tooling/charts/blob/main/charts/generic/values.yaml
    additionalVolumeMounts:
      - name: registration
        mountPath: /config/heisenbridge.yaml
        subPath: heisenbridge.yaml
        readOnly: true
    additionalVolumes:
      - name: registration
        secret:
          secretName: registration
    args:
      - -c
      - /config/heisenbridge.yaml
      - http://conduit-generic.conduit.svc.cluster.hub.internal
    deploymentStrategy:
      type: Recreate
    image:
      repository: docker.io/hif1/heisenbridge
      tag: latest
    ingress:
      enabled: false
    livenessProbe:
      httpGet: ~
    ports:
      - name: http
        containerPort: 9898
    readinessProbe:
      httpGet: ~
    service:
      ports:
        - targetPort: http
          protocol: TCP
          name: http
          port: 9898
