apiVersion: v1
kind: Secret
metadata:
    name: registration
    namespace: heisenbridge
stringData:
    heisenbridge.yaml: ENC[AES256_GCM,data:g1gygc10EfKecyfhZcvoPTw+BhRYweunegtWxYuLFXdpfZ3fx78zJ3VQbOMWCw+DfOtnXm2RvA0TNbf4oPYJMWAvgR0lyEYlmt0Nw9VuJpL1XtgX4VG3ZhhnXSIC0zVJjdwVbcbpRIDgUm7eyRN+DzKipVsQ+qX5+94quHnqFgJr3D5I5M34u0kRk9trkOiwgA5OzBNIWGqSgEfaSXbTbl0Gcp08jb7qRRToaTc9wSNj+aYHGbweS89/63iWnszxvx7x/4cbz13fz3hJjvFScgBg2tlmyjiVe3wkxZYHfeLCxwrTziTrO3JsbzyoZm7RHi6ZlXplZCdLZRWtAJc4ZoWPMM1s/9OQPb2a4chZnPF3jWwjLB0sZcs8oZ/7oLTWnt1eNeRquyhyOtfmDkZh2lD7CZ7Xg1mw4iVxeF9Zgzna33Eq/7Tlm/nDIvP90dDeUM6cNJETx8UdLpCbeNkQkAedJmssF9ZS73yMEGEgpUJKXo/6Ut18kkopOpUL6I9qL38V2YuMLmAjgeEPFmNPGCnbI1gg2MFONChVWZgN92aht5VsoB5gdBGgAeg8csc=,iv:VT8zQkd2/eeCPjxaX5hU7GaC2UbRw6I7Q0utFrnm5O4=,tag:ocUTiZhbfoBkTfURjf3qkA==,type:str]
sops:
    age:
        - recipient: age1tu8l2llfk32g0c4mvklqazjkj977h9xwvx3ntwt2ucdert8sufgq2g8mgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQdzNlU0UvdjlHVktFQ29Y
            dlJ3ME1YQjFwc3JQZHhCNDJLRGhvaFV1MFdFCk8vMnp4WllRaUoxSU5kRzJXVmFs
            WkxrNmV2VEdaMTZVeExnZ2Z0Nk50dzgKLS0tIGxML1d6bEREZ3RRZEhoTU56Sno4
            TW54a1VqN1NaNldVY213U1RRUkttLzQKZAkXHawxDmcw3yrXYIk5Ac534Y47Lw7/
            iZEGRlJJyWC9OI4Z54MGGD2J/V+t2I1cqGHj+m3CRZnpe9Olz7407w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14taxy23wzym2r9jndzsq5h8dx2f5cj5vtusfet2ggjjepp8pkfdqf6mus0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvTjltcXd0cEswR1c1K0Jm
            T2NFdVRDSUxybVdRV0JIVk9BQWs1b1ArTUFNCkdPZW1rd2ZwWWJOa0hPN1ZBVkM5
            NklHMnB5MEs1QnpibzltV21qckluQkEKLS0tIEhySlp0RlV2ZklrNUZVRTBGSktN
            Ti9vS2JpczZtaGhGU2NhaUZnZmJhQ2sKwNiZMvrtKukLf5l1N5siWBxPDEj8UtWS
            WGERa52UdPDLOdrHDHrllhRod/KQuvXeQN64f14YuYV0aeDI6DFjHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-20T23:16:52Z"
    mac: ENC[AES256_GCM,data:AAOQXEG+bUbGJS50DfUp5EdrX1kZ/O8qndL4hstAwaTiIXofyK/5TwdyBwCqffYI0JDBpHN3shK96Y51+KuRuwDEvbq+Tln9rx6gOdxSX6JTvJSkiP1HYZpXqnuJnOk82hNiQCkH9G0dMOV3cs9JPIEfUVXO6UkAr5Z+7AHcHcw=,iv:h5v8m6VN2QHNUiEL92EVB/P8HiCksUN2fMQK7XQjcqE=,tag:chJ7+TLRQmY2T0NxLDdQDQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
