apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fedora-forge-runners
resources:
  - namespace.yaml
  - runner-config.yaml
  - runner-amd64.yaml
  - runner-mobility-amd64.yaml
  - runner-arm64.yaml
