apiVersion: v1
kind: Secret
metadata:
    name: fedora-forge-runner-config
type: Opaque
stringData:
    amd64-config.yaml: ENC[AES256_GCM,data:GMBKukUqgIPCtxYC7Hu8ODpekbqVVniKxBImoz3uSQI8GiKWnniiI9d4wmw6l93lmt/9X9Se/Hzz9kQ3RWWp+1qxvjpvvYWhBARXwnBq7UMENljSjFYBM3u3lChDDiVZuPS/ifnI5wmVJ3vJfQ1kXYJpbUh7he85aS7Z0v8WnU5jlZanoGpBaVh6pUMTlVFNBU/BINyOY+PAHfIeOMHDnVQgpOpmGGHm34eyNtOr7Y5bBRbtzqQNV+3togsgfizK1MNXzQy/dcJ6l8nkuOf2PmTo6YGgv3buPR0W1qF4DFE2WqEIs2pVGVqazTsBB4FXRpbGrw303zght5dE3iEF02reWwsLxurXO6CzPLMsougmbynWsAjJ1i7BHd7TKa0sPDlN13pI30T+AkHwFQhorWEE0fFfbHkAY49C0F0q93ijDUIdt7SwzBRekMcN6GROuByf7Ppbe6OvV2ysp4vZtwrWqZI5xMn7YHkWx874/hiDx0JsyuSge3HxDUh8L7uqZw223ljFvhkgF3ZFiSsy8M4YUWAwJYDnPzsTzJiz0Jtj18mbe7CYse7Qtup8X5Cw7fOzsp+gxVt6a4/Ei/MaLDwBuforpaG+DwTC3uC7L9G8MSKfh3eD36gJRZ7rB9ZUaLKE6xx9B6Y5f3rWkFyUXrsJLEwmvGztIKVRyKd+MHd5SvZTkiG/25cX20XFd4m/MO3/bcbIu07erVH0Zb4ql8qazfqS8Oyxal9BcC8Gr4EbpcFMjD3ub1Yu4ZQ/oSHLn2oy0zw=,iv:iCp0vd7XRxx4qGhvcL7aSeA20N9Qr9t8DQ7063bym1c=,tag:w0RvU5ZeB/2tmRA/IMATdg==,type:str]
    arm64-config.yaml: ENC[AES256_GCM,data:B0LMmacBOQel3hKe2IFv+M2Q9d9BBoRcbbmaxQ+eQPlJPU4o+Ret8ELZZgPlJg2i26ylqI1erHm+3rWZwOGoxeJAV2uEnYEgmdvE1hz/3VPhE4Nh4jlnlEQyutDKnXobN3VYlTjo8Y6qptg4jGR0uFyeDdV0jPX6q/n6eckiuvZLLAOkmo9H7tIzEy4sMJRvw8klLvFDgc/cKYRg/tlT1Y4QPay2DUrkGxDJ0+8WRvHWlZ46cpkKLJLZUga3Ljek3zIAoKdpdgGy1NHH+78J9dmfE1kU/NXBgpZgtzVcgGSh41TnElQf9NP/aePDGEvSfOMzlUZJbxZFW6I6a9xceO0QFbIF23DEEE86CaYejVorenL5NhLl2lqsAIpW9wFaXT6cnNSCLjSGlWeyRw7lVCPHieWDbZiraI0IbPO+AEWr7clSXlfKHW9iEqlab/0ak7/u+gaBJky86v+PPPMgrGkk/HxXpZfLzobLvXuvgIAEZ4/7fx7pFd5ZCzLttif4T2mIriQt588II8XPT73j2SEWqjKeewP5/87NbdrihPLAgaKx+6NduFiqf1AZz+GJ1dHoc1ULNg7XbJMKSmAJtAH2pN54P3gc2K/hprKg2ZJJ/PSsXgGrwC7pIXIJfO3bKixY/44RbkQ4aPsk9xtVS0/pUXl52o/zfGTVnlLBP/e1mwlAav1FHv5Hdcv6b8A0zmQCvjRMU6D4+f7ouUBQ1rwTvSoEZbTzBLt7sHA98HmOo6SsdF8Z/jA2YUQgb1yr3TF2n3E=,iv:vYwVOPNcsG8womnfTkRqkTsBMNz3cQRUxqV0wGq6DFk=,tag:npgEjI6af/V7d0O8zDllXA==,type:str]
sops:
    age:
        - recipient: age1tu8l2llfk32g0c4mvklqazjkj977h9xwvx3ntwt2ucdert8sufgq2g8mgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZmN0SGtqZTlpTmVodXFl
            WmR4VHNkNjZod2cxbTZvQVNuemdUU2dycEZjCkxSUVd1aElrWHF2bVNjdnJsU1Bm
            Z0s1QUFBUkFteEFQNkhVUXJ6VmM0eW8KLS0tIGlWK3pkbEl3Y3lKSGxxcFM1elMx
            bEZraERuWWtLTVlaclV6aVY5QWRHRFEK7izTfeELKqvTZH/X05hW4a6aqJUArmmO
            qkTPeAcZgXOT8rR8X5H9ugbwKMS6ruXPt2t1TP2oEP00QWfqjjNcUg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14taxy23wzym2r9jndzsq5h8dx2f5cj5vtusfet2ggjjepp8pkfdqf6mus0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUSFhoWWl1WGlna3hpa0ZC
            akFCWXQ4eW9hYloxKyt5d1U1NVc2bTcwQWhJCnhBMXB1N0htVXlwYjJ4K3U1MTMr
            Y2hQVllUUGtCejBZMXVFWHo3ZTJnZ0kKLS0tIEZjTUhuSDE1Tmt0WVp6Q1pzVG5q
            dURlYmx6bXBjaW5NMTV2ZlIzcGtzWm8KXcninJ6WwiEyNBX4vAHYpfa1M5V1F5aW
            VAojLZUmoUIOeABs47sPeUIPHSygb6cpRf8bituDWoxzvfN0EOdP3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-06T06:56:47Z"
    mac: ENC[AES256_GCM,data:4xcEQl9WQtlEer5rZ3gLbqdMKNGqOz5CV8JzCJAED5LCCto+qfemNTF+uEVBPp00J6ZqoGjcEj+mcIkRXdCEK/WKaRQXU4tIYTyfBHCHWxK2x7V1Ms/m3maj8cxEeOBdi2gkLysiWXwd1vtYxSeQIdRwnzyZ1DxkQYhGUB072nc=,iv:uSX6Gj+gMm+6t5y0OH1jzS4W/xfJz4DnpcKR6AiPox4=,tag:ScmnDwIYAptDERPJlYO4rQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
