config:
  imagesForArch:
    arm64: ubuntu-22.04
    amd64: ubuntu-22.04
  nodeConfigs:
    cx23:
      cloudInit: |
        #!/bin/bash
        set -uexo pipefail
        cat > /etc/apt/sources.list <<HERE
        deb http://archive.ubuntu.com/ubuntu jammy main restricted universe multiverse
        deb http://archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse
        deb http://archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse
        deb http://security.ubuntu.com/ubuntu jammy-security main restricted universe multiverse
        HERE
        export DEBIAN_FRONTEND=noninteractive
        curl -fsSL https://tailscale.com/install.sh | sh
        tailscale up --accept-routes --login-server=https://headscale.tail22d0a0.ts.net --auth-key={{ $.Values.tsAuthKey }}
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.35/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.35/deb/ /' | tee /etc/apt/sources.list.d/kubernetes.list
        apt-get update
        apt install -y containerd kubelet kubeadm kubectl
        cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
        net.ipv4.ip_forward = 1
        EOF
        sudo sysctl --system
        systemctl enable containerd.service kubelet.service
        echo 'KUBELET_EXTRA_ARGS="--cloud-provider=external"' > /etc/default/kubelet
        mkdir -p /etc/containerd
        containerd config default | sed 's/SystemdCgroup = false/SystemdCgroup = true/' > /etc/containerd/config.toml
        systemctl restart containerd.service
        kubeadm join cloud-cluster-apiserver.tailnet.hub.samcday.com:6443 --token {{ $.Values.token.id }}.{{ $.Values.token.secret }} --discovery-token-ca-cert-hash sha256:{{ $.Values.hash }}
    cax11:
      cloudInit: |
        #!/bin/bash
        set -uexo pipefail
        cat > /etc/apt/sources.list <<HERE
        deb http://ports.ubuntu.com/ubuntu-ports jammy main restricted universe multiverse
        deb http://ports.ubuntu.com/ubuntu-ports jammy-updates main restricted universe multiverse
        deb http://ports.ubuntu.com/ubuntu-ports jammy-backports main restricted universe multiverse
        deb http://ports.ubuntu.com/ubuntu-ports jammy-security main restricted universe multiverse
        HERE
        export DEBIAN_FRONTEND=noninteractive
        curl -fsSL https://tailscale.com/install.sh | sh
        tailscale up --accept-routes --login-server=https://headscale.tail22d0a0.ts.net --auth-key={{ $.Values.tsAuthKey }}
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.35/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.35/deb/ /' | tee /etc/apt/sources.list.d/kubernetes.list
        apt-get update
        apt install -y containerd kubelet kubeadm kubectl
        cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
        net.ipv4.ip_forward = 1
        EOF
        sudo sysctl --system
        systemctl enable containerd.service kubelet.service
        echo 'KUBELET_EXTRA_ARGS="--cloud-provider=external"' > /etc/default/kubelet
        mkdir -p /etc/containerd
        containerd config default | sed 's/SystemdCgroup = false/SystemdCgroup = true/' > /etc/containerd/config.toml
        systemctl restart containerd.service
        kubeadm join cloud-cluster-apiserver.tailnet.hub.samcday.com:6443 --token {{ $.Values.token.id }}.{{ $.Values.token.secret }} --discovery-token-ca-cert-hash sha256:{{ $.Values.hash }}
    edge-fsn1-cx23:
      cloudInit: |
        #!/bin/bash
        set -uexo pipefail
        cat > /etc/apt/sources.list <<HERE
        deb http://archive.ubuntu.com/ubuntu jammy main restricted universe multiverse
        deb http://archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse
        deb http://archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse
        deb http://security.ubuntu.com/ubuntu jammy-security main restricted universe multiverse
        HERE
        export DEBIAN_FRONTEND=noninteractive
        curl -fsSL https://tailscale.com/install.sh | sh
        tailscale up --accept-routes --login-server=https://headscale.tail22d0a0.ts.net --auth-key={{ $.Values.tsAuthKey }}
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.35/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.35/deb/ /' | tee /etc/apt/sources.list.d/kubernetes.list
        apt-get update
        apt install -y containerd kubelet kubeadm kubectl
        cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
        net.ipv4.ip_forward = 1
        EOF
        sudo sysctl --system
        systemctl enable containerd.service kubelet.service
        echo 'KUBELET_EXTRA_ARGS="--cloud-provider=external"' > /etc/default/kubelet
        mkdir -p /etc/containerd
        containerd config default | sed 's/SystemdCgroup = false/SystemdCgroup = true/' > /etc/containerd/config.toml
        systemctl restart containerd.service
        kubeadm join cloud-cluster-apiserver.tailnet.hub.samcday.com:6443 --token {{ $.Values.token.id }}.{{ $.Values.token.secret }} --discovery-token-ca-cert-hash sha256:{{ $.Values.hash }}
      labels:
        node-role.samcday.com/edge: "true"
        topology.kubernetes.io/region: hetzner-fsn1
        samcday.com/pool: edge-fsn1-cx23
      taints:
        - key: node-role.samcday.com/edge
          value: "true"
          effect: NoSchedule
    edge-hel1-cx23:
      cloudInit: |
        #!/bin/bash
        set -uexo pipefail
        cat > /etc/apt/sources.list <<HERE
        deb http://archive.ubuntu.com/ubuntu jammy main restricted universe multiverse
        deb http://archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse
        deb http://archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse
        deb http://security.ubuntu.com/ubuntu jammy-security main restricted universe multiverse
        HERE
        export DEBIAN_FRONTEND=noninteractive
        curl -fsSL https://tailscale.com/install.sh | sh
        tailscale up --accept-routes --login-server=https://headscale.tail22d0a0.ts.net --auth-key={{ $.Values.tsAuthKey }}
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.35/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.35/deb/ /' | tee /etc/apt/sources.list.d/kubernetes.list
        apt-get update
        apt install -y containerd kubelet kubeadm kubectl
        cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
        net.ipv4.ip_forward = 1
        EOF
        sudo sysctl --system
        systemctl enable containerd.service kubelet.service
        echo 'KUBELET_EXTRA_ARGS="--cloud-provider=external"' > /etc/default/kubelet
        mkdir -p /etc/containerd
        containerd config default | sed 's/SystemdCgroup = false/SystemdCgroup = true/' > /etc/containerd/config.toml
        systemctl restart containerd.service
        kubeadm join cloud-cluster-apiserver.tailnet.hub.samcday.com:6443 --token {{ $.Values.token.id }}.{{ $.Values.token.secret }} --discovery-token-ca-cert-hash sha256:{{ $.Values.hash }}
      labels:
        node-role.samcday.com/edge: "true"
        topology.kubernetes.io/region: hetzner-hel1
        samcday.com/pool: edge-hel1-cx23
      taints:
        - key: node-role.samcday.com/edge
          value: "true"
          effect: NoSchedule
token:
  id: ~
  secret: ~
tsAuthKey: ~
hash: ~
