apiVersion: v1
kind: Secret
metadata:
    name: fastboopmos-age-key
    namespace: cloud-cluster
stringData:
    age.agekey: ENC[AES256_GCM,data:AqTUoH+LSBxBMW7YxjGMHu9P7pA2UiCK19Klf3mwe9TF5l31ELyhHbjco5lRH76Pp9fCVJmRW0x68mW2k6w0AaaeBnJq3OsItI7Qir5xvQ/yaD/4ZPbLs1QqYVTT2wCJK2iA4EziVC412UKpM8De67+HOTQTEWpA7jFPloBlCvEgcyygNzJCFRFf+qt8+5U3Dlze9KEQkQw6cGgdh/0QhZFaxdB2XoJUVn1PmdU8bsRiQe4tVaPN/zfHbhN4,iv:72y/bxheYRi/+pa28Q6cIa9pPrhSBKa0Aj2sNs1VlQ0=,tag:2nRwtrPGgybT8d1IOkG3QQ==,type:str]
sops:
    age:
        - recipient: age15v9ufl7p4vd2f67xsx5tstkmhzdrqgfj5408p9e3s7dyyc8mnacq44hkk9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsL2hSTTFBMnRaM3pYUDE2
            NmJFVkxMdHIvSm5ldnBCMmQvZEs2OEQxMm5FCkNkbnE5MjQxYWorc2RlRllSTXI1
            RjNLcjRRTjdwanBKaHpWT0IwREw1b0EKLS0tIGxHT1R3SDVrNmlaa0RQMDRZSDB6
            NEc1UjBUMzVCd2xNR2JHUDFLL1RUaHMKUBDVQGOFwyxgPPSsAkw13/tPiUyCIkAb
            ylJBZvnbpDZXZdw+a1gt0X8UpUj5iNuVwyppR1cYTYlNwouTso9gPQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFwawprQXEkGl38Q7T0PNseL0vpoyr4TbATMkEaZJTWQ
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IEw2V0lpQSBEUUxS
            TGp1Zk4xVlpZME9kTWJUVHNCVTZtWTNWY25uWFBKb3lUNkUvbVhFCktPaE1WUnNm
            aldEbmtDVzBTMTI2SUszM1VxSVpjdFJtbE5IY1IzNFhPcXcKLS0tIGlndURqNzAz
            b3k1WHdUb2xWbE1DaDMyUDNZVHN5Z0l5SmhDMTZoeGNVencKqo5kXQ4EZ4nwfqwg
            s4POYtrEKqxu6yJwXb5uaoOyXkovsr6vHLZu5Cy1s6WBCGBntJT9sWprEuy7VZbe
            GZA8Pw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-07T19:45:03Z"
    mac: ENC[AES256_GCM,data:W9W8ApuoEuzAEuMR0dJ+phXR0d0W8KKMac4g5gndTGJrIjgHMRFs95gqWfTMOUT2JjqFOvgEbrW2dkDUUrEjZHR9lbDcLsu9Gw4HcRK7bM9/f0V+6G2QwssebiVW7GFhWdToa6WbMqXAFM9tOpPbbFH50Fxvqrz5pqgobjpKikA=,iv:lXKfGIRGWuub56IFUbXnuZa+Lnwc+5FOjr9LXLVpzy0=,tag:WLceZ9QIF2rhz3W7pTlu7g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
