apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: conduit
  namespace: monitoring
spec:
  groups:
    - name: Conduit
      rules:
        - alert: ConduitUnavailable
          expr: kube_deployment_status_replicas_available{namespace="conduit",deployment="conduit-generic"} < 1
          for: 10m
          annotations:
            summary: conduit/conduit-generic has no available replicas for more than ten minutes.
        - alert: ConduitIdentityCheckStale
          expr: time() - kube_cronjob_status_last_successful_time{namespace="conduit",cronjob="conduit-identity-check"} > 2700
          for: 10m
          annotations:
            summary: Conduit identity check CronJob has not succeeded in over forty-five minutes.
        - alert: ConduitPVCNotBound
          expr: max(kube_persistentvolumeclaim_status_phase{namespace="conduit",persistentvolumeclaim="conduit-generic",phase="Bound"}) < 1
          for: 10m
          annotations:
            summary: conduit/conduit-generic PVC is not Bound.
