apiVersion: v1
kind: Secret
metadata:
    name: dms-url
    namespace: monitoring
stringData:
    url: ENC[AES256_GCM,data:dyIsG2m/zXJBjCpIgi/cCMigou1t3zpFuKR1qw==,iv:tGHOt/0dhYAdFM/sy/JcxTmhWex2xdoZdLbjVGXDaAQ=,tag:cFK7hk781/TK442Kt2yfFA==,type:str]
sops:
    age:
        - recipient: age1r8tha72lm6j96pre8qrlxj2nyyzm9cq38umh9dcd2kf5hhjnqsfqe6saex
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOUjRvc1JwLzAzWTUwT3NE
            U2dSZksrcm5uRDJ5MUlpVk1iaDR3N3BmWjNBCjNiWDZoM3lIamMvOUgzNTJZaVMr
            NUFjZTBERWRYbWwyd2hITnk1aTRPcW8KLS0tIHpyRXpvYmpuMWZlejF4TDhCekRw
            RC80bmRaWnZTbEtERHBMdkZXODJpeUkKHeQWspbjm3AnN90dJX9zKo97sxg02KtU
            MojOIaOzWkupnFeChLys7we9Ye1JmCMxmLjs7HP4t2oZhFJdpyy4FQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14taxy23wzym2r9jndzsq5h8dx2f5cj5vtusfet2ggjjepp8pkfdqf6mus0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBERGFvalJtWTQ5Q1hWYmFh
            N0Mvem9kb3lkNXdSSG45MFpMQkwxOSszZWpRClJiWVl4REI3YTJ6dkxEd28vdUhU
            VHZCeXhjSlUwU2ZtMW5Dd3FQNHNWcncKLS0tIHhuWG0reXZuS2gwdUZlaFRnMS9h
            TlV6M2J3RWk0WU9uRTZBdTdBTTNPbVkKFW5mTUP3grWUx2eailkwHyz6lMclWqDI
            M0/IFjsr/h9Uyyv1wqLms7YsF+ZqYUlAuPwP+Ia5Yk2b2eA8Hk8bLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-25T06:53:55Z"
    mac: ENC[AES256_GCM,data:oIka/af/n0NZrgj4NksztscM4buitoa19L4RLKRe3lfYUF85EJk57RTazXdVETrWDose3mA3ae5Nnh/eYN9AN7e/q+UeTNlZDDW4YPxAYVmMZO8YcHouCVp8IaFMLTJin7AJ3KH/w29H6634OMMyKGtJHF/ZIvFKR/WnWj3x2hI=,iv:YhN7bjIZVz4K6XsmkMFRSaNdmwBZJQJriMu854tZ528=,tag:ExBTfh1aRmKivCTsun61hg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
