apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yaml
  - flux-podmonitor.yaml
  - dms.yaml
  - dms-secret.yaml
  - notification-check.yaml
  - pagerduty.yaml
  - pagerduty-secret.yaml
  - pagerduty-test.yaml
  - rules/
