apiVersion: v1
kind: Secret
metadata:
    name: pagerduty
    namespace: monitoring
stringData:
    integration-key: ENC[AES256_GCM,data:KLw4x8wEQDI2VWToam5vDbFCoz+p01Ypw29BUdKDl6U=,iv:ost/pVqiEvQXEPWJa/lAbL+duh3b64Xhsb5KuolvlJA=,tag:wlbD6STzlJQGTzB7+p+vpw==,type:str]
sops:
    age:
        - recipient: age1r8tha72lm6j96pre8qrlxj2nyyzm9cq38umh9dcd2kf5hhjnqsfqe6saex
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSGUycVhyQVFLWjJnTEZ5
            WUZPcUp5Tno5V2hjK1BNTWFZU2pnSjFQK2dVCnVIajBJNThSaTNqLzNWZWJoeHZT
            cVNWTWdEcHd4SUV2OFRlajhHU1owODAKLS0tIEg2QlFKc2UzT3RTeEhSZU9rTjls
            NEVkeEVnYVF2T0xEN2gyRnhDTnZ5aFkKjbfQT4TT22XYltqHdY2phD/KTTqr6dap
            wX9/ZoV7U5HF1qMj2u1G8uGhmH1dzZYFpg2v3gSCjZim62wO+bUmEg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14taxy23wzym2r9jndzsq5h8dx2f5cj5vtusfet2ggjjepp8pkfdqf6mus0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzYUo0aU41RmNQM2xwbTJP
            NDhXanFTR2k5eEVsTjhuazdqQXpvdzdlTURBCkJGNzEwSWlNU2RUWGVWY25aVDNx
            S0hldi93ODNmeTlTaDB2UFdtUW1lbmMKLS0tIGp1Ry9QSHdxOE9vVGJ0dStRODhO
            YkRzRWN1aEVrNzVDUUl4SU9nZExOcncKFXllyZPrES4sMNq9GY/xRTRPuo0U4YUD
            2IONjX2ktunnOPJ6D/F1dqndiCOzCxdVAPP/0YInkXolg3PCOlgrvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-22T07:21:26Z"
    mac: ENC[AES256_GCM,data:fR9H8Uwsy19v9aKQy+XNuZvcBsw0sbhzmdojud4MAjdIyKaY6Ox1KlkcInSnuzbudkPzIi40SROXFJ3lA+o4Z/p8a6FwxUsV0SU8ZNyjv3xmzTjIIn5FWwLEze/0N6fZ3L3Rq/qHHOVZYo0Kf0hOS3sZeffd2UxLzmIcTfHgetg=,iv:BJu52wkRSRm7YrgLsIkf89RVdHLP8896pqpbdaGPud4=,tag:R+iX0UOdkazgg5mVEVVgtQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
