apiVersion: v1
kind: Secret
metadata:
    name: dex-secrets
    namespace: dex
stringData:
    PASS_HASH: ENC[AES256_GCM,data:zJfYiXxFkgHuI94CEGrYApMM2OVsh3z4ZiMEk+KKxnMrKWlm08LMZSstWQPVXqEfdkDEvOENN0g0wTsT,iv:J+LJ95rL4SNDAn8tHb0AQVgopRi/Bkm3PIMmGZwjdCs=,tag:OROZ7GLWis9qMrRFzeseEA==,type:str]
    TS_SECRET: ENC[AES256_GCM,data:j/5oefqkWgHaBf88XiAJj5IBQaeopT3agv/00BKTanKszGiJuhpalg==,iv:xsh5tnC/2EjIawdCJBuhKJnEmR1xHH3E5yYkE+cV7D8=,tag:YDIMjM4JoaWU6bBxKBWbpQ==,type:str]
sops:
    age:
        - recipient: age15v9ufl7p4vd2f67xsx5tstkmhzdrqgfj5408p9e3s7dyyc8mnacq44hkk9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4cm9ZYXl0b0NtK2tNaFVh
            R04yK20yOFRJd2NwS0tWS2ZkWjY0bm4xL3lrCnV5OXJuSi9wR1lNcnU2bUorNUM5
            a3RvOE5TOFg4Nk51dzNLZVR4QVhQcEEKLS0tIDJWb1IrZHNqazZBdHllTEJvSy9I
            bDRlM1NpYUdNd055SE11WUFqZktMMEEKqvemwElhg4VkTidfmhYTV9wZLw3ZAH20
            g3nwesX4RjoT7wry4IL5PqUfLWo5EVQi5ekUTn+NSRYoRpzdcigO9Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFwawprQXEkGl38Q7T0PNseL0vpoyr4TbATMkEaZJTWQ
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IEw2V0lpQSBrR3gx
            Mnh1UWJkcVp0QWNFajVSKzRaUXEycVFjNU1rTHdMcnVhNDJtbWlRCkY1SU81ejZy
            dTJpeHBTS2tSeWZKa0VnaGsybFhIMHpuemtVazV2Q3NGV1kKLS0tIGZGbmNaeW5q
            RXZJcXdEOHQvMTZTTG04V0RXWGRoZWx1bGNmaG9NaUFYWTAKhnOjxkAgkHhzz+3R
            4h7FPcGT5xewbgZ8bOQqokUyQuPOQsz0LKhukdbgNJ40+M1yp0aZ/U4vymBJff4x
            80mcdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-07T19:27:04Z"
    mac: ENC[AES256_GCM,data:J6j+y784P9H917Oj5azX9gZZF8862RIJCbhI+L41hw/bIWsRoWC+iFROWMx0cnkUj/CjDPxNdQ9DUzK8fR8m3U69KbLdRXuD1xnbT1HOtfdG0ix6F1uH6hsK3mEeAe51aR6WEggq0OLICfW6MW3l7Vvw3SA0cEbzsosqdXzVHgQ=,iv:Hp8t/UNKkIWD7w00vftmrVM9aQN0Zr6hJpq6mzE9R1M=,tag:dB5wJgM+Z0iJ9uP9I+vGXw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
