apiVersion: v1
kind: Secret
metadata:
    name: dex-forgejo
    namespace: dex
stringData:
    FORGEJO_SECRET: ENC[AES256_GCM,data:IBD+pNjegF0JFb6+4LCdJtc/AiyBsiqWlDMiVyHcoDnBrRE1G+9Xd4zWGOAZOeODdrX/+Jef/541ooT+PDPQ2w==,iv:YiUbGN1vWCmy3A+3RuzHGMSC/8XSu95zfCs7i/5QrLc=,tag:n0rw5GQaq8m5usasEFljaA==,type:str]
sops:
    age:
        - recipient: age15v9ufl7p4vd2f67xsx5tstkmhzdrqgfj5408p9e3s7dyyc8mnacq44hkk9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzMWQ4VnhRQlRZMjlNT0d1
            NUVvQWh6TGhHZUphSWRwWkdsZWVJdENsalFnCmlVeW1YTURnWERKcVc0WUZCeHI0
            UzlIU3lCU0p0K3NsSTcvVUM0Y2hKTGMKLS0tIGRJcnBVbVRzVjBrNldPdldEdzVn
            KzEzVGlOcWc2MXBaK2ZUcm9oTWk4NkEKTXbyqJhrErl5xzSjZpCucYktwBKLiBwR
            we9/a6UXTx2677AubREyNyu4RTVr6BIMEAH/5HN2/PVopttUNosIhw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFwawprQXEkGl38Q7T0PNseL0vpoyr4TbATMkEaZJTWQ
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IEw2V0lpQSB6Umpk
            RGxESzFOVXc3VUwyUWp0OTZ6QlRVWGwxci9UVU94L3BvbFZvY1MwClk1bnRFK1FB
            WHBZNzlONzJOL0drYWs1ZWFkT2JweDdBSTdnaXFXanJxSXcKLS0tIGZZOVJkZ1Vt
            QVB5U2hkYllnMjRzZTlTR0srRVI5QmJzWFZnZVlMQmtIR1kK9htpVZpZZy6k+KyI
            CtEQkDFGChv6u+gsDjGB0gkvJHBzPsjl3KJrJ76ijXP/doNC6I/baGFadYTUaFKJ
            Uc8jgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-07T19:27:04Z"
    mac: ENC[AES256_GCM,data:D93rzP6JVgyd8I4SBbyU5lWpqWp2FP0c62JBAjTPrlnnkyXuVnb+lj+f6m5WoLb1l3L0Rj83QwFwiYOX9UcAQHlVwfwlKJzmq72eekcXaBms7ZlRcyPEADXcg1CTVdv0Z3wVyGXVtB6jQPyoZjbK6QJeruUjJ/Cv2x2NbaPA5Z4=,iv:hpCL6Bq/ULiE5YUhg6Fx2n2cUFyA2xYJBcxV1VUC0FI=,tag:JlwyWQLUXAl8n/n0HbvOYA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
