apiVersion: v1
kind: Secret
metadata:
    name: dex-secrets
    namespace: dex
stringData:
    PASS_HASH: ENC[AES256_GCM,data:AjjjQ/b/eGaj8BPT2pTPoeNqRXnBwX4sF4mKn2we3Co4JPQX+aOLc/rGK7RT04yd2/kQERwUWl554qlg,iv:IPpuqBBm41Um/9FgOrWurTH/1bwv2275+yBXeW2s+8E=,tag:k0BENVdfvrp3cCXZuilw8g==,type:str]
    TS_SECRET: ENC[AES256_GCM,data:ZoFtPSnhWKYbPpFprEzHg6+/R0cFfrSBWEcv8xZ2dsV4nonBQT0yTQ==,iv:WnvlvYNDeI/AO/9F5co+WpAe1/njUIddkugvKy1Az8U=,tag:v/tzESwF6arzoWThph0WTQ==,type:str]
    FRIEND_PASS_HASH: ENC[AES256_GCM,data:B9izKA410vAxZvq4/So5nBzS0Fca6lif8gkA6TWalikUBtXRsiqqr/VUI6xtGg3gPfhsDn65kT3gXLaJ,iv:d8p2NxyqDO7yJVVew9rMjNPhL0Lp9c+GuECOGOBXO7U=,tag:XfOaCEJXifdIvcj0F0Q5jg==,type:str]
sops:
    age:
        - recipient: age1tu8l2llfk32g0c4mvklqazjkj977h9xwvx3ntwt2ucdert8sufgq2g8mgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIMVZLZnlzcDAzSmc2UjlH
            TjI0YmM5VXJ1MG1obTVnQ2x5cmFpUW1ITjJRCjdYcVJZNG9TQXROVGVIOTQ3NUJQ
            QVdseEs0MEQzcm1zMVRzZ1dsSzFWV0kKLS0tIC93amxNZktEc3RqYzh2VWtrSzFD
            eHIzMGQ0VEtieEFaZGZqR3dYcjZXVjgKKlzfvH4OIms6BkCVPmtZcY7IvfwEW5/x
            mheT5doT0u2zZ/NXWWoGE02O5/T0yTIIUCUXsz2+VzhRdJY9AMGzMw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14taxy23wzym2r9jndzsq5h8dx2f5cj5vtusfet2ggjjepp8pkfdqf6mus0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyODRyS093dXorMUhoRHQ2
            ZE1BMy96M2t0bk5GSjFBMmJreFZhcUxRVEZFCjdTUzhNRi9uSEZ0dVlyOVVHSU8z
            azgyOTJxSWo5N3B3MitleWpadzdOOTQKLS0tIHdNUnFSRVptRUNvdHdpMVBIdHpw
            ZEJoblhBYjZQMXljcGFLTFJHWk5uUncKH9tnnbi8Uts/45VWzNIZd1yTjVnN4drO
            r5PkyLTNbAxfH62v0Aq3xMNII+4hiKo/+YcUHEpnNcq9yv5y4hdZRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T03:49:12Z"
    mac: ENC[AES256_GCM,data:vw+GiwfocmvYItFVjtk5egJBliKu3BN8okE3Sz36XBVIZpJhdPf04afh1mhmjt7LmxoGk0cLeZW8n+AjAFyQpwN75sLQfEAGvUewGsn3QPboRXZIbTkPr8KZgst1cv1rqo+GE4ldFlUV9htyQNahldq01JzBdrsjK0q3TZ93dWI=,iv:7TbaBQ4HMfqNOs4Dc5yNLhrc0mPaJP29tnx2SYZtnvs=,tag:baA8dl6iREITZ4K+IRWmXQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
