apiVersion: v1
kind: Secret
metadata:
    name: dex-secrets
    namespace: dex
stringData:
    PASS_HASH: ENC[AES256_GCM,data:GDsPBElXlcb2wqeFsOg5ribCqT0KfC5FXp1t1f7g2mll1V5vSwD6SpV+BmjW4Sw//8StuCDKSUqZK5lj,iv:ilndROyo6CETdddKeSXg7CQJUZV0Nk+4ylsfNIxUFHI=,tag:+AXNSscAfZsFFeul0BdA5Q==,type:str]
    TS_SECRET: ENC[AES256_GCM,data:ZoFtPSnhWKYbPpFprEzHg6+/R0cFfrSBWEcv8xZ2dsV4nonBQT0yTQ==,iv:WnvlvYNDeI/AO/9F5co+WpAe1/njUIddkugvKy1Az8U=,tag:v/tzESwF6arzoWThph0WTQ==,type:str]
    FRIEND_PASS_HASH: ENC[AES256_GCM,data:B9izKA410vAxZvq4/So5nBzS0Fca6lif8gkA6TWalikUBtXRsiqqr/VUI6xtGg3gPfhsDn65kT3gXLaJ,iv:d8p2NxyqDO7yJVVew9rMjNPhL0Lp9c+GuECOGOBXO7U=,tag:XfOaCEJXifdIvcj0F0Q5jg==,type:str]
sops:
    age:
        - recipient: age1tu8l2llfk32g0c4mvklqazjkj977h9xwvx3ntwt2ucdert8sufgq2g8mgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIMVZLZnlzcDAzSmc2UjlH
            TjI0YmM5VXJ1MG1obTVnQ2x5cmFpUW1ITjJRCjdYcVJZNG9TQXROVGVIOTQ3NUJQ
            QVdseEs0MEQzcm1zMVRzZ1dsSzFWV0kKLS0tIC93amxNZktEc3RqYzh2VWtrSzFD
            eHIzMGQ0VEtieEFaZGZqR3dYcjZXVjgKKlzfvH4OIms6BkCVPmtZcY7IvfwEW5/x
            mheT5doT0u2zZ/NXWWoGE02O5/T0yTIIUCUXsz2+VzhRdJY9AMGzMw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14taxy23wzym2r9jndzsq5h8dx2f5cj5vtusfet2ggjjepp8pkfdqf6mus0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyODRyS093dXorMUhoRHQ2
            ZE1BMy96M2t0bk5GSjFBMmJreFZhcUxRVEZFCjdTUzhNRi9uSEZ0dVlyOVVHSU8z
            azgyOTJxSWo5N3B3MitleWpadzdOOTQKLS0tIHdNUnFSRVptRUNvdHdpMVBIdHpw
            ZEJoblhBYjZQMXljcGFLTFJHWk5uUncKH9tnnbi8Uts/45VWzNIZd1yTjVnN4drO
            r5PkyLTNbAxfH62v0Aq3xMNII+4hiKo/+YcUHEpnNcq9yv5y4hdZRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T03:41:28Z"
    mac: ENC[AES256_GCM,data:57jB4SaRil7QohbPS70CWJYlCnrx6AJvgUQGIKgBAUYIXJAzMMVFpFuTed4sdoV92yn19cXe4RHN/1D4Uwlh/ADJBFtJ7F0q8I0AALPo+Bv+X99M+H/p7bEGka1GO2UD6ZHfu1sAMO+EfJuv4VTj+kv+UqSq5Ypq+SO0XS/HM84=,iv:E3HZMy0JUnZz/5qcgybzQ6swHzHULlizCZd4EbyZz2E=,tag:Ve76d/BZruZskkpYXtT5PA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
