---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: litestream
  namespace: conduit
spec:
  generateBucketName: conduit-litestream-
  storageClassName: ceph-bucket

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: conduit
  namespace: conduit
spec:
  chart:
    spec:
      chart: generic
      sourceRef:
        kind: HelmRepository
        name: community-tooling-charts
        namespace: flux-system
      version: 8.1.1
  interval: 1h
  values:
    # https://github.com/community-tooling/charts/blob/main/charts/generic/values.yaml
    additionalContainers:
      - name: litestream
        image: docker.io/litestream/litestream:latest
        args:
          - replicate
          - -config
          - /etc/litestream.yml
        envFrom:
          - secretRef:
              name: litestream
          - configMapRef:
              name: litestream
        volumeMounts:
          - name: data
            mountPath: /var/lib/matrix-conduit
          - name: configmap
            mountPath: /etc/litestream.yml
            subPath: litestream.yml
            readOnly: true
    configMap:
      enabled: true
      data:
        conduit.toml: |-
          [global]
          server_name = "samcday.com"
          database_backend = "sqlite"
          database_path = "/var/lib/matrix-conduit/"
          address = "0.0.0.0"
          port = 6167
          allow_encryption = true
          allow_federation = true
          allow_registration = false
          trusted_servers = ["matrix.org"]
        litestream.yml: |-
          dbs:
            - path: /var/lib/matrix-conduit/conduit.db
              restore-if-db-not-exists: true
              replica:
                url: s3://${BUCKET_NAME}/conduit.db?endpoint=http://${BUCKET_HOST}:${BUCKET_PORT}&region=${BUCKET_REGION}&force-path-style=true
      mountFiles:
        - subPath: conduit.toml
          mountPath: /etc/conduit/conduit.toml
        - subPath: litestream.yml
          mountPath: /etc/litestream.yml
    deploymentStrategy:
      type: Recreate
    env:
      CONDUIT_CONFIG: /etc/conduit/conduit.toml
    image:
      repository: docker.io/matrixconduit/matrix-conduit
      tag: latest
    ingress:
      enabled: false
    initContainers:
      - name: litestream-restore
        image: docker.io/litestream/litestream:latest
        command:
          - /bin/sh
          - -ec
        args:
          - >-
            litestream restore
            -if-db-not-exists
            -if-replica-exists
            -config /etc/litestream.yml
            /var/lib/matrix-conduit/conduit.db
        envFrom:
          - secretRef:
              name: litestream
          - configMapRef:
              name: litestream
        volumeMounts:
          - name: data
            mountPath: /var/lib/matrix-conduit
          - name: configmap
            mountPath: /etc/litestream.yml
            subPath: litestream.yml
            readOnly: true
    livenessProbe:
      httpGet:
        path: /_matrix/client/versions
        port: http
    persistence:
      enabled: true
      mountPath: /var/lib/matrix-conduit
      storage: 20Gi
      accessMode: ReadWriteOnce
      storageClassName: ceph-block
    ports:
      - name: http
        containerPort: 6167
    readinessProbe:
      httpGet:
        path: /_matrix/client/versions
        port: http
    service:
      ports:
        - targetPort: http
          protocol: TCP
          name: http
          port: 80

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: conduit
  namespace: conduit
  annotations:
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  hostnames:
    - matrix.samcday.com
  parentRefs:
    - name: public
      namespace: ingress-nginx
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: conduit-generic
          port: 80
