apiVersion: apps/v1
kind: Deployment
metadata:
  name: bootie
  namespace: ilumbaclusta
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      name: bootie
  template:
    metadata:
      labels:
        name: bootie
    spec:
      initContainers:
      - name: butane
        image: ghcr.io/samcday/infra-bootie:2025082805 # {"$imagepolicy": "flux-system:bootie"}
        command:
        - ash
        - -uexo
        - pipefail
        - -c
        - |
          for f in /butane/*.yaml; do
            name=$(basename $f)
            butane --strict < $f > /ignition/${name/.yaml}.ign
          done
        volumeMounts:
        - name: butane
          mountPath: /butane
        - name: ignition
          mountPath: /ignition
      containers:
      - name: bootie
        image: ghcr.io/samcday/infra-bootie:2025082805 # {"$imagepolicy": "flux-system:bootie"}
        env:
        - name: FCOS_VERSION
          value: 42.20250721.3.0
        - name: FCOS_BASE
          value: http://10.0.3.1/static
        - name: KUBECONFIG
          value: /kubeconfig
        ports:
        - name: http
          containerPort: 80
        livenessProbe:
          initialDelaySeconds: 5
          httpGet:
            path: /
            port: 80
        resources:
        volumeMounts:
        - name: admin-kubeconfig
          mountPath: /kubeconfig
          subPath: value
        - name: ignition
          mountPath: /ignition
      volumes:
      - name: admin-kubeconfig
        secret:
          secretName: admin-kubeconfig
      - name: butane
        secret:
          secretName: butane
      - name: ignition
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: bootie
  namespace: bootie
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ilumbaclusta-bootie-hub.samcday.com
spec:
  loadBalancerClass: io.cilium/bgp-control-plane
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    name: bootie
  type: LoadBalancer
