apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ilumbaclusta
configMapGenerator:
  - name: control-plane-values
    files:
      - values.yaml=control-plane-values.yaml
resources:
  - ../../../.kustomize-config
  - bootie.yaml
  - cilium.yaml
  - control-plane.yaml
  - coredns.yaml
  - node-bootstrap-token.yaml
  - vpas.yaml
