apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: subnet-router
spec:
  replicas: 2
  selector:
    matchLabels:
      app: subnet-router
  template:
    metadata:
      labels:
        app: subnet-router
    spec:
      serviceAccountName: subnet-router
      containers:
        - name: tailscale
          # NOTE: don't upgrade past 1.84.3 until https://github.com/tailscale/tailscale/issues/16804 is resolved
          image: ghcr.io/tailscale/tailscale:v1.84.3
          env:
            - name: TS_EXTRA_ARGS
              value: --login-server={{ $.Values.loginServer }} --accept-routes
            - name: TS_KUBE_SECRET
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: TS_DEBUG_FIREWALL_MODE
              value: auto
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: subnet-router-ts-auth
                  key: key
            - name: TS_ROUTES
              value: {{ $.Values.routes | join "," }}
          securityContext:
            capabilities:
              add: [NET_ADMIN]
