apiVersion: apps/v1
kind: Deployment
metadata:
  name: bootie
  namespace: simonet
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      name: bootie
  template:
    metadata:
      annotations:
        reloader.stakater.com/auto: "true"
      labels:
        name: bootie
    spec:
      initContainers:
      - name: butane
        image: ghcr.io/samcday/infra-bootie:2025091700 # {"$imagepolicy": "flux-system:bootie"}
        command:
        - ash
        - -uexo
        - pipefail
        - -c
        - |
          cat > /secrets/kubeadm.join <<HERE
          apiVersion: kubeadm.k8s.io/v1beta3
          kind: JoinConfiguration
          discovery:
            bootstrapToken:
              token: $(cat /token/id).$(cat /token/secret)
              apiServerEndpoint: simonet.hub.samcday.com
              caCertHashes: [$(cat /ca-hash)]
          HERE
          butane -d /secrets --strict <<HERE > /ignition/secrets.ign
          variant: fcos
          version: 1.5.0
          storage:
            files:
              - path: /etc/ts-authkey
                mode: 0600
                contents:
                  local: ts-authkey
              - path: /etc/kubeadm.join
                mode: 0600
                contents:
                  local: kubeadm.join
          HERE
          mkdir /ignition/common
          for f in /butane/common/*.yaml; do
            name=$(basename $f)
            butane --strict < $f > /ignition/common/${name/.yaml}.ign
          done
          for f in /butane/*.yaml; do
            name=$(basename $f)
            butane -d /ignition --strict < $f > /ignition/${name/.yaml}.ign
          done
        volumeMounts:
        - name: butane
          mountPath: /butane
        - name: butane-common
          mountPath: /butane/common
        - name: ca-hash
          mountPath: /ca-hash
          subPath: hash
        - name: ignition
          mountPath: /ignition
        - name: node-ts-auth
          mountPath: /secrets/ts-authkey
          subPath: key
        - name: node-bootstrap-token
          mountPath: /token
      containers:
      - name: bootie
        image: ghcr.io/samcday/infra-bootie:2025091700 # {"$imagepolicy": "flux-system:bootie"}
        env:
        - name: EXTRA_BASE_CONFIGS
          value: secrets ssh-hostkeys
        - name: FCOS_VERSION
          value: "42.20250818.3.0"
        - name: FCOS_BASE
          value: http://10.0.5.1/static
        - name: KUBECONFIG
          value: /kubeconfig
        ports:
        - name: http
          containerPort: 80
        livenessProbe:
          initialDelaySeconds: 5
          httpGet:
            path: /
            port: 80
        resources:
        volumeMounts:
        - name: admin-kubeconfig
          mountPath: /kubeconfig
          subPath: value
        - name: ignition
          mountPath: /ignition
      volumes:
      - name: admin-kubeconfig
        secret:
          secretName: admin-kubeconfig
      - name: butane
        secret:
          secretName: butane
      - name: butane-common
        secret:
          secretName: butane-common
      - name: ca-hash
        configMap:
          name: ca-hash
      - name: ignition
        emptyDir: {}
      - name: node-bootstrap-token
        secret:
          secretName: node-bootstrap-token
      - name: node-ts-auth
        secret:
          secretName: node-ts-auth
---
apiVersion: v1
kind: Service
metadata:
  name: bootie
  namespace: bootie
  annotations:
    external-dns.alpha.kubernetes.io/hostname: bootie.simonet.hub.samcday.com
  labels:
    samcday.com/group: simonet
spec:
  loadBalancerClass: io.cilium/bgp-control-plane
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    name: bootie
  type: LoadBalancer
