apiServer:
  service:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: simonet.hub.samcday.com
    labels:
      samcday.com/group: simonet
    spec:
      externalTrafficPolicy: Local
      loadBalancerClass: io.cilium/bgp-control-plane
      type: LoadBalancer
bootstrapTokens:
  - id: z3r8ou
    extraGroups: [system:bootstrappers:kubeadm:default-node-token]
clusterCIDRs: [172.25.0.0/16]
clusterDNS: [172.26.0.10]
clusterName: simonet
etcd:
  certIssuer:
    name: etcd
    kind: ClusterIssuer
  endpoints:
    - https://hub-az1-cp1.hub.internal:2379
    - https://hub-az1-cp2.hub.internal:2379
    - https://hub-az1-cp3.hub.internal:2379
externalHostname: simonet.hub.samcday.com
parentClusterDomain: cluster.hub.internal
serviceCIDRs: [172.26.0.0/16]
serviceIP: 172.26.0.1
