---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx-internal
  namespace: simonet
spec:
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      version: 4.13.0
  driftDetection:
    mode: enabled
  interval: 1h
  kubeConfig:
    secretRef:
      name: admin-kubeconfig
  storageNamespace: ingress-nginx
  targetNamespace: ingress-nginx
  values:
    # https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml
    controller: 
      allowSnippetAnnotations: true
      metrics:
        enabled: true
      replicaCount: 3
      service:
        externalTrafficPolicy: Local
        loadBalancerClass: io.cilium/bgp-control-plane
      terminationGracePeriodSeconds: 5
