apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: simonet
configMapGenerator:
  - name: control-plane-values
    files:
      - values.yaml=control-plane-values.yaml
resources:
  - ../../../.kustomize-config
  - bootie.yaml
  - cert-manager.yaml
  - cilium.yaml
  - cloudflare-token.yaml
  - control-plane.yaml
  - coredns.yaml
  - external-dns.yaml
  - ingress-nginx-internal.yaml
  - ingress-nginx-public.yaml
  - metrics-server.yaml
  - namespaces.yaml
  - node-bootstrap-token.yaml
  - oidc-rbac.yaml
  - prometheus-operator-crds.yaml
  - rook-ceph.yaml
  - snapshot-controller.yaml
  - subnet-router.yaml
  - syncthing.yaml
  - tailscale-node-controller.yaml
  - tofu.yaml
  - vpas.yaml
