---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfd
  namespace: simonet
spec:
  chart:
    spec:
      chart: node-feature-discovery
      sourceRef:
        kind: HelmRepository
        name: nfd
        namespace: flux-system
      version: 0.17.3
  driftDetection:
    mode: enabled
  interval: 1h
  kubeConfig:
    secretRef:
      name: admin-kubeconfig
  storageNamespace: kube-system
  targetNamespace: kube-system
  values:
    # https://github.com/kubernetes-sigs/node-feature-discovery/blob/master/deployment/helm/node-feature-discovery/values.yaml
