apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: subnet-router
  namespace: simonet
spec:
  chart:
    spec:
      chart: charts/tailscale-subnet-router
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: infra
        namespace: flux-system
  driftDetection:
    mode: enabled
  interval: 1h
  kubeConfig:
    secretRef:
      name: admin-kubeconfig
  storageNamespace: kube-system
  targetNamespace: kube-system
  values:
    routes: [10.0.6.0/24]
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: subnet-router-ts-auth
  namespace: simonet
spec:
  chart:
    spec:
      chart: charts/resources
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: infra
        namespace: flux-system
  driftDetection:
    mode: enabled
  interval: 1h
  kubeConfig:
    secretRef:
      name: admin-kubeconfig
  storageNamespace: kube-system
  targetNamespace: kube-system
  values:
    subnet-router-ts-auth:
      kind: Secret
  valuesFrom:
    - kind: Secret
      name: subnet-router-ts-auth
      valuesKey: key
      targetPath: subnet-router-ts-auth.stringData.key
